/* Linearization */
#include "ThreePhaseMotor_PWM_model.h"
#if defined(__cplusplus)
extern "C" {
#endif
const char *ThreePhaseMotor_PWM_linear_model_frame()
{
  return "model linearized_model \"ThreePhaseMotor_PWM\"\n"
  "  parameter Integer n = 4 \"number of states\";\n"
  "  parameter Integer m = 5 \"number of inputs\";\n"
  "  parameter Integer p = 9 \"number of outputs\";\n"
  "\n"
  "  parameter Real x0[n] = %s;\n"
  "  parameter Real u0[m] = %s;\n"
  "\n"
  "  parameter Real A[n, n] =\n\t[%s];\n\n"
  "  parameter Real B[n, m] =\n\t[%s];\n\n"
  "  parameter Real C[p, n] =\n\t[%s];\n\n"
  "  parameter Real D[p, m] =\n\t[%s];\n\n"
  "\n"
  "  Real x[n](start=x0);\n"
  "  input Real u[m](start=u0);\n"
  "  output Real y[p];\n"
  "\n"
  "  Real 'x_i_d' = x[1];\n"
  "  Real 'x_i_q' = x[2];\n"
  "  Real 'x_omega_m' = x[3];\n"
  "  Real 'x_theta_e' = x[4];\n"
  "  Real 'u_T_load' = u[1];\n"
  "  Real 'u_duty_a' = u[2];\n"
  "  Real 'u_duty_b' = u[3];\n"
  "  Real 'u_duty_c' = u[4];\n"
  "  Real 'u_v_dc' = u[5];\n"
  "  Real 'y_T_em_out' = y[1];\n"
  "  Real 'y_emf_a' = y[2];\n"
  "  Real 'y_emf_b' = y[3];\n"
  "  Real 'y_emf_c' = y[4];\n"
  "  Real 'y_i_a' = y[5];\n"
  "  Real 'y_i_b' = y[6];\n"
  "  Real 'y_i_c' = y[7];\n"
  "  Real 'y_speed_rpm' = y[8];\n"
  "  Real 'y_theta_m' = y[9];\n"
  "equation\n"
  "  der(x) = A * x + B * u;\n"
  "  y = C * x + D * u;\n"
  "end linearized_model;\n";
}
const char *ThreePhaseMotor_PWM_linear_model_datarecovery_frame()
{
  return "model linearized_model \"ThreePhaseMotor_PWM\"\n"
  "  parameter Integer n = 4 \"number of states\";\n"
  "  parameter Integer m = 5 \"number of inputs\";\n"
  "  parameter Integer p = 9 \"number of outputs\";\n"
  "  parameter Integer nz = 30 \"data recovery variables\";\n"
  "\n"
  "  parameter Real x0[n] = %s;\n"
  "  parameter Real u0[m] = %s;\n"
  "  parameter Real z0[nz] = %s;\n"
  "\n"
  "  parameter Real A[n, n] =\n\t[%s];\n\n"
  "  parameter Real B[n, m] =\n\t[%s];\n\n"
  "  parameter Real C[p, n] =\n\t[%s];\n\n"
  "  parameter Real D[p, m] =\n\t[%s];\n\n"
  "  parameter Real Cz[nz, n] =\n\t[%s];\n\n"
  "  parameter Real Dz[nz, m] =\n\t[%s];\n\n"
  "\n"
  "  Real x[n](start=x0);\n"
  "  input Real u[m](start=u0);\n"
  "  output Real y[p];\n"
  "  output Real z[nz];\n"
  "\n"
  "  Real 'x_i_d' = x[1];\n"
  "  Real 'x_i_q' = x[2];\n"
  "  Real 'x_omega_m' = x[3];\n"
  "  Real 'x_theta_e' = x[4];\n"
  "  Real 'u_T_load' = u[1];\n"
  "  Real 'u_duty_a' = u[2];\n"
  "  Real 'u_duty_b' = u[3];\n"
  "  Real 'u_duty_c' = u[4];\n"
  "  Real 'u_v_dc' = u[5];\n"
  "  Real 'y_T_em_out' = y[1];\n"
  "  Real 'y_emf_a' = y[2];\n"
  "  Real 'y_emf_b' = y[3];\n"
  "  Real 'y_emf_c' = y[4];\n"
  "  Real 'y_i_a' = y[5];\n"
  "  Real 'y_i_b' = y[6];\n"
  "  Real 'y_i_c' = y[7];\n"
  "  Real 'y_speed_rpm' = y[8];\n"
  "  Real 'y_theta_m' = y[9];\n"
  "  Real 'z_$cse1' = z[1];\n"
  "  Real 'z_$cse2' = z[2];\n"
  "  Real 'z_$cse3' = z[3];\n"
  "  Real 'z_$cse4' = z[4];\n"
  "  Real 'z_T_em_out' = z[5];\n"
  "  Real 'z_T_load' = z[6];\n"
  "  Real 'z_duty_a' = z[7];\n"
  "  Real 'z_duty_b' = z[8];\n"
  "  Real 'z_duty_c' = z[9];\n"
  "  Real 'z_emf_a' = z[10];\n"
  "  Real 'z_emf_b' = z[11];\n"
  "  Real 'z_emf_c' = z[12];\n"
  "  Real 'z_i_a' = z[13];\n"
  "  Real 'z_i_b' = z[14];\n"
  "  Real 'z_i_beta' = z[15];\n"
  "  Real 'z_i_c' = z[16];\n"
  "  Real 'z_omega_e' = z[17];\n"
  "  Real 'z_speed_rpm' = z[18];\n"
  "  Real 'z_theta_m' = z[19];\n"
  "  Real 'z_v_a_leg' = z[20];\n"
  "  Real 'z_v_alpha' = z[21];\n"
  "  Real 'z_v_b' = z[22];\n"
  "  Real 'z_v_b_leg' = z[23];\n"
  "  Real 'z_v_beta' = z[24];\n"
  "  Real 'z_v_c' = z[25];\n"
  "  Real 'z_v_c_leg' = z[26];\n"
  "  Real 'z_v_d_cmd' = z[27];\n"
  "  Real 'z_v_dc' = z[28];\n"
  "  Real 'z_v_neutral' = z[29];\n"
  "  Real 'z_v_q_cmd' = z[30];\n"
  "equation\n"
  "  der(x) = A * x + B * u;\n"
  "  y = C * x + D * u;\n"
  "  z = Cz * x + Dz * u;\n"
  "end linearized_model;\n";
}
#if defined(__cplusplus)
}
#endif

