@echo off
REM =============================================================================
REM cleanup.bat  —  Remove all generated / compiled artefacts from c_src
REM =============================================================================
REM Keeps only the files you need to hand in or version-control:
REM
REM   KEEP (source files you author):
REM     *.h   *.c               C headers and implementations
REM     *.pyx                   Cython wrapper sources
REM     setup_*.py              Per-module build scripts
REM     build_all.bat / .sh     Top-level build drivers
REM     cleanup.bat / .sh       This script
REM     BUILD.md                Build instructions
REM
REM   DELETE (generated / compiled, always re-creatable):
REM     build\                  setuptools build tree
REM     *.pyd                   Compiled Windows extension modules
REM     *.so                    Compiled Linux/macOS extension modules
REM     *.c   generated by Cython from *.pyx  (same base name as .pyx)
REM     *.html                  Cython annotation files
REM     __pycache__\            Python bytecode cache
REM     *.pyc                   Compiled Python bytecodes
REM
REM Usage:
REM   cd pmsm_blocks\c_src
REM   cleanup.bat
REM =============================================================================

echo ============================================================
echo  Cleaning c_src build artefacts
echo ============================================================

cd /d "%~dp0"

REM -- setuptools build tree ---------------------------------------------------
if exist build (
    echo Removing build\...
    rmdir /s /q build
)

REM -- Compiled extension modules (.pyd) ---------------------------------------
echo Removing *.pyd...
for /r . %%f in (*.pyd) do del /q "%%f"

REM -- Cython-generated C files (same stem as .pyx, NOT our hand-written .c) --
REM   Our hand-written C files: pmsm_motor.c  transforms.c  pi_controller.c
REM   Cython-generated C files: pmsm_motor_wrapper.c  transforms_wrapper.c  pi_controller_wrapper.c
echo Removing Cython-generated *.c files (not hand-written sources)...
if exist pmsm_motor_wrapper.c    del /q pmsm_motor_wrapper.c
if exist transforms_wrapper.c    del /q transforms_wrapper.c
if exist pi_controller_wrapper.c del /q pi_controller_wrapper.c

REM -- Cython annotation HTML --------------------------------------------------
echo Removing *.html annotation files...
for /r . %%f in (*.html) do del /q "%%f"

REM -- Python bytecode cache ---------------------------------------------------
echo Removing __pycache__...
if exist __pycache__ rmdir /s /q __pycache__
for /r . %%d in (__pycache__) do (
    if exist "%%d" rmdir /s /q "%%d"
)
for /r . %%f in (*.pyc) do del /q "%%f"

echo.
echo ============================================================
echo  Done.  Remaining files (source only):
echo ============================================================
dir /b /o:n
