/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title PMSM FOC using AURIX TC3xx
 * \abstract This example describes the implementation of Permanent Magnet Synchronous Motors (PMSM) Field Oriented Control (FOC) software for a 3-phase motor using the Infineon AURIXÃ¢â€žÂ¢ TC3x microcontroller.
 * \description The intention of this software development kit (SDK) is to offer functionality to drive Permanent Magnet
 *              Synchronous Motors (PMSM) in sensor mode using AURIXâ„¢ TC3x devices. It contains all the common modules
 *              necessary for the modes as generic drives, and provides a high level of configurability and modularity
 *              to address different segments. The Field Oriented Control (FOC) is a method of motor control to generate
 *              three phase sinusoidal signals which can be easily controlled with frequency and amplitude in order to
 *              minimize the current, which in turn means to maximize the efficiency. The basic idea is to transform
 *              three phase signals into two rotor-fix signals and vice-versa.
 *              
 *              With this example, FreeRTOSâ„¢ is integrated. The operating system functions can only be used with TriCoreâ„¢ CPU0.
 *
 * \name AURIX_TC3x_Motor_Control_SDK
 * \version V1.0.4
 * \board APPLICATION KIT TC3X7 V2.0, KIT_A2G_TC387_5V_TFT, TC38xQP_A-Step
 * \board APPLICATION KIT TC3X7 V2.0, , 
 * \keywords PMSM, FOC, AURIX, Motor Control, xEV
 * \documents AP32540
 * \documents AP32541
 * \documents see README.md
 * \lastUpdated 2025-07-19
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "FreeRTOS.h"
#include "PmsmFoc_UserConfig.h"
#include "PmsmFoc_Functions.h"
#include "Mcu_Init.h"
#include "Display_Functions.h"
#include "PmsmFoc_Interface.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
MotorControl        g_motorControl;                 /**< Motor control instance. */
IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;   /**< CPU synchronization event. */

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Wait for CPU synchronization */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    /* Initialize motor control */
    PmsmFoc_initMotorControl(&g_motorControl);

    /* Initialize display */
    Dispaly_initDisplay();

#if(ONEEYE_MODE == ENABLED)
    /* Initialize OneEye GUI */
    OneEye_initOneEye();
#endif

    /* Initialize operating system tasks */
    extern void OS_Tasks_init(void);
    OS_Tasks_init();

    while(1)
    {
    }
}
