/* Simulation code for SpiralGalaxy generated by the OpenModelica Compiler OpenModelica v1.25.7 (64-bit). */
#if !defined(SpiralGalaxy__MODEL_H)
#define SpiralGalaxy__MODEL_H

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#if defined(__cplusplus)
extern "C" {
#endif

#include <string.h>

#include "SpiralGalaxy_functions.h"


extern void SpiralGalaxy_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void SpiralGalaxy_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int SpiralGalaxy_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int SpiralGalaxy_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int SpiralGalaxy_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int SpiralGalaxy_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int SpiralGalaxy_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int SpiralGalaxy_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int SpiralGalaxy_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int SpiralGalaxy_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int SpiralGalaxy_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int SpiralGalaxy_checkForAsserts(DATA *data, threadData_t *threadData);
extern int SpiralGalaxy_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int SpiralGalaxy_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int SpiralGalaxy_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* SpiralGalaxy_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* SpiralGalaxy_relationDescription(int i);
extern void SpiralGalaxy_function_initSample(DATA *data, threadData_t *threadData);
extern int SpiralGalaxy_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SpiralGalaxy_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SpiralGalaxy_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SpiralGalaxy_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SpiralGalaxy_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SpiralGalaxy_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SpiralGalaxy_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *jacobian);
extern int SpiralGalaxy_functionJacG_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int SpiralGalaxy_functionJacA_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int SpiralGalaxy_functionJacB_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int SpiralGalaxy_functionJacC_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int SpiralGalaxy_functionJacD_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int SpiralGalaxy_functionJacF_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern int SpiralGalaxy_functionJacH_column(DATA* data, threadData_t *threadData, ANALYTIC_JACOBIAN *thisJacobian, ANALYTIC_JACOBIAN *parentJacobian);
extern const char* SpiralGalaxy_linear_model_frame(void);
extern const char* SpiralGalaxy_linear_model_datarecovery_frame(void);
extern int SpiralGalaxy_mayer(DATA* data, modelica_real** res, short *);
extern int SpiralGalaxy_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int SpiralGalaxy_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int SpiralGalaxy_setInputData(DATA *data, const modelica_boolean file);
extern int SpiralGalaxy_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void SpiralGalaxy_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void SpiralGalaxy_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int SpiralGalaxy_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void SpiralGalaxy_read_simulation_info(SIMULATION_INFO* simulationData);
extern void SpiralGalaxy_read_input_fmu(MODEL_DATA* modelData);
extern void SpiralGalaxy_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int SpiralGalaxy_inputNames(DATA* data, char ** names);
extern int SpiralGalaxy_dataReconciliationInputNames(DATA* data, char ** names);
extern int SpiralGalaxy_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int SpiralGalaxy_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int SpiralGalaxy_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int SpiralGalaxy_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "SpiralGalaxy_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(SpiralGalaxy__MODEL_H) */


