/*
 * \file PmsmFoc_Functions.h
 * \brief Field-Oriented Control (FOC) functions for PMSM motor control systems.
 * \ingroup pmsm_foc_controlmodules
 * \version 1.0.0
 * \date 2019
 * \details
 * This header file defines the data structures, enumerations, and function prototypes
 * required for implementing Field-Oriented Control (FOC) in PMSM motor control systems.
 * It includes functions for current reconstruction, Clarke and Park transformations,
 * PI control, and other FOC-related operations.
 *
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef PMSM_FOC_CONTROLMODULES_PMSM_FOC_FUNCTIONS_H
#define PMSM_FOC_CONTROLMODULES_PMSM_FOC_FUNCTIONS_H

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "Ifx_Types.h"
#include "Ifx_PicF32.h"
#include "IfxStdIf_Pos.h"
#include "PmsmFoc_Inverter.h"
#include "PmsmFoc_Motor.h"
#include "PmsmFoc_PositionAndSpeedAcquisition.h"
#include "SysSe/Math/Ifx_RampF32.h"
#include "Arith.StdReal.h"
#include "MotorControl.h"
#include "PmsmFoc_SpeedControl.h"

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/
/**
 * \brief State machine states for motor control.
 * \details
 * Enumerates the possible states of the PMSM motor control state machine.
 */
typedef enum StateMachine
{
    StateMachine_calibration = 0,        /**< Calibration state. */
    StateMachine_focClosedLoop,         /**< Field-Oriented Control closed-loop mode. */
    StateMachine_enableInverter,        /**< Enable inverter state. */
    StateMachine_vfOpenLoop,            /**< Open-loop V/F control state. */
    StateMachine_tuneCurrentRegulators, /**< Current regulator tuning state. */
    StateMachine_prePositioning,        /**< Pre-positioning state for rotor alignment. */
    StateMachine_motorIdle,             /**< Motor idle state. */
    StateMachine_motorStop,             /**< Motor stopped state. */
    StateMachine_motorHold,             /**< Motor hold state. */
    StateMachine_identifyMotorParameters /**< Identify motor parameters state. */
} StateMachine;

/**
 * \brief Control schemes for motor control.
 * \details Enumerates the different control schemes available for PMSM motor control.
 */
typedef enum ControlScheme
{
    ControlScheme_speed = 0, /**< Speed control scheme. */
    ControlScheme_current,   /**< Current control scheme. */
    ControlScheme_torque,    /**< Torque control scheme. */
    ControlScheme_voltage    /**< Voltage control scheme. */
} ControlScheme;

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/
/**
 * \brief Interface information for motor control.
 */
typedef struct
{
    uint32 running;                 /**< \brief 1 = Motor is running; 0 = Motor is stopped. */
    uint32 start;                   /**< \brief 1 = Request to start; 0 = No effect. */
    uint32 stop;                    /**< \brief 1 = Request to stop; 0 = No effect. */
    uint32 demo;                    /**< \brief 1 = Start demo; 0 = Stop demo. */
    sint32 motorTargetSpeed;        /**< \brief Target speed in RPM. */
    uint32 hadEmergency;            /**< \brief 1 = Emergency event occurred; 0 = No event. */
} Interfaces;

/**
 * \brief Open-loop control information for PMSM motors.
 */
typedef struct
{
    float32 amplitude;              /**< \brief Vector amplitude in open-loop mode (Range: [0, 1]). */
    uint32 electricalAngleDelta;    /**< \brief Delta angle for electrical position (Q16.16 format). */
    uint32 electricalAngle;         /**< \brief Electrical angle in open-loop mode. */
#if(EMOTOR_LIB == MC_EMOTOR)
    CplxStdReal AngleCosSin;        /**< \brief Sin and Cos values of the angle. */
    CplxStdReal modulationIndex;    /**< \brief Modulation index for SVM. */
#endif
} OpenLoop;

/**
 * \brief Field-Oriented Control (FOC) information.
 * \details
 * This structure contains parameters, states, and objects used for
 * Field-Oriented Control (FOC) in PMSM motor control systems.
 */
typedef struct
{
#if (EMOTOR_LIB == MC_EMOTOR)
    /* Phase Current and Voltage Information */
    T3Phase iPhaseMeas;             /**< \brief Measured phase currents (U, V, W). */
    T3Phase bemf;                   /**< \brief Measured Back-EMF values (U, V, W). */
    CplxStdReal iab;                /**< \brief Alpha/Beta values of current space vector. */
    CplxStdReal vabRef;             /**< \brief Reference Alpha/Beta values of voltage space vector. */

    /* DQ-Axis Current and Voltage Information */
    CplxStdReal idqRef;             /**< \brief Reference DQ-axis current space vector. */
    CplxStdReal idqRefExternal;     /**< \brief External DQ-axis current reference space vector. */
    CplxStdReal idqMeas;            /**< \brief Measured DQ-axis current space vector. */
    CplxStdReal idqError;           /**< \brief DQ-axis current error (reference - measured). */
    CplxStdReal vdqRef;             /**< \brief Reference DQ-axis voltage space vector. */
    StdReal vdqMag;                 /**< \brief Magnitude of voltage space vector. */

    /* Angular Information */
    CplxStdReal CurrentAngleCosSin; /**< \brief Sin and Cos values of the current angle. */
    CplxStdReal VoltageAngleCosSin; /**< \brief Sin and Cos values of the voltage angle. */
    sint16 electricalAngle;         /**< \brief Rotor angle (Encoder, Resolver, Estimator, etc.). */

    /* Torque Information */
    StdReal torqueRef;              /**< \brief Torque command or output of speed regulator. */
    StdReal torqueEst;              /**< \brief Estimated torque based on motor parameters and currents. */

    /* Control Objects */
    Ifx_PicF32 piId;                /**< \brief PI controller for the D-axis current. */
    Ifx_PicF32 piIq;                /**< \brief PI controller for the Q-axis current. */
    SpeedControl speedControl;      /**< \brief Speed control object. */

    /* Reference Ramps */
    Ifx_RampF32 speedRamp;          /**< \brief Speed reference ramp. */
    Ifx_RampF32 idRefExternalRamp;  /**< \brief External D-axis current reference ramp. */
    Ifx_RampF32 iqRefExternalRamp;  /**< \brief External Q-axis current reference ramp. */

    /* Modulation Information */
    CplxStdReal modulationIndex;    /**< \brief Modulation index for Space Vector Modulation (SVM). */

#endif /* (EMOTOR_LIB == MC_EMOTOR) */
} PmsmFoc;

/**
 * \brief Control parameters for PMSM motor control.
 * \details
 * This structure contains various control parameters, counters, and flags
 * for managing motor operation and calibration in PMSM motor control systems.
 */
typedef struct
{
    /* Motor Control State and Scheme */
    uint32 state;                  /**< \brief Motor state (e.g.: V/f, FOC). */
    ControlScheme controlScheme;   /**< \brief Control scheme (e.g., speed control, current control). */

    /* Motor Rotation and Inverter Status */
    uint16 rotationDir;            /**< \brief Rotation direction of motor:
                                         - Increasing rotor angle
                                         - Decreasing rotor angle. */
    uint16 inverterStatus;         /**< \brief 0 -> Inverter disabled, 1 -> Inverter enabled. */

    /* General Purpose Counters */
    uint32 counter;                /**< \brief General-purpose counter. */
    uint32 rampCounter;            /**< \brief Counter for motor speed ramp up/down. */
    uint32 alignmentCounter;       /**< \brief Counter for rotor initial positioning / alignment in V/F. */
    uint32 nonRealTimeCounter;     /**< \brief Counter for non-real-time tasks. */

    /* Calibration Counters */
    uint32 encOffsetCalCounter;    /**< \brief Counter for encoder offset calibration. */
    uint32 encTopZeroCounter;      /**< \brief Counter for encoder top zero calibration. */
    uint32 tuneCurrentRegsCounter; /**< \brief Counter for current regulator calibration. */

    /* Calibration and Tuning Flags */
    boolean tuneCurrentRegs;       /**< \brief Current regulator tuning flag:
                                         - `TRUE`: Tuning enabled.
                                         - `FALSE`: Tuning disabled. */
} ControlParameters;

/**
 * \brief Diagnostic parameters for PMSM motor control.
 * \details
 * This structure contains various diagnostic parameters, flags, and settings
 * used to monitor and configure the motor control system.
 */
typedef struct
{
    /* Motor Phase and Rotation Settings */
    boolean swapped;                        /**< \brief Indicates if phases A and B are swapped:
                                            - `FALSE`: ABC sequence.
                                            - `TRUE`: ACB sequence (used in @ref DIAG mode). */
    uint16 rotate;                          /**< \brief Phase rotation pattern (range: [0, 2]):
                                            - Swapped = `FALSE`: 0 (ABC), 1 (CAB), 2 (BCA).
                                            - Swapped = `TRUE`: 0 (ACB), 1 (BAC), 2 (CBA). */

    /* Control Enable Flags */
    boolean focControlEnabled;              /**< \brief Specifies if Field-Oriented Control (FOC) is enabled:
                                            - `TRUE`: FOC is enabled.
                                            - `FALSE`: FOC is disabled. */
    boolean encoderEnabled;                 /**< \brief Indicates if the position sensor (encoder) is enabled:
                                            - `TRUE`: Encoder is enabled.
                                            - `FALSE`: Encoder is disabled. */

    /* Diagnostic and Calibration Settings */
    uint16 maxTurn;                         /**< \brief Maximum number of turns allowed before stopping
                                            (used in @ref DIAG mode). */
    sint32 electricalAngleOffset;           /**< \brief Electrical angle offset for calibration. */
    sint32 electricalAngleSensor;           /**< \brief Current electrical angle from the position sensor. */
    boolean encCalStatus;                   /**< \brief Encoder calibration status:
                                            - `TRUE`: Calibration completed.
                                            - `FALSE`: Calibration not completed. */
} Diagnostic;

/**
 * \brief Motor control structure for PMSM FOC.
 * \details
 * Contains all the parameters, states, and objects required for Field-Oriented Control.
 */
typedef struct
{
    Interfaces interface;                  /**< \brief Interface parameters. */
    ControlParameters controlParameters;   /**< \brief Control parameters object. */
    Diagnostic diagnostic;                 /**< \brief Diagnostic object. */
    Inverter inverter;                     /**< \brief Inverter object. */
    PmsmFoc pmsmFoc;                       /**< \brief FOC object. */
    OpenLoop openLoop;                     /**< \brief Open loop object. */
    PositionAcquisition positionSensor;    /**< \brief Position sensor object. */
    MotorParameters motor;                 /**< \brief Motor parameters object. */
} MotorControl;

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
extern MotorControl g_motorControl;

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/

/**
 * \brief Initialize the motor control structure.
 * \details
 * This function initializes the various components of the motor control structure,
 * including control variables, hardware peripherals, and calibration resets.
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 */
IFX_EXTERN void PmsmFoc_initMotorControl(MotorControl* const motorCtrl);

/**
 * \brief Initializes the control variables for motor control.
 * \details
 * Configures and initializes all control variables in the motor control structure.
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 */
IFX_EXTERN void PmsmFoc_initControlVariables(MotorControl* const motorCtrl);

/**
 * \brief Executes the Field-Oriented Control (FOC) algorithm.
 * \details
 * Implements the steps for FOC, including Clarke and Park transformations, PI control,
 * voltage limit handling, and space vector modulation.
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 */
IFX_EXTERN void PmsmFoc_doFieldOrientedControl(MotorControl* const motorCtrl);

/**
 * \brief Executes V/F control for the motor.
 * \details
 * Implements open-loop voltage-to-frequency control for PMSM motor systems.
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 */
IFX_EXTERN void PmsmFoc_doVfControl(MotorControl* const motorCtrl);

/**
 * \brief Reconstructs the motor phase currents from the ADC values.
 * \details
 * Reads the ADC results and calculates the phase currents for further processing.
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 */
IFX_EXTERN void PmsmFoc_reconstructCurrent(MotorControl* const motorCtrl);

/**
 * \brief Perform Clarke transformation on motor currents.
 * \details
 * Converts the measured phase currents into a stationary reference frame (Alpha/Beta).
 *
 * \param[in,out] foc Pointer to the FOC structure.
 */
IFX_EXTERN void PmsmFoc_doClarkeTransform(PmsmFoc* const foc);

/**
 * \brief Calculate Sin and Cos values for a given electrical angle.
 * \details
 * Computes the Sin and Cos values for the current electrical angle used in transformations.
 *
 * \param[in,out] foc Pointer to the FOC structure.
 */
IFX_EXTERN void PmsmFoc_getCosSin(PmsmFoc* const foc);

/**
 * \brief Perform Park transformation on motor currents.
 * \details
 * Converts the stationary Alpha/Beta reference frame currents into the rotating DQ-axis reference frame.
 *
 * \param[in,out] foc Pointer to the FOC structure.
 */
IFX_EXTERN void PmsmFoc_doParkTransform(PmsmFoc* const foc);

/**
 * \brief Set the DQ-axis current reference.
 * \details
 * Configures the reference current values for the D-axis and Q-axis in the FOC structure.
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 */
IFX_EXTERN void PmsmFoc_setIdqRef(MotorControl* const motorCtrl);

/**
 * \brief Get the current DQ-axis reference values.
 * \details
 * Retrieves the current reference values for the D-axis and Q-axis currents.
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 */
IFX_EXTERN void PmsmFoc_getIdqRef(MotorControl* const motorCtrl);

/**
 * \brief Set the D-axis current reference limits.
 * \details
 * Configures the minimum and maximum limits for the D-axis current reference.
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 * \param[in] min Minimum limit for the D-axis current reference.
 * \param[in] max Maximum limit for the D-axis current reference.
 */
IFX_EXTERN void PmsmFoc_setIdRefLimit(MotorControl* const motorCtrl, float32 min, float32 max);

/**
 * \brief Set the Q-axis current reference limits.
 * \details
 * Configures the minimum and maximum limits for the Q-axis current reference.
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 * \param[in] min Minimum limit for the Q-axis current reference.
 * \param[in] max Maximum limit for the Q-axis current reference.
 */
IFX_EXTERN void PmsmFoc_setIqRefLimit(MotorControl* const motorCtrl, float32 min, float32 max);

/**
 * \brief Get the D-axis current reference limit.
 * \details
 * Retrieves the currently configured D-axis current reference limit.
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 * \return The D-axis current reference limit.
 */
IFX_EXTERN StdReal PmsmFoc_getIdRefLimit(MotorControl* const motorCtrl);

/**
 * \brief Get the Q-axis current reference limit.
 * \details
 * Retrieves the currently configured Q-axis current reference limit.
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 * \return The Q-axis current reference limit.
 */
IFX_EXTERN StdReal PmsmFoc_getIqRefLimit(MotorControl* const motorCtrl);

/**
 * \brief Perform D-axis current control.
 * \details
 * Executes the PI control loop for the D-axis current.
 *
 * \param[in,out] foc Pointer to the FOC structure.
 */
IFX_EXTERN void PmsmFoc_doIdControl(PmsmFoc* const foc);

/**
 * \brief Perform Q-axis current control.
 * \details
 * Executes the PI control loop for the Q-axis current.
 *
 * \param[in,out] foc Pointer to the FOC structure.
 */
IFX_EXTERN void PmsmFoc_doIqControl(PmsmFoc* const foc);

/**
 * \brief Get the magnitude of the DQ-axis voltage space vector.
 * \details
 * Calculates the magnitude of the voltage space vector in the DQ-axis.
 *
 * \param[in,out] foc Pointer to the FOC structure.
 * \return The magnitude of the DQ-axis voltage space vector.
 */
IFX_EXTERN StdReal PmsmFoc_getVdqMagnitude(PmsmFoc* const foc);

/**
 * \brief Get the voltage limit for the DQ-axis.
 * \details
 * Retrieves the currently configured voltage limit for the DQ-axis.
 *
 * \param[in,out] foc Pointer to the FOC structure.
 * \return The DQ-axis voltage limit.
 */
IFX_EXTERN StdReal PmsmFoc_getVdqLimit(PmsmFoc* const foc);

/**
 * \brief Set the voltage limit for the DQ-axis.
 * \details
 * Configures the voltage limit for the DQ-axis.
 *
 * \param[in,out] foc Pointer to the FOC structure.
 */
IFX_EXTERN void PmsmFoc_setVdqLimit(PmsmFoc* const foc);

/**
 * \brief Limit the DQ-axis voltage space vector.
 * \details
 * Ensures that the voltage space vector magnitude does not exceed the configured limit.
 *
 * \param[in,out] foc Pointer to the FOC structure.
 */
IFX_EXTERN void PmsmFoc_doVdqLimit(PmsmFoc* const foc);

/**
 * \brief Perform inverse Park transformation.
 * \details
 * Converts the rotating DQ-axis voltage space vector back to the stationary Alpha/Beta reference frame.
 *
 * \param[in,out] foc Pointer to the FOC structure.
 */
IFX_EXTERN void PmsmFoc_doInverseParkTransform(PmsmFoc* const foc);

/**
 * \brief Perform DQ decoupling.
 * \details
 * Applies feedforward decoupling to the DQ-axis voltage space vector.
 *
 * \param[in,out] foc Pointer to the FOC structure.
 */
IFX_EXTERN void PmsmFoc_doDqDecoupling(PmsmFoc* const foc);

/**
 * \brief Perform miscellaneous tasks for motor control.
 * \details
 * Executes additional non-critical tasks for motor control.
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 */
IFX_EXTERN void PmsmFoc_doMiscWorks (MotorControl* const motorCtrl);

/**
 * \brief Executes speed control for the motor.
 * \details
 * Calculates the control output based on the reference and measured speed.
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 */
IFX_EXTERN void PmsmFoc_doSpeedControl(MotorControl* const motorCtrl);

/**
 * \brief Executes the encoder calibration process.
 * \details
 * Implements the steps required for calibrating the encoder in PMSM motor control systems.
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 */
IFX_EXTERN void PmsmFoc_doEncoderCalibration(MotorControl* const motorCtrl);

/**
 * \brief Resets the encoder calibration status.
 * \details
 * Resets the encoder calibration status and synchronization flags in the motor control structure.
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 */
IFX_EXTERN void PmsmFoc_resetEncoderCalibrationStatus(MotorControl* const motorCtrl);

/**
 * \brief Tunes the current regulator for the motor.
 * \details
 * Implements steps to tune the current regulator by alternating current references.
 *
 * *
 * Iq_ref:   _ _ _ _ _ _ _ __ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
 *                   _ _ _ _         _ _ _ _         _ _ _ _
 * Id_ref:   _ _ _ _|       |_ _ _ _|       |_ _ _ _|       |
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 */
IFX_EXTERN void PmsmFoc_tuneCurrentRegulator(MotorControl* const motorCtrl);

/**
 * \brief Perform periodic routines for motor control.
 * \details
 * Executes periodic routines required for motor operation and diagnostics.
 *
 * \param[in,out] motorCtrl Pointer to the motor control structure.
 */
IFX_EXTERN void PmsmFoc_doPeriodicRoutine (MotorControl* const motorCtrl);

/******************************************************************************/
/*-------------------------Inline Function Prototypes-------------------------*/
/******************************************************************************/

/**
 * \brief Executes a single step in the speed reference linear ramp.
 * \details
 * Increments the speed reference ramp by its configured step value.
 *
 * \param[in,out] foc Pointer to the Field-Oriented Control (FOC) object.
 */
IFX_INLINE void PmsmFoc_doSpeedRefLinearRamp(PmsmFoc* const foc);

/**
 * \brief Executes a step in the current reference linear ramp.
 * \details
 * Increments both the D-axis and Q-axis current reference ramps by their configured step values.
 *
 * \param[in,out] foc Pointer to the Field-Oriented Control (FOC) object.
 */
IFX_INLINE void PmsmFoc_doCurrentRefLinearRamp(PmsmFoc* const foc);

/**
 * \brief Retrieves the current value of the speed reference linear ramp.
 * \details
 * Returns the current value of the speed reference ramp.
 *
 * \param[in] foc Pointer to the Field-Oriented Control (FOC) object.
 * \return The current value of the speed reference ramp.
 */
IFX_INLINE float32 PmsmFoc_getSpeedRefLinearRamp(PmsmFoc* const foc);

/**
 * \brief Retrieves the current value of the DQ-axis current reference linear ramp.
 * \details
 * Returns the current values of the D-axis and Q-axis current reference ramps as a complex number.
 *
 * \param[in] foc Pointer to the Field-Oriented Control (FOC) object.
 * \return The current values of the DQ-axis current reference ramp.
 */
IFX_INLINE CplxStdReal PmsmFoc_getCurrentRefLinearRamp(PmsmFoc* const foc);

/**
 * \brief Sets a new reference value for the speed linear ramp.
 * \details
 * Updates the target value for the speed reference ramp.
 *
 * \param[in,out] foc Pointer to the Field-Oriented Control (FOC) object.
 * \param[in] ref The target reference speed.
 */
IFX_INLINE void PmsmFoc_setSpeedRefLinearRamp(PmsmFoc* const foc, float32 ref);

/**
 * \brief Resets the speed reference linear ramp.
 * \details
 * Resets the speed reference ramp to its initial state.
 *
 * \param[in,out] foc Pointer to the Field-Oriented Control (FOC) object.
 */
IFX_INLINE void PmsmFoc_resetSpeedRefLinearRamp(PmsmFoc* const foc);

/**
 * \brief Resets the Field-Oriented Control (FOC) parameters.
 * \details
 * Resets all control parameters and state variables in the FOC object to their default values.
 *
 * \param[in,out] foc Pointer to the Field-Oriented Control (FOC) object.
 */
IFX_INLINE void PmsmFoc_resetFieldOrientedControl(PmsmFoc* const foc);

/**
 * \brief Sets a new reference value for the DQ-axis current linear ramp.
 * \details
 * Updates the target reference values for the D-axis and Q-axis current ramps.
 *
 * \param[in,out] foc Pointer to the Field-Oriented Control (FOC) object.
 * \param[in] ref The target reference DQ-axis current as a complex number.
 */
IFX_INLINE void PmsmFoc_setCurrentRefLinearRamp(PmsmFoc* const foc, CplxStdReal ref);

/******************************************************************************/
/*---------------------Inline Function Implementations------------------------*/
/******************************************************************************/
IFX_INLINE void PmsmFoc_doSpeedRefLinearRamp(PmsmFoc* const foc)
{
	Ifx_RampF32_step(&foc->speedRamp);
}

IFX_INLINE void PmsmFoc_doCurrentRefLinearRamp(PmsmFoc* const foc)
{
	Ifx_RampF32_step(&foc->iqRefExternalRamp);
	Ifx_RampF32_step(&foc->idRefExternalRamp);
}

IFX_INLINE float32 PmsmFoc_getSpeedRefLinearRamp(PmsmFoc* const foc)
{
	return Ifx_RampF32_getValue(&foc->speedRamp);
}

IFX_INLINE CplxStdReal PmsmFoc_getCurrentRefLinearRamp(PmsmFoc* const foc)
{
	CplxStdReal result;
	result.imag = Ifx_RampF32_getValue(&foc->iqRefExternalRamp);
	result.real = Ifx_RampF32_getValue(&foc->idRefExternalRamp);

	return result;
}

IFX_INLINE void PmsmFoc_setSpeedRefLinearRamp(PmsmFoc* const foc, float32 ref)
{
	Ifx_RampF32_setRef(&foc->speedRamp,ref);
}

IFX_INLINE void PmsmFoc_resetFieldOrientedControl(PmsmFoc* const foc)
{
    foc->CurrentAngleCosSin.imag = 0;
    foc->CurrentAngleCosSin.real = 0;
    foc->VoltageAngleCosSin.imag = 0;
    foc->VoltageAngleCosSin.real = 0;
    foc->idqRef.real = 0.0;
    foc->idqRef.imag = 0.0;
    foc->vdqRef.real = 0.0;
    foc->vdqRef.imag = 0.0;
    foc->idqError.real = 0.0;
    foc->idqError.imag = 0.0;
    foc->vabRef.real = 0.0;
    foc->vabRef.imag = 0.0;
    foc->modulationIndex.real = 0.0;
    foc->modulationIndex.imag = 0.0;
    Ifx_PicF32_reset(&foc->piId);
    Ifx_PicF32_reset(&foc->piIq);
}

IFX_INLINE void PmsmFoc_resetSpeedRefLinearRamp(PmsmFoc* const foc)
{
    Ifx_RampF32_reset(&foc->speedRamp);
}

IFX_INLINE void PmsmFoc_setCurrentRefLinearRamp(PmsmFoc* const foc, CplxStdReal ref)
{
	Ifx_RampF32_setRef(&foc->iqRefExternalRamp,ref.imag);
	Ifx_RampF32_setRef(&foc->idRefExternalRamp,ref.real);
}

#endif /* PMSM_FOC_CONTROLMODULES_PMSM_FOC_FUNCTIONS_H */
