/* Additional record code for DCMotor generated by the OpenModelica Compiler OpenModelica v1.26.3 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "DCMotor_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

