/**
 * @file PmsmFoc_Motor_Nanotec_DB42S02.h
 * @brief Header file for PMSM FOC motor configuration (Nanotec DB42S02).
 * @ingroup pmsm_foc_configuration
 * @version 1.0
 * @date 2019
 * @copyright
 * Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 * @details
 * This file contains macro definitions and configuration parameters specific
 * to the Nanotec DB42S02 motor. These include motor parameters, encoder settings,
 * current controller parameters, and speed control configurations.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef PMSM_FOC_MOTOR_NANOTEC_DB42S02_H_
#define PMSM_FOC_MOTOR_NANOTEC_DB42S02_H_
/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

/**
 * @brief Include user configuration for PMSM FOC applications.
 */
#include "PmsmFoc_UserConfig.h"
#include "Ifx_Types.h"

/******************************************************************************/
/*--------------------------------Macros--------------------------------------*/
/******************************************************************************/

#if (MOTOR_TYPE == NANOTEC_MOTOR_DB42S02)

/**
 * @defgroup Motor_Parameters Motor Parameters
 * @brief Motor-specific configuration parameters for Nanotec DB42S02.
 * @{
 */

/** @brief Define the motor pole pairs number. */
#define USER_MOTOR_POLE_PAIR                            (4U)

/** @brief Define the motor resistance (phase-to-phase) in ohms. */
#define USER_MOTOR_RESISTANCE_PHASE_TO_PHASE            (0.19f)

/** @brief Define the motor inductance (phase-to-phase) in henry. */
#define USER_MOTOR_INDUCTANCE_PHASE_TO_PHASE            (0.245e-3)

/** @brief Define the motor wiring connection type (DELTA or WYE). */
#define USER_MOTOR_WIRING_CONNECTION                    DELTA

#if (USER_MOTOR_WIRING_CONNECTION == DELTA)
/** @brief Define the motor resistance per phase in ohms (DELTA connection). */
#define USER_MOTOR_RESISTANCE_PER_PHASE                 (USER_MOTOR_RESISTANCE_PHASE_TO_PHASE * 3 / 2)
/** @brief Define the motor inductance per phase in henry (DELTA connection). */
#define USER_MOTOR_INDUCTANCE_PER_PHASE                 (USER_MOTOR_INDUCTANCE_PHASE_TO_PHASE * 3 / 2)
#elif (USER_MOTOR_WIRING_CONNECTION == WYE)
/** @brief Define the motor resistance per phase in ohms (WYE connection). */
#define USER_MOTOR_RESISTANCE_PER_PHASE                 (USER_MOTOR_RESISTANCE_PHASE_TO_PHASE / 2)
/** @brief Define the motor inductance per phase in henry (WYE connection). */
#define USER_MOTOR_INDUCTANCE_PER_PHASE                 (USER_MOTOR_INDUCTANCE_PHASE_TO_PHASE / 2)
#endif

/** @} */

/**
 * @defgroup Encoder_Parameters Encoder Parameters
 * @brief Encoder-specific configuration parameters for the motor.
 * @{
 */

/** @brief Define the speed point to switch between position sensing methods (RPM). */
#define USER_MOTOR_SPEED_PULSE_COUNTING_RPM             (1200.0f)

/** @brief Define the incremental encoder offset value. */
#define USER_MOTOR_ENCODER_OFFSET                       (-855)

/** @brief Define the number of incremental encoder pulses per revolution. */
#define USER_MOTOR_ENCODER_PULSES_PER_REVOLUTION        (1000U)

/** @brief Define the incremental encoder maximum speed value in RPM. */
#define USER_MOTOR_ENCODER_MAX_RPM                      (6000.0f)

/** @brief Define top zero calibration delta amplitude. */
#define USER_MOTOR_ENCODER_CAL_TOP_ZERO_AMPL_DELTA      (0.005f)

/** @brief Define top zero calibration maximum amplitude. */
#define USER_MOTOR_ENCODER_CAL_TOP_ZERO_AMPL_MAX        (0.1f)

/** @brief Define top zero calibration angle delta. */
#define USER_MOTOR_ENCODER_CAL_TOP_ZERO_ANGLE_DELTA     (45000U)

/** @brief Define top zero calibration counts. */
#define USER_MOTOR_ENCODER_CAL_TOP_ZERO_COUNTS          (1000U)

/** @brief Define offset calibration delta amplitude. */
#define USER_MOTOR_ENCODER_CAL_OFFSET_AMPL_DELTA        (0.00025f)

/** @brief Define offset calibration maximum amplitude. */
#define USER_MOTOR_ENCODER_CAL_OFFSET_AMPL_MAX          (0.1f)

/** @brief Define offset calibration angle delta. */
#define USER_MOTOR_ENCODER_CAL_OFFSET_ANGLE_DELTA       (1000U)

/** @brief Define offset calibration counts. */
#define USER_MOTOR_ENCODER_CAL_OFFSET_COUNTS            (30000U)

/** @} */

/**
 * @defgroup Speed_Control_Parameters Speed Control Parameters
 * @brief Speed-specific parameters for motor control.
 * @{
 */

/** @brief Define the minimum motor speed limit in RPM. */
#define USER_MOTOR_SPEED_LOW_LIMIT_RPM                  (1.0f)

/** @brief Define the maximum motor speed limit in RPM. */
#define USER_MOTOR_SPEED_HIGH_LIMIT_RPM                 (USER_MOTOR_ENCODER_MAX_RPM)

/** @brief Define the max rpm in 1/min value. */
#define USER_MOTOR_SPEED_CONTROL_MAX_RPM            (USER_MOTOR_SPEED_HIGH_LIMIT_RPM)

/** @brief Define the delta between reference speed and nominal speed. */
#define USER_MOTOR_DELTASPEED                           (1000.0f)

/** @brief Define the maximum speed slew rate in RPM per second. */
#define USER_MOTOR_SPEED_RAMP_SLEW_RATE                 (500.0f)

/** @brief Define the speed ramp function sampling period in seconds. */
#define USER_MOTOR_SPEED_RAMP_PERIOD                    (50e-3f)

/** @brief Define empirical value for speed control KP. */
#define USER_MOTOR_SPEED_KP_MULTI                       (0.000005f)

/** @brief Define empirical value for speed control KI. */
#define USER_MOTOR_SPEED_KI_MULTI                       (0.00004f)

/** @brief Define the speed control KP parameter value. */
#define USER_MOTOR_SPEED_CONTROL_KP                     (USER_MOTOR_SPEED_KP_MULTI * USER_MOTOR_FOC_CALC_KP)

/** @brief Define the speed control KI parameter value. */
#define USER_MOTOR_SPEED_CONTROL_KI                     (USER_MOTOR_SPEED_KI_MULTI * USER_MOTOR_FOC_CALC_KI)

/** @brief Define the maximum speed control parameter value. */
#define USER_MOTOR_SPEED_CONTROL_MAX                    (1.0f)

/** @brief Define the minimum speed control parameter value. */
#define USER_MOTOR_SPEED_CONTROL_MIN                    (-0.3f)

/** @brief Define the speed control period in seconds. */
#define USER_MOTOR_SPEED_CONTROL_PERIOD                 (5e-3)

/** @brief Define the initial motor speed reference value in RPM. */
#define USER_MOTOR_SPEED_CONTROL_REF                    (0.0f)

/** @} */

/**
 * @defgroup Current_Control_Parameters Current Control Parameters
 * @brief Parameters for D-axis and Q-axis current control.
 * @{
 */

/** @brief Define the maximum q-axis current slew rate in amperes per second. */
#define USER_MOTOR_CURRENT_Q_RAMP_SLEW_RATE             (100e-3f)

/** @brief Define the sampling period of the q-axis current ramp function in seconds. */
#define USER_MOTOR_CURRENT_Q_RAMP_PERIOD                (5e-3f)

/** @brief Define the maximum d-axis current slew rate in amperes per second. */
#define USER_MOTOR_CURRENT_D_RAMP_SLEW_RATE             (100e-3f)

/** @brief Define the sampling period of the d-axis current ramp function in seconds. */
#define USER_MOTOR_CURRENT_D_RAMP_PERIOD                (5e-3f)

/** @brief Define the D-axis current regulator Kp parameter adjustment value. */
#define USER_MOTOR_KPD_MULTI                            (0.50f)

/** @brief Define the D-axis current regulator Ki parameter adjustment value. */
#define USER_MOTOR_KID_MULTI                            (0.001f)

/** @brief Define the Q-axis current regulator Kp parameter adjustment value. */
#define USER_MOTOR_KPQ_MULTI                            (0.5f)

/** @brief Define the Q-axis current regulator Ki parameter adjustment value. */
#define USER_MOTOR_KIQ_MULTI                            (0.001f)

/** @brief Define the bandwidth of the PI controller in Hz. */
#define USER_MOTOR_CURRENT_PI_CONTROLLER_BANDWITH       (1000.0f)

/** @brief Define the stator time constant. */
#define USER_MOTOR_FOC_CALC_TSTATOR                     ((USER_MOTOR_INDUCTANCE_PER_PHASE) / \
                                                         (USER_MOTOR_RESISTANCE_PER_PHASE))

/** @brief Define the DQ-axis current controller parameter scaling factor. */
#define USER_MOTOR_FOC_K_FACTOR                         (1.0 / (USER_INVERTER_VDC_LINK_V * IFX_TWO_OVER_PI))

/** @brief Define the DQ-axis current controller Ki parameter value. */
#define USER_MOTOR_FOC_CALC_KI                          ((USER_MOTOR_RESISTANCE_PER_PHASE) / \
                                                         (1 / (2 * IFX_PI * USER_MOTOR_CURRENT_PI_CONTROLLER_BANDWITH)) * \
                                                         USER_MOTOR_FOC_K_FACTOR)

/** @brief Define the DQ-axis current controller Kp parameter value. */
#define USER_MOTOR_FOC_CALC_KP                          (USER_MOTOR_FOC_CALC_KI * USER_MOTOR_FOC_CALC_TSTATOR)

/** @brief Define the adjusted D-axis current regulator Kp parameter value. */
#define USER_MOTOR_PI_ID_KP                             (USER_MOTOR_KPD_MULTI * USER_MOTOR_FOC_CALC_KP)

/** @brief Define the adjusted D-axis current regulator Ki parameter value. */
#define USER_MOTOR_PI_ID_KI                             (USER_MOTOR_KID_MULTI * USER_MOTOR_FOC_CALC_KI)

/** @brief Define the adjusted Q-axis current regulator Kp parameter value. */
#define USER_MOTOR_PI_IQ_KP                             (USER_MOTOR_KPQ_MULTI * USER_MOTOR_FOC_CALC_KP)

/** @brief Define the adjusted Q-axis current regulator Ki parameter value. */
#define USER_MOTOR_PI_IQ_KI                             (USER_MOTOR_KIQ_MULTI * USER_MOTOR_FOC_CALC_KI)

/** @brief Define the maximum limit for the D-axis current regulator. */
#define USER_MOTOR_PI_ID_LIMIT_MAX                      (0.85f)

/** @brief Define the maximum limit for the Q-axis current regulator. */
#define USER_MOTOR_PI_IQ_LIMIT_MAX                      (0.85f)

/** @brief Define the control period for the D-axis current regulator. */
#define USER_MOTOR_PI_ID_CONTROL_PERIOD                 (50e-6)

/** @brief Define the control period for the Q-axis current regulator. */
#define USER_MOTOR_PI_IQ_CONTROL_PERIOD                 (50e-6)

/** @brief Define the max limit value of Q-axis current reference. */
#define USER_MOTOR_IQLIMIT                              (5.0f)

/** @brief Define the max limit value of D-axis current reference. */
#define USER_MOTOR_IDLIMIT                              (4.0f)
/** @} */

#endif /* MOTOR_TYPE == NANOTEC_MOTOR_DB42S02 */

/******************************************************************************/
/*------------------------------Global Variables------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Inline Function Prototypes-------------------------*/
/******************************************************************************/

#endif /* PMSM_FOC_MOTOR_NANOTEC_DB42S02_H_ */
