################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C_SRCS := 
ELF_SRCS := 
OBJ_SRCS := 
O_SRCS := 
S_SRCS := 
S_UPPER_SRCS := 
C_DEPS := 
EXECUTABLES := 
OBJS := 
SECONDARY_FLASH := 
SECONDARY_SIZE := 
S_DEPS := 
S_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
Configurations \
Dave/Generated \
Libraries/Infra/Ipc/Tricore/ipc/src \
Libraries/Infra/Platform/Compilers \
Libraries/Infra/Ssw/TC4xx/Tricore \
Libraries/Service/CpuGeneric/If \
Libraries/Service/CpuGeneric/StdIf \
Libraries/Service/CpuGeneric/SysSe/Bsp \
Libraries/Service/CpuGeneric/SysSe/General \
Libraries/Service/CpuGeneric/SysSe/Time \
Libraries/Service/Tricore/Comm \
Libraries/Service/Tricore/Math \
Libraries/iLLD/TC4xx/CpuGeneric/Adc/Cdsp \
Libraries/iLLD/TC4xx/CpuGeneric/Adc/Dsadc \
Libraries/iLLD/TC4xx/CpuGeneric/Adc/Fcc \
Libraries/iLLD/TC4xx/CpuGeneric/Adc/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Adc/Tmadc \
Libraries/iLLD/TC4xx/CpuGeneric/Ap/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Asclin/Asc \
Libraries/iLLD/TC4xx/CpuGeneric/Asclin/Lin \
Libraries/iLLD/TC4xx/CpuGeneric/Asclin/Spi \
Libraries/iLLD/TC4xx/CpuGeneric/Asclin/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Clock/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Dma/Dma \
Libraries/iLLD/TC4xx/CpuGeneric/Dma/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Egtm/Atom/Pwm \
Libraries/iLLD/TC4xx/CpuGeneric/Egtm/Atom/Timer \
Libraries/iLLD/TC4xx/CpuGeneric/Egtm/Input \
Libraries/iLLD/TC4xx/CpuGeneric/Egtm/Pwm \
Libraries/iLLD/TC4xx/CpuGeneric/Egtm/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Egtm/Tim/In \
Libraries/iLLD/TC4xx/CpuGeneric/Egtm/Tim/Timer \
Libraries/iLLD/TC4xx/CpuGeneric/Egtm/Tom/Pwm \
Libraries/iLLD/TC4xx/CpuGeneric/Egtm/Tom/Timer \
Libraries/iLLD/TC4xx/CpuGeneric/Egtm/Trigger \
Libraries/iLLD/TC4xx/CpuGeneric/Fce/Crc \
Libraries/iLLD/TC4xx/CpuGeneric/Fce/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Geth/Eth \
Libraries/iLLD/TC4xx/CpuGeneric/Geth/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Gpt12/IncrEnc \
Libraries/iLLD/TC4xx/CpuGeneric/Gpt12/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Gst/Gst \
Libraries/iLLD/TC4xx/CpuGeneric/Gst/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Gtm/Atom/Pwm \
Libraries/iLLD/TC4xx/CpuGeneric/Gtm/Atom/Timer \
Libraries/iLLD/TC4xx/CpuGeneric/Gtm/Input \
Libraries/iLLD/TC4xx/CpuGeneric/Gtm/Pwm \
Libraries/iLLD/TC4xx/CpuGeneric/Gtm/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Gtm/Tim/In \
Libraries/iLLD/TC4xx/CpuGeneric/Gtm/Tim/Timer \
Libraries/iLLD/TC4xx/CpuGeneric/Gtm/Tom/Pwm \
Libraries/iLLD/TC4xx/CpuGeneric/Gtm/Tom/Timer \
Libraries/iLLD/TC4xx/CpuGeneric/Gtm/Trigger \
Libraries/iLLD/TC4xx/CpuGeneric/Hsphy/Dll \
Libraries/iLLD/TC4xx/CpuGeneric/Hsphy/EthIO \
Libraries/iLLD/TC4xx/CpuGeneric/Hsphy/Hsphy \
Libraries/iLLD/TC4xx/CpuGeneric/Hsphy/Mp8g \
Libraries/iLLD/TC4xx/CpuGeneric/Hsphy/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Hsphy/Xpcs \
Libraries/iLLD/TC4xx/CpuGeneric/Leth/Eth \
Libraries/iLLD/TC4xx/CpuGeneric/Leth/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Pcie/Ep \
Libraries/iLLD/TC4xx/CpuGeneric/Pcie/Lib/Cap \
Libraries/iLLD/TC4xx/CpuGeneric/Pcie/Lib/Device \
Libraries/iLLD/TC4xx/CpuGeneric/Pcie/Lib/Dma \
Libraries/iLLD/TC4xx/CpuGeneric/Pcie/Rc \
Libraries/iLLD/TC4xx/CpuGeneric/Pcie/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Port/Io \
Libraries/iLLD/TC4xx/CpuGeneric/Port/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Rdma/Rdma \
Libraries/iLLD/TC4xx/CpuGeneric/Rdma/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Rif/Dphy \
Libraries/iLLD/TC4xx/CpuGeneric/Rif/Rif \
Libraries/iLLD/TC4xx/CpuGeneric/Rif/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Spu/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Src/Std \
Libraries/iLLD/TC4xx/CpuGeneric/Xspi/Spi \
Libraries/iLLD/TC4xx/CpuGeneric/Xspi/Std \
Libraries/iLLD/TC4xx/CpuGeneric/_Impl \
Libraries/iLLD/TC4xx/CpuGeneric/_Impl/TC4Dx \
Libraries/iLLD/TC4xx/CpuGeneric/_Lib/DataHandling \
Libraries/iLLD/TC4xx/CpuGeneric/_Lib/InternalMux \
Libraries/iLLD/TC4xx/CpuGeneric/_Lib/Timer \
Libraries/iLLD/TC4xx/CpuGeneric/_PinMap \
Libraries/iLLD/TC4xx/CpuGeneric/_PinMap/TC4Dx \
Libraries/iLLD/TC4xx/Tricore/Audio/Audio \
Libraries/iLLD/TC4xx/Tricore/Audio/Ldma \
Libraries/iLLD/TC4xx/Tricore/Audio/Mixer \
Libraries/iLLD/TC4xx/Tricore/Audio/Std \
Libraries/iLLD/TC4xx/Tricore/Audio/Tdm \
Libraries/iLLD/TC4xx/Tricore/Can/Can \
Libraries/iLLD/TC4xx/Tricore/Can/Std \
Libraries/iLLD/TC4xx/Tricore/Canxl/Can \
Libraries/iLLD/TC4xx/Tricore/Canxl/Std \
Libraries/iLLD/TC4xx/Tricore/Cpu/Irq \
Libraries/iLLD/TC4xx/Tricore/Cpu/Std \
Libraries/iLLD/TC4xx/Tricore/Cpu/Trap \
Libraries/iLLD/TC4xx/Tricore/Dre/Dre \
Libraries/iLLD/TC4xx/Tricore/Dre/Std \
Libraries/iLLD/TC4xx/Tricore/Eray/Eray \
Libraries/iLLD/TC4xx/Tricore/Eray/Std \
Libraries/iLLD/TC4xx/Tricore/Flash/Std \
Libraries/iLLD/TC4xx/Tricore/Hssl/Hssl \
Libraries/iLLD/TC4xx/Tricore/Hssl/Std \
Libraries/iLLD/TC4xx/Tricore/I2c/I2c \
Libraries/iLLD/TC4xx/Tricore/I2c/Std \
Libraries/iLLD/TC4xx/Tricore/Msc/Msc \
Libraries/iLLD/TC4xx/Tricore/Msc/Std \
Libraries/iLLD/TC4xx/Tricore/Nvmr/Std \
Libraries/iLLD/TC4xx/Tricore/Pms/Std \
Libraries/iLLD/TC4xx/Tricore/Ppuc/Std \
Libraries/iLLD/TC4xx/Tricore/Psi5/Psi5 \
Libraries/iLLD/TC4xx/Tricore/Psi5/Std \
Libraries/iLLD/TC4xx/Tricore/Psi5s/Psi5s \
Libraries/iLLD/TC4xx/Tricore/Psi5s/Std \
Libraries/iLLD/TC4xx/Tricore/Qspi/SpiMaster \
Libraries/iLLD/TC4xx/Tricore/Qspi/SpiSlave \
Libraries/iLLD/TC4xx/Tricore/Qspi/Std \
Libraries/iLLD/TC4xx/Tricore/Rmem/Std \
Libraries/iLLD/TC4xx/Tricore/Scu/Std \
Libraries/iLLD/TC4xx/Tricore/Sdmmc/Emmc \
Libraries/iLLD/TC4xx/Tricore/Sdmmc/Sd \
Libraries/iLLD/TC4xx/Tricore/Sdmmc/Std \
Libraries/iLLD/TC4xx/Tricore/Sent/Sent \
Libraries/iLLD/TC4xx/Tricore/Sent/Std \
Libraries/iLLD/TC4xx/Tricore/Smm/Std \
Libraries/iLLD/TC4xx/Tricore/Smu/Smu \
Libraries/iLLD/TC4xx/Tricore/Smu/Std \
Libraries/iLLD/TC4xx/Tricore/Stm/Std \
Libraries/iLLD/TC4xx/Tricore/Stm/Timer \
Libraries/iLLD/TC4xx/Tricore/Tri/Std \
Libraries/iLLD/TC4xx/Tricore/Vmt/Std \
Libraries/iLLD/TC4xx/Tricore/Wtu/Std \
Libraries/iLLD/TC4xx/Tricore/_Impl \
Libraries/iLLD/TC4xx/Tricore/_Impl/TC4Dx \
Libraries/iLLD/TC4xx/Tricore/_PinMap/TC4Dx \
complex_device_driver \

