/* Additional record code for PMSM_Plant_FMU generated by the OpenModelica Compiler OpenModelica v1.26.3 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "PMSM_Plant_FMU_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

