/* embedsim_loop.h
 * Auto-generated by EmbedSim LoopGenerator (feature 05121967)
 * DO NOT EDIT — re-generate with cg_end.generate_loop()
 */

#ifndef EMBEDSIM_LOOP_H
#define EMBEDSIM_LOOP_H

#include "Sys_Types.h"   /* real32_T */

/* Sample period for a 1000000 Hz control loop */
#define EMBEDSIM_DT  (0.0000010000f)

/* Block headers */
#include "pi_buck_controller.h"
#include "Sys_Types.h"

/* Persistent state (file-scope statics — one per stateful block) */
static PI_Buck_Block_T pi_buck_state;

/* ── Public API ─────────────────────────────────────────────── */

/**
 * embedsim_loop_init
 * Call once at startup to zero all block states.
 */
void embedsim_loop_init(void);

/**
 * embedsim_loop_step
 * Call every sample period.  dt = sample period [seconds].
 */
void embedsim_loop_step(real32_T dt);

#endif /* EMBEDSIM_LOOP_H */
