/* embedsim_loop.h
 * Auto-generated by EmbedSim LoopGenerator (feature 05121967)
 * DO NOT EDIT - re-generate with cg_end.generate_loop()
 */

#ifndef EMBEDSIM_LOOP_H
#define EMBEDSIM_LOOP_H

#include "Sys_Types.h"   /* real32_T */

/* Sample period for a 100000 Hz control loop */
#define EMBEDSIM_DT  (0.0000100000f)

/* Block headers */
#include "Coordinate_Transform.h"

/* Persistent state -- defined in embedsim_loop.c, declared extern here */
extern Clarke_T Clarke_state;
extern Park_T Park_state;

/* -- Public API ------------------------------------------------- */

/**
 * embedsim_loop_init
 * Call once at startup to zero all block states.
 */
void embedsim_loop_init(void);

/**
 * embedsim_loop_step
 * Call every sample period.  dt = sample period [seconds].
 */
void embedsim_loop_step(real32_T dt);

#endif /* EMBEDSIM_LOOP_H */
