/* embedsim_loop.c
 * Auto-generated by EmbedSim LoopGenerator (feature 05121967)
 * DO NOT EDIT - re-generate with cg_end.generate_loop()
 */

#include <string.h>   /* memcpy, memset */
#include "embedsim_loop.h"
#include "Coordinate_Transform.h"

/* -- State struct definitions (one per stateful block) -- */
static Clarke_T Clarke_state;
static Park_T Park_state;


/* ================================================================
 * embedsim_loop_init
 *
 * Initialise all block states via their typed Init functions.
 * Call once at startup before the first call to
 * embedsim_loop_step().
 *
 * MISRA C:2012 Rule 21.8 compliance:
 *   memset() is NOT used because zeroing a struct that contains
 *   floating-point members via memset() is not guaranteed by the
 *   C standard to produce 0.0f (Rule 21.8 / CERT EXP05-C).
 *   Each block provides a typed Init function for safe init.
 * ================================================================
 */
void embedsim_loop_init(void)
{
    Clarke_Init(&Clarke_state);
    Park_Init(&Park_state);
}


/* ================================================================
 * embedsim_loop_step
 *
 * Execute one control loop step.  Call at fixed sample rate.
 *
 * Parameters:
 *   dt : sample period in seconds (e.g. 1.0f/10000.0f for 10 kHz)
 * ================================================================
 */
void embedsim_loop_step(real32_T dt)
{
    /* --- Clarke (ClarkeTransformBlock) --- */
    {
        MatrixFloat clarke_alpha, clarke_beta;
        Clarke_Step(&Clarke_state,
                    u_cg_start[0], u_cg_start[1], u_cg_start[2],
                    &clarke_alpha, &clarke_beta);
        real32_T y_Clarke[2];
        y_Clarke[0] = clarke_alpha;
        y_Clarke[1] = clarke_beta;
    }

    /* [Theta] Python-only block — no C step function. Replace with hand-written C or add C_SOURCES + step_func. */

    /* --- Park (ParkTransformBlock) --- */
    {
        MatrixFloat park_d, park_q;
        Park_Step(&Park_state,
                  y_Clarke[0], y_Clarke[1],
                  THETA_E,
                  &park_d, &park_q);
        real32_T y_Park[2];
        y_Park[0] = park_d;
        y_Park[1] = park_q;
    }

}
