/**
 * \file embedsim_step.c
 * \brief EmbedSim — auto-generated step-function implementation
 *
 * Auto-generated by EmbedSim StepGenerator.
 * DO NOT EDIT — re-generate with cg_end.generate_step().
 *
 * MISRA C:2012 compliant — no dynamic memory, no static locals.
 */

#include <string.h>   /* memcpy, memset */
#include <math.h>     /* fabsf, atan2f, sqrtf */
#include "embedsim_step.h"
#include "embed_sim_sv_pwm.h"


/* ================================================================
 * EmbedSim_Init
 * Initialise all block states via typed Init functions.
 * MISRA C:2012 Rule 21.8: no memset on float-bearing structs.
 * ================================================================
 */
void EmbedSim_Init(void)
{
    /* No stateful blocks in this region */
}


/* ================================================================
 * EmbedSim_Step
 * Execute one control-loop step.
 * \param dt   Sample period [s].
 * \param in   Pointer to EmbedSim_Input_T.
 * \param out  Pointer to EmbedSim_Output_T.
 * ================================================================
 */
void EmbedSim_Step(
    real32_T                    dt,
    const EmbedSim_Input_T  * in,
          EmbedSim_Output_T * out
)
{
    /* ── Unpack inputs ────────────────────────────────── */

    /* ── Local variable declarations (MISRA C:2012 Rule 8.1) ── */

    /* ── Block chain ──────────────────────────────────────── */
      /* --- svpwm (svpwm) — SVM_CalculateDutyCycle --- */
      {
          SVM_DutyCycle_Type svm_duty;
          MatrixStatus_Type  svm_status;

          /* Default values (duty cycles = 0.5 for safe state) */
          out->ta = 0.5f;
          out->tb = 0.5f;
          out->tc = 0.5f;
          out->sector = 0U;

          svm_status = SVM_CalculateDutyCycle(
                           in->magnitude,   /* modulation index */
                           in->angle_rad,       /* angle [rad] */
                           &svm_duty);
          if (svm_status == MATRIX_SUCCESS)
          {
              out->ta = (real32_T)svm_duty.ta / (real32_T)Q31_ONE;
              out->tb = (real32_T)svm_duty.tb / (real32_T)Q31_ONE;
              out->tc = (real32_T)svm_duty.tc / (real32_T)Q31_ONE;
              out->sector = (uint8_T)svm_duty.sector;
          }
      }

}
