/* embedsim_loop.c
 * Auto-generated by EmbedSim LoopGenerator (feature 05121967)
 * DO NOT EDIT - re-generate with cg_end.generate_loop()
 */

#include <string.h>   /* memcpy, memset */
#include "embedsim_loop.h"
#include "motor_utility_blocks.h"
#include "Coordinate_Transform.h"
#include "svpwm.h"

/* -- State struct definitions (one per stateful block) -- */
static SpeedRamp_T speed_ref_state;
static VfAngle_T vf_angle_state;
static VfDQ_T vf_dq_state;
static VfTheta_T vf_theta_state;
static InvPark_T inv_park_state;
static SVPWMPack_T svpwm_pack_state;
static DutyPack_T duty_pack_state;


/* ================================================================
 * embedsim_loop_init
 *
 * Initialise all block states via their typed Init functions.
 * Call once at startup before the first call to
 * embedsim_loop_step().
 *
 * MISRA C:2012 Rule 21.8 compliance:
 *   memset() is NOT used because zeroing a struct that contains
 *   floating-point members via memset() is not guaranteed by the
 *   C standard to produce 0.0f (Rule 21.8 / CERT EXP05-C).
 *   Each block provides a typed Init function for safe init.
 * ================================================================
 */
void embedsim_loop_init(void)
{
    SpeedRamp_Init(&speed_ref_state);
    VfAngle_Init(&vf_angle_state);
    VfDQ_Init(&vf_dq_state);
    VfTheta_Init(&vf_theta_state);
    InvPark_Init(&inv_park_state);
    SVPWMPack_Init(&svpwm_pack_state);
    DutyPack_Init(&duty_pack_state);
}


/* ================================================================
 * embedsim_loop_step
 *
 * Execute one control loop step.  Call at fixed sample rate.
 *
 * Parameters:
 *   dt : sample period in seconds (e.g. 1.0f/10000.0f for 10 kHz)
 * ================================================================
 */
void embedsim_loop_step(real32_T dt)
{
    /* --- speed_ref (SpeedRampBlock) — source, no u[] --- */
    /* y_speed_ref[1] pre-seeded from in->speed_ref above */
    SpeedRamp_Step(&speed_ref_state, dt, y_speed_ref);
    /* Override ramp output with external command if non-zero */
    if (in->speed_ref > 0.0f) { y_speed_ref[0] = in->speed_ref; }

    /* --- vf_angle (VfAngleBlock) --- */
    real32_T u_vf_angle[1];
    u_vf_angle[0] = y_speed_ref[0];
    real32_T y_vf_angle[3];
    VfAngle_Step(&vf_angle_state, u_vf_angle, dt, y_vf_angle);


    /* --- vf_dq (VfDQBlock) --- */
    real32_T u_vf_dq[3];
    u_vf_dq[0] = y_vf_angle[0];
    u_vf_dq[1] = y_vf_angle[1];
    u_vf_dq[2] = y_vf_angle[2];
    real32_T y_vf_dq[2];
    VfDQ_Step(&vf_dq_state, u_vf_dq, dt, y_vf_dq);


    /* --- vf_theta (VfThetaBlock) --- */
    real32_T u_vf_theta[3];
    u_vf_theta[0] = y_vf_angle[0];
    u_vf_theta[1] = y_vf_angle[1];
    u_vf_theta[2] = y_vf_angle[2];
    real32_T y_vf_theta[1];
    VfTheta_Step(&vf_theta_state, u_vf_theta, dt, y_vf_theta);


    /* --- inv_park (InvParkTransformBlock) --- */
    real32_T y_inv_park[2];
    {
        MatrixFloat invpark_alpha, invpark_beta;
        InvPark_Step(&inv_park_state,
                     y_vf_dq[0],      /* v_d     */
                     y_vf_dq[1],      /* v_q     */
                     y_vf_theta[0],   /* theta_e */
                     &invpark_alpha,
                     &invpark_beta);
        y_inv_park[0] = (real32_T)invpark_alpha;
        y_inv_park[1] = (real32_T)invpark_beta;
    }

    /* --- svpwm_pack (SVPWMPackBlock) — inline polar conversion --- */
    real32_T y_svpwm_pack[3];
    y_svpwm_pack[0] = sqrtf(  y_inv_park[0] * y_inv_park[0]
                            + y_inv_park[1] * y_inv_park[1]);
    y_svpwm_pack[1] = atan2f( y_inv_park[1], y_inv_park[0]);
    y_svpwm_pack[2] = 17.0000f;   /* V_dc */

    /* --- svpwm (SVPWMBlock) — struct-based I/O --- */
    real32_T y_svpwm[4];
    {
        SVPWM_Input  svpwm_in;
        SVPWM_Output svpwm_out;
        svpwm_in.Vref  = y_svpwm_pack[0];   /* Vref  */
        svpwm_in.alpha = y_svpwm_pack[1];   /* alpha */
        svpwm_in.Vdc   = y_svpwm_pack[2];   /* V_dc  */
        svpwm_in.Ts    = dt;
        SVPWM_Step(&svpwm_in, &svpwm_out);
        y_svpwm[0] = svpwm_out.T1;
        y_svpwm[1] = svpwm_out.T2;
        y_svpwm[2] = svpwm_out.T0;
        y_svpwm[3] = (real32_T)svpwm_out.sector;
    }

    /* --- duty_pack (DutyPackBlock) --- */
    real32_T u_duty_pack[2];
    u_duty_pack[0] = y_inv_park[0];
    u_duty_pack[1] = y_inv_park[1];
    real32_T y_duty_pack[5];
    DutyPack_Step(&duty_pack_state, u_duty_pack, dt, y_duty_pack);


}
