/**
 * \file embedsimdfc_step.h
 * \brief EmbedSimDfc — auto-generated step-function API
 *
 * Auto-generated by EmbedSim StepGenerator.
 * DO NOT EDIT — re-generate with cg_end.generate_step().
 *
 * Simulink-equivalent pattern:
 *   Simulink  : Model_step(RT_MODEL *M)
 *   EmbedSim  : EmbedSimDfc_Step(dt, in*, out*)
 *
 * EmbedSimDfc_Input_T  — signals entering region at CodeGenStart
 * EmbedSimDfc_Output_T — signals leaving  region at CodeGenEnd
 *
 * Integration pattern:
 *   AppInit():
 *       EmbedSimDfc_Init();
 *   controlLoop_ISR():
 *       EmbedSimDfc_Input_T  in;
 *       EmbedSimDfc_Output_T out;
 *       in.<field> = <sensor value>;
 *       EmbedSimDfc_Step(EMBEDSIM_DT, &in, &out);
 *       <write out.<field> to actuator registers>;
 *
 * MISRA C:2012 compliant — no dynamic memory, no static locals.
 */

#ifndef EMBEDSIMDFC_STEP_H_
#define EMBEDSIMDFC_STEP_H_

#include "embed_sim_sys_types.h"   /* real32_T */

/* Sample period for a 20000 Hz control loop */
#define EMBEDSIM_DT  (0.0000500000f)

/**
 * EmbedSimDfc_Input_T
 * Signals entering the CodeGen region (CodeGenStart boundary).
 */
typedef struct
{
    real32_T speed_ref_rpm;                             /**< IN : Mechanical speed reference [RPM]; range [0, 3000] */
    real32_T ia;                                        /**< IN : Phase-A current from ADC [A]; range [-DFC_I_MAX, +DFC_I_MAX] */
    real32_T ib;                                        /**< IN : Phase-B current from ADC [A]; range [-DFC_I_MAX, +DFC_I_MAX] */
    real32_T ic;                                        /**< IN : Phase-C current from ADC [A]; range [-DFC_I_MAX, +DFC_I_MAX] */
} EmbedSimDfc_Input_T;

/**
 * EmbedSimDfc_Output_T
 * Signals leaving the CodeGen region (CodeGenEnd boundary).
 */
typedef struct
{
    real32_T ta;                                        /**< OUT: Phase-A duty cycle [0.0..1.0] -> GTM ATOM compare */
    real32_T tb;                                        /**< OUT: Phase-B duty cycle [0.0..1.0] -> GTM ATOM compare */
    real32_T tc;                                        /**< OUT: Phase-C duty cycle [0.0..1.0] -> GTM ATOM compare */
    real32_T omega_mech;                                /**< OUT: SMO mechanical speed estimate [rad/s] */
    real32_T theta_mech;                                /**< OUT: Integrated mechanical rotor position [rad, 0..2pi) */
    real32_T ia_echo;                                   /**< OUT: Phase-A current echo [A] (passthrough of input U) */
    real32_T ib_echo;                                   /**< OUT: Phase-B current echo [A] (passthrough of input V) */
    real32_T ic_echo;                                   /**< OUT: Phase-C current echo [A] (star-point W = -U-V) */
    real32_T mode;                                      /**< OUT: Controller mode (0 ALIGN / 1 OPENLOOP / 2 CLOSEDLOOP) */
} EmbedSimDfc_Output_T;

/* Block headers */
#include "embed_sim_dfc_controller.h"

extern void EmbedSimDfc_Init(void);

extern void EmbedSimDfc_Step(
    real32_T                    dt,
    const EmbedSimDfc_Input_T  * in,
          EmbedSimDfc_Output_T * out
);

#endif /* EMBEDSIMDFC_STEP_H_ */
