/**
 * \file embedsimdfc_step.c
 * \brief EmbedSimDfc — auto-generated step-function implementation
 *
 * Auto-generated by EmbedSim StepGenerator.
 * DO NOT EDIT — re-generate with cg_end.generate_step().
 *
 * MISRA C:2012 compliant — no dynamic memory, no static locals.
 */

#include <string.h>   /* memcpy, memset */
#include <math.h>     /* fabsf, atan2f, sqrtf */
#include "embedsimdfc_step.h"
#include "embed_sim_dfc_controller.h"

/* ── Block state structs ──────────────────────────────────────
 * Internal linkage — not exposed in the .h.
 * MISRA C:2012 Rule 8.7: static, TU-local only.
 * ──────────────────────────────────────────────────────────── */
static DFC_State_T dfc_state;   /* Rule 8.7: internal linkage */


/* ================================================================
 * EmbedSimDfc_Init
 * Initialise all block states via typed Init functions.
 * MISRA C:2012 Rule 21.8: no memset on float-bearing structs.
 * ================================================================
 */
void EmbedSimDfc_Init(void)
{
    DFC_Init(&dfc_state);
}


/* ================================================================
 * EmbedSimDfc_Step
 * Execute one control-loop step.
 * \param dt   Sample period [s].
 * \param in   Pointer to EmbedSimDfc_Input_T.
 * \param out  Pointer to EmbedSimDfc_Output_T.
 * ================================================================
 */
void EmbedSimDfc_Step(
    real32_T                    dt,
    const EmbedSimDfc_Input_T  * in,
          EmbedSimDfc_Output_T * out
)
{
    /* ── Unpack inputs ────────────────────────────────── */

    /* ── Local variable declarations (MISRA C:2012 Rule 8.1) ── */

    /* ── Block chain ──────────────────────────────────────── */
        /* --- dfc (DFControllerBlock, v4 sensorless) --- */
        /* DFC_Step() runs Clarke -> SMO -> mode SM -> flatness law -> SVPWM  */
        /* and outputs Ta/Tb/Tc duties plus speed/position/current estimates. */
        /* Region input : named fields speed_ref_rpm, ia, ib, ic.             */
        /* Prerequisite (once, at startup): Transform_Init(); SVM_Init();     */
        DFC_Input_T   u_dfc;
        DFC_Output_T  y_dfc_out;
        real32_T      y_dfc[9];

        u_dfc.SpeedRefRpm     = in->speed_ref_rpm;
        u_dfc.PhaseCurrents.U = in->ia;
        u_dfc.PhaseCurrents.V = in->ib;
        u_dfc.PhaseCurrents.W = in->ic;

        (void)DFC_Step(&dfc_state, &u_dfc, dt, &y_dfc_out);

        y_dfc[0] = y_dfc_out.Ta;                    /* duty A               */
        y_dfc[1] = y_dfc_out.Tb;                    /* duty B               */
        y_dfc[2] = y_dfc_out.Tc;                    /* duty C               */
        y_dfc[3] = y_dfc_out.AngularVelocity;       /* speed est [rad/s]    */
        y_dfc[4] = y_dfc_out.RotorPosition;         /* position  [rad]      */
        y_dfc[5] = y_dfc_out.PhaseCurrents.U;       /* ia echo   [A]        */
        y_dfc[6] = y_dfc_out.PhaseCurrents.V;       /* ib echo   [A]        */
        y_dfc[7] = y_dfc_out.PhaseCurrents.W;       /* ic echo   [A] (=-U-V)*/
        y_dfc[8] = (real32_T)y_dfc_out.Mode;        /* mode 0/1/2           */

    /* ── Pack outputs ─────────────────────────────────── */
    out->ta = y_dfc[0];
    out->tb = y_dfc[1];
    out->tc = y_dfc[2];
    out->omega_mech = y_dfc[3];
    out->theta_mech = y_dfc[4];
    out->ia_echo = y_dfc[5];
    out->ib_echo = y_dfc[6];
    out->ic_echo = y_dfc[7];
    out->mode = y_dfc[8];

}
