/**
 * \file EmbedSim_step.h
 * \brief EmbedSim — auto-generated step-function API
 *
 * Auto-generated by EmbedSim StepGenerator.
 * DO NOT EDIT — re-generate with cg_end.generate_step().
 *
 * Simulink-equivalent pattern:
 *   Simulink  : Model_step(RT_MODEL *M)
 *   EmbedSim  : EmbedSim_Step(dt, in*, out*)
 *
 * EmbedSim_Input_T  — signals entering region at CodeGenStart
 * EmbedSim_Output_T — signals leaving  region at CodeGenEnd
 *
 * Integration pattern:
 *   AppInit():
 *       EmbedSim_Init();
 *   controlLoop_ISR():
 *       EmbedSim_Input_T  in;
 *       EmbedSim_Output_T out;
 *       in.<field> = <sensor value>;
 *       EmbedSim_Step(EMBEDSIM_DT, &in, &out);
 *       <write out.<field> to actuator registers>;
 *
 * MISRA C:2012 compliant — no dynamic memory, no static locals.
 */

#ifndef EMBEDSIM_STEP_H_
#define EMBEDSIM_STEP_H_

#include "Sys_Types.h"   /* real32_T */

/* Sample period for a 10000 Hz control loop */
#define EMBEDSIM_DT  (0.0001000000f)

/**
 * EmbedSim_Input_T
 * Signals entering the CodeGen region (CodeGenStart boundary).
 */
typedef struct
{
    real32_T speed_ref;
} EmbedSim_Input_T;

/**
 * EmbedSim_Output_T
 * Signals leaving the CodeGen region (CodeGenEnd boundary).
 */
typedef struct
{
    real32_T duty_a;
    real32_T duty_b;
    real32_T duty_c;
} EmbedSim_Output_T;

/* Block headers */
#include "motor_utility_blocks.h"
#include "Coordinate_Transform.h"

extern void EmbedSim_Init(void);

extern void EmbedSim_Step(
    real32_T                    dt,
    const EmbedSim_Input_T  * in,
          EmbedSim_Output_T * out
);

#endif /* EMBEDSIM_STEP_H_ */
