#!/usr/bin/env bash
# =============================================================================
# cleanup.sh  —  Remove all generated / compiled artefacts from c_src
# =============================================================================
# Keeps only the files you need to hand in or version-control:
#
#   KEEP (source files you author):
#     *.h   *.c               C headers and implementations
#     *.pyx                   Cython wrapper sources
#     setup_*.py              Per-module build scripts
#     build_all.bat / .sh     Top-level build drivers
#     cleanup.bat / .sh       This script
#     BUILD.md                Build instructions
#
#   DELETE (generated / compiled, always re-creatable):
#     build/                  setuptools build tree
#     *.so                    Compiled Linux/macOS extension modules
#     *.pyd                   Compiled Windows extension modules (if present)
#     *_wrapper.c             C files generated by Cython from *_wrapper.pyx
#     *.html                  Cython annotation files
#     __pycache__/            Python bytecode cache
#     *.pyc                   Compiled Python bytecodes
#
# Usage:
#   cd pmsm_blocks/c_src
#   chmod +x cleanup.sh && ./cleanup.sh
# =============================================================================

set -e
cd "$(dirname "$0")"

echo "============================================================"
echo " Cleaning c_src build artefacts"
echo "============================================================"

# setuptools build tree
if [ -d build ]; then
    echo "Removing build/..."
    rm -rf build
fi

# Compiled extension modules
echo "Removing *.so and *.pyd..."
find . -maxdepth 1 -name "*.so"  -delete
find . -maxdepth 1 -name "*.pyd" -delete

# Cython-generated C files (wrapper stems only, NOT our hand-written .c files)
echo "Removing Cython-generated *_wrapper.c files..."
rm -f pmsm_motor_wrapper.c transforms_wrapper.c pi_controller_wrapper.c

# Cython annotation HTML
echo "Removing *.html annotation files..."
find . -maxdepth 1 -name "*.html" -delete

# Python bytecode cache
echo "Removing __pycache__ and *.pyc..."
find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
find . -name "*.pyc" -delete 2>/dev/null || true

echo ""
echo "============================================================"
echo " Done.  Remaining files (source only):"
echo "============================================================"
ls -1
