/**********************************************************************************************************************
 * \file      embed_sim_motor_parameter.h
 * \brief     Motor parameters and operational limits for PMSM control.
 *
 * \details   Defines all motor-specific physical parameters for the Nanotec DB42S02 motor.
 *            Includes pole pairs, resistance, inductance, flux linkage, inertia,
 *            and friction coefficients.
 *            Targets 32-bit MCUs (Infineon AURIX TriCore, ARM Cortex-M4).
 *
 * \note      MISRA C:2012 compliance:
 *              - Rule  8.5 : One declaration per identifier
 *              - Rule  8.6 : No definitions in header files
 *              - Rule 17.2 : No recursion
 *
 * \note      EmbedSim naming convention:
 *              - Functions      : Pascal_Snake_Case
 *              - Parameters     : PascalCase  (single-letter → Uppercase)
 *              - Output pointers: PascalCase_P
 *              - Local variables: Lower camelCase
 *              - Struct members : PascalCase
 *              - Macros         : UPPER_SNAKE_CASE
 *              - Typedefs       : Pascal_Snake_Case_T
 *
 * \version   2.0.0
 * \date      2026-08-12
 * \author    EmbedSim / EV Light Vehicle Foundation
 *
 * \copyright Copyright (C) 2026 EmbedSim — EV Light Vehicle Foundation, Jaffna, Sri Lanka.
 *            Licensed under the MIT License.
 *
 * \note      Original motor data based on Nanotec DB42S02.
 *********************************************************************************************************************/

#ifndef EMBEDSIM_EMBED_SIM_MOTOR_PARAMETER_H_
#define EMBEDSIM_EMBED_SIM_MOTOR_PARAMETER_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "embed_sim_sys_types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/* ====================================================================
 * MOTOR PHYSICAL PARAMETERS (Nanotec DB42S02)
 * These are motor-specific and should NOT be changed
 * ==================================================================== */

/**
 * \brief   Motor pole pairs
 *
 * \details Number of pole pairs of the permanent magnet motor.
 *          For Nanotec DB42S02, this is 4 pole pairs.
 *
 * \note    Value: 4.0
 * \unit    pole pairs [-]
 */
#define MP_POLES                ((MatrixFloat)4.0f)

/**
 * \brief   Stator resistance per phase
 *
 * \details Phase resistance of the motor stator windings.
 *          Used for voltage drop and thermal calculations.
 *
 * \note    Value: 0.19 Ohm
 * \unit    Ohms [Ω]
 */
#define MP_R_S                  ((MatrixFloat)0.19f)

/**
 * \brief   Direct-axis inductance
 *
 * \details Inductance in the direct (d) axis of the rotor reference frame.
 *          For surface PMSM (SPMSM), Ld = Lq.
 *
 * \note    Value: 0.000125 H
 * \unit    Henries [H]
 */
#define MP_L_D                  ((MatrixFloat)0.000125f)

/**
 * \brief   Quadrature-axis inductance
 *
 * \details Inductance in the quadrature (q) axis of the rotor reference frame.
 *          For surface PMSM (SPMSM), Ld = Lq.
 *
 * \note    Value: 0.000125 H
 * \unit    Henries [H]
 */
#define MP_L_Q                  ((MatrixFloat)0.000125f)

/**
 * \brief   Permanent magnet flux linkage
 *
 * \details Flux linkage generated by the permanent magnets.
 *          Used for back-EMF and torque calculations.
 *
 * \note    Value: 0.0014 Wb
 * \unit    Webers [Wb]
 */
#define MP_LAMBDA_PM            ((MatrixFloat)0.0014f)

/**
 * \brief   Rotor inertia
 *
 * \details Moment of inertia of the rotor assembly.
 *          Used in mechanical dynamics equations.
 *
 * \note    Value: 2.4e-6 kg·m²
 * \unit    Kilogram-meter squared [kg·m²]
 */
#define MP_J_ROTOR              ((MatrixFloat)2.4e-6f)

/**
 * \brief   Viscous friction coefficient
 *
 * \details Damping coefficient for mechanical friction losses.
 *          Used in mechanical dynamics equations.
 *
 * \note    Value: 1.0e-6 N·m·s/rad
 * \unit    Newton-meter-second per radian [N·m·s/rad]
 */
#define MP_B_FRIC               ((MatrixFloat)1.0e-6f)

/**
 * \brief   DC bus voltage
 *
 * \details Nominal DC link voltage supplied to the inverter.
 *          Used for voltage limit calculations.
 *
 * \note    Value: 12.0 V
 * \unit    Volts [V]
 */
#define MP_V_DC                 ((MatrixFloat)12.0f)

/*
 * ====================================================================
 * NOTE: Operational limit macros are defined in embed_sim_control.h
 * ====================================================================
 * The following macros are defined in embed_sim_control.h:
 *   - MAX_SPEED_RPM
 *   - CLOSED_LOOP_MIN_SPEED
 *   - MAX_JERK_RPM
 *   - SPEED_SETTLE_TOL
 *   - JERK_SMOOTHING_FACTOR
 *   - DFC_MAX_CURRENT
 *   - DFC_MAX_VOLTAGE
 *   - DFC_VOLTAGE_MARGIN
 * ====================================================================
 */

/**
 * @def DFC_STARTUP_MOD_MIN
 * @brief Minimum Modulation Index for Start UP
 *
 */
#define DFC_STARTUP_MOD_MIN      (0.1F)

/**
 * @def DFC_STARTUP_MOD_MAX
 * @brief Maximum Modulation Index
 *
 */
#define DFC_STARTUP_MOD_MAX       (0.2F)






/**
 * \def ES_ANGLE_CORR_THRESHOLD_RAD
 * \brief   Threshold for switching between slow and fast angle convergence.
 *
 * \details When the angular error between the model angle and the sensor‑based
 *          angle is below this value, the model angle is corrected fully
 *          (gain = 1.0) and the half‑sample delay feedforward is applied.
 *          Above this threshold, a slow gain (ES_ANGLE_CORR_SLOW_GAIN) is used
 *          to avoid abrupt voltage steps.
 *
 * \note    This value must be larger than the worst‑case sensor noise and
 *          quantisation error to prevent unnecessary full corrections.
 *          Typical values: 0.01 rad (0.57°) to 0.03 rad (1.72°).
 *
 * \warning Increasing this threshold may cause larger angle jumps during
 *          the fast‑correction phase, potentially introducing torque ripple.
 *          Decreasing it may slow down convergence when the error is small.
 *
 * \unit    rad
 * \range   0.001 to 0.1 (recommended)
 */
#define ES_ANGLE_CORR_THRESHOLD_RAD   (0.0223F)   /* ~1.28° */

/**
 * \def ES_ANGLE_CORR_SLOW_GAIN
 * \brief   Proportional gain used when the angular error is large.
 *
 * \details When the error exceeds ES_ANGLE_CORR_THRESHOLD_RAD, the model angle
 *          is corrected using this gain. It provides a slow, smooth convergence
 *          to prevent sudden voltage changes that could cause current spikes
 *          or torque disturbances.
 *
 *          The effective gain is actually scheduled smoothly from this value
 *          to 1.0 as the error decreases below the threshold (see
 *          EmbedSim_ExecuteObserver for the exact formula).
 *
 * \note    A value of 0.1 results in a convergence time constant of ~10 samples.
 *          For a 10 kHz loop, this is ~1 ms, which is fast enough for most
 *          motor control applications.
 *
 * \unit    dimensionless
 * \range   0.01 to 0.3 (recommended)
 */
#define ES_ANGLE_CORR_SLOW_GAIN       (0.1F)

/**
 * \def ES_MEASUREMENT_DELAY_FACTOR
 * \brief   Factor to compensate for the delay between sensor sampling and
 *          control update.
 *
 * \details In many digital control systems, the sensor value is sampled at the
 *          start of the control cycle, but the PWM voltage is applied at the
 *          end of the cycle. This delay causes a phase lag in the rotor angle.
 *
 *          The feedforward term added to the model angle is:
 *          \f[ \Delta\theta = \omega_e \cdot \text{delay\_factor} \cdot T_s \f]
 *
 *          Typically, the delay is half the sample period, hence a factor of 0.5.
 *
 * \note    This factor should match the actual delay in your hardware.
 *          If the measurement is taken exactly at the midpoint, use 0.5.
 *          If it is taken at the beginning, use 1.0 for fully synchronous
 *          implementation (rare).
 *
 * \unit    dimensionless
 * \range   0.0 to 1.0 (typical)
 */
#define ES_MEASUREMENT_DELAY_FACTOR   (0.5F)

/**
 * \def ES_MAX_ANGLE_STEP_RAD
 * \brief   Safety clamp for the half‑sample delay feedforward term.
 *
 * \details The feedforward correction is limited to ±this value per sample to
 *          prevent the model angle from jumping excessively due to sensor noise
 *          or erroneous speed readings (e.g., a glitch reporting 1e6 RPM).
 *
 *          If the computed feedforward exceeds this limit, it is clamped,
 *          preventing a large angle step that could cause current transients
 *          or loss of field orientation.
 *
 *          A typical value of 0.5 rad (~28.6°) is sufficient for most traction
 *          motors running at 10–20 kHz sample rates and up to 8 pole pairs.
 *          For very high pole counts or slower sample rates, increase accordingly.
 *
 * \note    This clamp only limits the feedforward term, not the main
 *          proportional correction (which is clamped via the gain scheduling).
 *
 * \unit    rad
 * \range   0.1 to 1.0 (recommended)
 */
#define ES_MAX_ANGLE_STEP_RAD  (0.5F)   /* ~28.6 degrees */

#endif /* EMBEDSIM_EMBED_SIM_MOTOR_PARAMETER_H_ */
