/**********************************************************************************************************************
 * \file      embed_sim_motor_parameter.h
 * \brief     Motor parameters and operational limits for PMSM control.
 *
 * \details   Defines all motor-specific physical parameters for the Nanotec DB42S02 motor.
 *            Includes pole pairs, resistance, inductance, flux linkage, inertia,
 *            and friction coefficients.
 *            Targets 32-bit MCUs (Infineon AURIX TriCore, ARM Cortex-M4).
 *
 * \note      MISRA C:2012 compliance:
 *              - Rule  8.5 : One declaration per identifier
 *              - Rule  8.6 : No definitions in header files
 *              - Rule 17.2 : No recursion
 *
 * \note      EmbedSim naming convention:
 *              - Functions      : Pascal_Snake_Case
 *              - Parameters     : PascalCase  (single-letter → Uppercase)
 *              - Output pointers: PascalCase_P
 *              - Local variables: Lower camelCase
 *              - Struct members : PascalCase
 *              - Macros         : UPPER_SNAKE_CASE
 *              - Typedefs       : Pascal_Snake_Case_T
 *
 * \version   2.0.0
 * \date      2026-08-12
 * \author    EmbedSim / EV Light Vehicle Foundation
 *
 * \copyright Copyright (C) 2026 EmbedSim — EV Light Vehicle Foundation, Jaffna, Sri Lanka.
 *            Licensed under the MIT License.
 *
 * \note      Original motor data based on Nanotec DB42S02.
 *********************************************************************************************************************/

#ifndef EMBEDSIM_EMBED_SIM_MOTOR_PARAMETER_H_
#define EMBEDSIM_EMBED_SIM_MOTOR_PARAMETER_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "embed_sim_sys_types.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/* ====================================================================
 * MOTOR PHYSICAL PARAMETERS (Nanotec DB42S02)
 * These are motor-specific and should NOT be changed
 * ==================================================================== */

/**
 * \brief   Motor pole pairs
 *
 * \details Number of pole pairs of the permanent magnet motor.
 *          For Nanotec DB42S02, this is 4 pole pairs.
 *
 * \note    Value: 4.0
 * \unit    pole pairs [-]
 */
#define MP_POLES                ((MatrixFloat)4.0f)

/**
 * \brief   Stator resistance per phase
 *
 * \details Phase resistance of the motor stator windings.
 *          Used for voltage drop and thermal calculations.
 *
 * \note    Value: 0.19 Ohm
 * \unit    Ohms [Ω]
 */
#define MP_R_S                  ((MatrixFloat)0.19f)

/**
 * \brief   Direct-axis inductance
 *
 * \details Inductance in the direct (d) axis of the rotor reference frame.
 *          For surface PMSM (SPMSM), Ld = Lq.
 *
 * \note    Value: 0.000125 H
 * \unit    Henries [H]
 */
#define MP_L_D                  ((MatrixFloat)0.000125f)

/**
 * \brief   Quadrature-axis inductance
 *
 * \details Inductance in the quadrature (q) axis of the rotor reference frame.
 *          For surface PMSM (SPMSM), Ld = Lq.
 *
 * \note    Value: 0.000125 H
 * \unit    Henries [H]
 */
#define MP_L_Q                  ((MatrixFloat)0.000125f)

/**
 * \brief   Permanent magnet flux linkage
 *
 * \details Flux linkage generated by the permanent magnets.
 *          Used for back-EMF and torque calculations.
 *
 * \note    Value: 0.0014 Wb
 * \unit    Webers [Wb]
 */
#define MP_LAMBDA_PM            ((MatrixFloat)0.0014f)

/**
 * \brief   Rotor inertia
 *
 * \details Moment of inertia of the rotor assembly.
 *          Used in mechanical dynamics equations.
 *
 * \note    Value: 2.4e-6 kg·m²
 * \unit    Kilogram-meter squared [kg·m²]
 */
#define MP_J_ROTOR              ((MatrixFloat)2.4e-6f)

/**
 * \brief   Viscous friction coefficient
 *
 * \details Damping coefficient for mechanical friction losses.
 *          Used in mechanical dynamics equations.
 *
 * \note    Value: 1.0e-6 N·m·s/rad
 * \unit    Newton-meter-second per radian [N·m·s/rad]
 */
#define MP_B_FRIC               ((MatrixFloat)1.0e-6f)

/**
 * \brief   DC bus voltage
 *
 * \details Nominal DC link voltage supplied to the inverter.
 *          Used for voltage limit calculations.
 *
 * \note    Value: 12.0 V
 * \unit    Volts [V]
 */
#define MP_V_DC                 ((MatrixFloat)12.0f)

/*
 * ====================================================================
 * NOTE: Operational limit macros are defined in embed_sim_control.h
 * ====================================================================
 * The following macros are defined in embed_sim_control.h:
 *   - MAX_SPEED_RPM
 *   - CLOSED_LOOP_MIN_SPEED
 *   - MAX_JERK_RPM
 *   - SPEED_SETTLE_TOL
 *   - JERK_SMOOTHING_FACTOR
 *   - DFC_MAX_CURRENT
 *   - DFC_MAX_VOLTAGE
 *   - DFC_VOLTAGE_MARGIN
 * ====================================================================
 */

/**
 * @def DFC_STARTUP_MOD_MIN
 * @brief Minimum Modulation Index for Start UP
 *
 */
#define DFC_STARTUP_MOD_MIN      (0.2F)

/**
 * @def DFC_STARTUP_MOD_MAX
 * @brief Maximum Modulation Index
 *
 */
#define DFC_STARTUP_MOD_MAX       (0.2F)




#define ES_WRAP_2PI(ANGLE)  (((ANGLE) >= ES_MATH_2PI_F) ? ((ANGLE) - ES_MATH_2PI_F) :  (((ANGLE) < 0.0F) ? ((ANGLE) + ES_MATH_2PI_F) : (ANGLE)))

#define ES_WRAP_PI(ANGLE)  (((ANGLE) >= ES_MATH_PI_F) ? ((ANGLE) - ES_MATH_2PI_F) : (((ANGLE) < -ES_MATH_PI_F) ? ((ANGLE) + ES_MATH_2PI_F) : (ANGLE)))





#endif /* EMBEDSIM_EMBED_SIM_MOTOR_PARAMETER_H_ */
