/**********************************************************************************************************************
 * \file      embed_sim_dfc_controller.h
 * \brief     DFC (Direct Field Control) controller for embedded motor control applications.
 *
 * \details   Implements differential-flatness-based feedforward control for permanent magnet
 *            synchronous motors (PMSM). Uses pure flatness mapping with PI current correction.
 *            Targets 32-bit MCUs (Infineon AURIX TriCore, ARM Cortex-M4).
 *
 * \note      MISRA C:2012 compliance:
 *              - Rule  8.5 : One declaration per identifier
 *              - Rule  8.6 : No definitions in header files
 *              - Rule 17.2 : No recursion
 *
 * \note      EmbedSim naming convention:
 *              - Functions      : Pascal_Snake_Case
 *              - Parameters     : PascalCase  (single-letter → Uppercase)
 *              - Output pointers: PascalCase_P
 *              - Local variables: Lower camelCase
 *              - Struct members : PascalCase
 *              - Macros         : UPPER_SNAKE_CASE
 *              - Typedefs       : Pascal_Snake_Case_T
 *
 * \version   2.0.0
 * \date      2026-08-12
 * \author    EmbedSim / EV Light Vehicle Foundation
 *
 * \copyright Copyright (C) 2026 EmbedSim — EV Light Vehicle Foundation, Jaffna, Sri Lanka.
 *            Licensed under the MIT License.
 *********************************************************************************************************************/

#ifndef EMBED_SIM_DFC_CONTROLLER_H_
#define EMBED_SIM_DFC_CONTROLLER_H_

#include "embed_sim_sys_types.h"
#include "embed_sim_control.h"

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/

/* No public data structures required for DFC controller */

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/**
 * \brief   Initialize DFC controller
 *
 * \details Resets controller states to zero. Must be called before DFC_Step().
 *          For pure flatness feedforward, no state initialization is required.
 *
 * \return  void
 */
void DFC_Init(void);

/**
 * \brief   Execute Differential Flatness Control step
 *
 * \details Computes voltage commands using differential-flatness feedforward
 *          with PI current error correction.
 *
 *          Controller structure:
 *            - Mechanical flatness:  Te = J*ω̇ + B*ω + Tload
 *            - Current reference:    iq = Te / (1.5*p*λ_PM)
 *            - Current derivative:   iq_dot = (J*ω̈ + B*ω̇) / (1.5*p*λ_PM)
 *            - Voltage feedforward:  Vd = -p*ω*Lq*iq
 *                                    Vq = Rs*iq + Lq*iq_dot + p*ω*(Ld*id + λ_PM)
 *            - PI correction:        Vd_cmd = Vd + Kp_d*(id_ref - id)
 *                                    Vq_cmd = Vq + Kp_q*(iq_ref - iq)
 *
 *          Assumptions:
 *            - Id_ref = 0 (surface PMSM / MTPA operation)
 *            - Load torque is constant
 *            - Rotor speed reference is generated by an S-curve
 *
 * \param[in]  motorPtr  Pointer to motor structure containing:
 *                       - InputPtr   : Control input (references & feedback)
 *                       - OutputPtr  : Control output (voltage commands)
 *                       - MachinePtr : Motor parameters (resistance, inductance, flux)
 *
 * \return  void
 */
void DFC_Step(EmbedSimMachine_T* const motorPtr);

#endif /* EMBED_SIM_DFC_CONTROLLER_H_ */
