/**********************************************************************************************************************
 * \file        cdd_gate_driver_9180.h
 * \brief       TLE9180D-31QK gate driver interface for 3-phase motor control
 *              on the AURIX TC3xx Motor Control Power Board (AP32541).
 *
 * \details     The TLE9180D-31QK is driven in 6-pin mode:
 *                  ILx  — low-side  switch input (active HIGH) → GTM DTM output
 *                  /IHx — high-side switch input (active LOW)  → GTM DTM output_N
 *
 *              Dead-time is generated by the GTM DTM (CDD_GTM_DTM_DEAD_TIME_TICKS).
 *              The TLE9180D internal dead-time registers (Dt_hs / Dt_ls) are set
 *              to the minimum value (0x00 = 107 ns) so the IC's shoot-through
 *              protection remains active but does not add to the GTM dead-time.
 *
 *              Start-up sequence (TLE9180D DS Fig. 34):
 *                  1. INH = LOW, ENA = LOW, /SOFF = HIGH
 *                  2. Set INH = HIGH — device enters idle mode (tINH_Pen1 ≤ 5 ms)
 *                  3. Wait for /ERR = HIGH (ERR pin high = no fault)
 *                  4. Send SPI configuration registers (batch write)
 *                  5. Send configuration signature (addr 0x00, data 0xA1)
 *                     → device transitions to normal operation mode automatically
 *                  6. Read back operation mode register (addr 0x40) to confirm
 *                  7. Set ENA = HIGH to enable output stages
 *
 *              SPI frame format (24-bit, MSB first):
 *                  [23]    write_command  (1 = write, 0 = read)
 *                  [22:16] address        (7 bits)
 *                  [15:8]  data           (8 bits)
 *                  [7:0]   CRC3 + reserved
 *
 * \note        MISRA C:2012 compliance:
 *              - Rule  8.5 : One declaration per function
 *              - Rule  8.6 : All definitions in cdd_gate_driver_9180.c
 *
 * \copyright   Copyright (C) EmbedSim Project / Paul Abraham 2024
 *              https://github.com/vectorsim/embed_sim_project
 *              SPDX-License-Identifier: MIT
 *********************************************************************************************************************/

#ifndef CDD_GATE_DRIVER_9180_H_
#define CDD_GATE_DRIVER_9180_H_

/**********************************************************************************************************************
 * Includes
 *********************************************************************************************************************/
#include "cdd_config.h"

/**********************************************************************************************************************
 * Configuration
 *********************************************************************************************************************/

/** \brief  Number of SPI frames in the configuration batch                    */
#define GD9180_CONFIGURE_CMD_SIZE   (15U)

/** \brief  Number of SPI frames for a register read operation                 */
#define GD9180_READ_REG_SIZE        (2U)

/**********************************************************************************************************************
 * Data Types — SPI Frame
 *********************************************************************************************************************/

/**
 * \brief  TLE9180D receive frame bit-fields (MISO).
 */
typedef struct
{
    uint32_T    crc3        : 3;    /**< \brief [2:0]   CRC3                   */
    uint32_T    reserved_3  : 1;    /**< \brief [3]     reserved               */
    uint32_T    data        : 8;    /**< \brief [11:4]  data byte              */
    uint32_T    address     : 7;    /**< \brief [18:12] address                */
    uint32_T    specialEvt  : 1;    /**< \brief [19]    special event flag     */
    uint32_T    spiError    : 1;    /**< \brief [20]    SPI error flag         */
    uint32_T    configValid : 1;    /**< \brief [21]    config valid flag      */
    uint32_T    warning     : 1;    /**< \brief [22]    warning flag           */
    uint32_T    error       : 1;    /**< \brief [23]    error flag             */
    uint32_T    reserved_24 : 8;    /**< \brief [31:24] reserved               */
} GD9180_Rx_Bits_T;

typedef union
{
    uint32_T        U;
    GD9180_Rx_Bits_T B;
} GD9180_Rx_Frame_T;

/**
 * \brief  TLE9180D transmit frame bit-fields (MOSI).
 */
typedef struct
{
    uint32_T    crc3        : 3;    /**< \brief [2:0]   CRC3                   */
    uint32_T    reserved_3  : 5;    /**< \brief [7:3]   reserved               */
    uint32_T    data        : 8;    /**< \brief [15:8]  data byte              */
    uint32_T    address     : 7;    /**< \brief [22:16] address                */
    uint32_T    write_cmd   : 1;    /**< \brief [23]    1 = write, 0 = read   */
    uint32_T    reserved_24 : 8;    /**< \brief [31:24] reserved               */
} GD9180_Tx_Bits_T;

typedef union
{
    uint32_T        U;
    GD9180_Tx_Bits_T B;
} GD9180_Tx_Frame_T;

/**
 * \brief  TLE9180D operation mode register 0x40 decoded fields.
 */
typedef struct
{
    uint32_T    idle_m      : 1;    /**< \brief Idle mode active               */
    uint32_T    conf_m      : 1;    /**< \brief Configuration mode active      */
    uint32_T    conf_lock   : 1;    /**< \brief Configuration lock active      */
    uint32_T    self_test_m : 1;    /**< \brief Self-test mode active          */
    uint32_T    soff_m      : 1;    /**< \brief Safe-off mode active           */
    uint32_T    err_m       : 1;    /**< \brief Error mode active              */
    uint32_T    rect_m      : 1;    /**< \brief Rectifier mode active          */
    uint32_T    norm_m      : 1;    /**< \brief Normal operation mode active   */
} GD9180_OpMode_T;

/**********************************************************************************************************************
 * Function Prototypes
 *********************************************************************************************************************/

/**
 * \brief   Initialises GPIO control pins for the TLE9180D (INH/ENA/SOFF/ERR).
 * \details Sets default safe state: INH=LOW, ENA=LOW, /SOFF=HIGH.
 *          GPIO pins must already be configured as outputs by cdd_gpio_app.
 * \return  None
 */
extern void GD9180_Init_Pins(void);

/**
 * \brief   Executes the recommended TLE9180D power-up sequence (DS Fig. 34).
 *
 * \details Full sequence:
 *              1. Assert sleep state (INH=LOW, ENA=LOW)
 *              2. Set INH=HIGH — starts idle mode
 *              3. Wait up to 10 ms for /ERR pin to go HIGH
 *              4. Send 15-register SPI configuration batch
 *              5. Send configuration signature (addr 0x00 → normal mode)
 *              6. Read back operation mode register 0x40
 *              7. Set ENA=HIGH if normal mode confirmed
 *
 * \return  1 if device entered normal operation mode, 0 on failure
 */
extern uint32_T GD9180_Startup(void);

/**
 * \brief   Sends the 15-register SPI configuration batch.
 *
 * \details Configures failure modes, dead-time (minimum for 6-pin DTM mode),
 *          CSA gain, VRO voltage, and other parameters.
 *          Must be called while device is in idle or configuration mode.
 *
 * \return  1 if all frames transmitted successfully, 0 on SPI error
 */
extern uint32_T GD9180_Configure(void);

/**
 * \brief   Reads the operation mode register (addr 0x40) into Reg_Ptr.
 * \param   Reg_Ptr   Pointer to decoded operation mode structure
 * \return  None
 */
extern void GD9180_Read_Op_Mode(GD9180_OpMode_T * const Reg_Ptr);

/**
 * \brief   Returns 1 if the /ERR pin is HIGH (no fault), 0 if fault present.
 * \return  1 = no fault, 0 = fault
 */
extern uint32_T GD9180_No_Error(void);

/**
 * \brief   Asserts emergency safe-off: sets /SOFF = LOW and ENA = LOW.
 * \details All output stages turn off immediately.  SPI and CSAs remain active.
 *          Call from fault handler or IPC MOTOR_STOP handler.
 * \return  None
 */
extern void GD9180_Safe_Off(void);

/**
 * \brief   Releases safe-off state: sets /SOFF = HIGH.
 * \details Call after fault is cleared and before re-enabling with GD9180_Enable_Outputs.
 * \return  None
 */
extern void GD9180_Release_Safe_Off(void);

/**
 * \brief   Enables output stages: sets ENA = HIGH.
 * \details Call after GD9180_Startup() returns 1 and GTM PWM is running.
 * \return  None
 */
extern void GD9180_Enable_Outputs(void);

/**
 * \brief   Disables output stages: sets ENA = LOW.
 * \details Does not enter safe-off or sleep mode.
 * \return  None
 */
extern void GD9180_Disable_Outputs(void);

#endif /* CDD_GATE_DRIVER_9180_H_ */
