/*
 * \file Display_Qspi_Init.h
 * \brief
 * \ingroup
 * \version 
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by 
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the 
 * Software, and to permit third-parties to whom the Software is furnished to 
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */


#ifndef DISPLAY_QSPI_INIT_H_
#define DISPLAY_QSPI_INIT_H_

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "IfxQspi_SpiMaster.h"
#include "IfxDma.h"
#include "Display_Cfg_AppKitTft_TC387A.h"
/******************************************************************************/
/*--------------------------------Macros--------------------------------------*/
/******************************************************************************/
#define SPI_0_MODULE                            TFT_SPI_MODULE
#define SPI_0_CLOCK_PIN                         TFT_SPI_CLOCK_PIN
#define SPI_0_MOSI_PIN                          TFT_SPI_MOSI_PIN
#define SPI_0_MISO_PIN                          TFT_SPI_MISO_PIN
#define SPI_0_HOST_CPU                          TFT_SPI_HOST_CPU
#define SPI_0_USE_DMA                           TFT_SPI_USE_DMA
#define SPI_0_TX_DMA_CH                         TFT_SPI_TX_DMA_CH
#define SPI_0_RX_DMA_CH                         TFT_SPI_RX_DMA_CH


#define TFT_QSPI_INIT()                 &spiMasterQspi0
#define TOUCH_QSPI_INIT()               &spiMasterQspi0
/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
extern IfxQspi_SpiMaster           spiMasterQspi0;

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/
 
/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/
IFX_EXTERN void Display_initSpiModules(void);
/******************************************************************************/
/*-------------------------Inline Function Prototypes-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*---------------------Inline Function Implementations------------------------*/
/******************************************************************************/

#endif /* DISPLAY_QSPI_INIT_H_ */
