/**********************************************************************************************************************
 * \file cdd_gpio_app.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "cdd_gpio_app.h"
#include "IfxPort_reg.h"
#include "IfxEGtm_reg.h"


/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* None. */

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* None. */

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
/* None. */

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
/* None. */

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/**
 * \brief   Configures P02.0 as the ATOM0 CH0 master PWM output.
 *
 * \details Performs both halves of the pin setup:
 *            -# Configures the P02.0 pad as output (PCSR0 + DRVCFG).
 *            -# Routes the eGTM TOUT0 signal to P02.0 via TOUTSEL0.SEL0,
 *               selecting CDTM0_DTM4_0 (ATOM0 channel 0 dead-time output).
 *
 *          Without the TOUTSEL write the pad is enabled as an alternate
 *          function but no eGTM signal is connected to it, so the pin
 *          remains idle.
 *
 * \return  void
 */
void CddGpio_ConfigEgtmAtomMasterP02_00(void)
{
    Ifx_P_PADCFG_DRVCFG    padCfg;
    Ifx_EGTM_TOUTSEL       toutSel;

    padCfg.U  = P02_PADCFG0_DRVCFG.U;
    toutSel.U = EGTM_TOUTSEL0.U;

    padCfg.B.MODE  = 0x9u;   /* pad driver mode   */
    padCfg.B.DIR   = 0x1u;   /* direction: output */
    toutSel.B.SEL0 = 0x1U;   /* output selection  */

    P02_PADCFG0_DRVCFG.U = padCfg.U;
    EGTM_TOUTSEL0.U      = toutSel.U;
}


void CddGpio_ConfigEgtmAtomUhP02_05(void)
{
    Ifx_P_PADCFG_DRVCFG    padCfg;
    Ifx_EGTM_TOUTSEL       toutSel;

    toutSel.U = EGTM_TOUTSEL0.U;
    padCfg.U  = P02_PADCFG5_DRVCFG.U;

    padCfg.B.MODE  = 0x9U;   /* pad driver mode   */
    padCfg.B.DIR   = 0x1U;   /* direction: output */
    toutSel.B.SEL5 = 0x12U;  /* output selection  */

    P02_PADCFG5_DRVCFG.U = padCfg.U;
    EGTM_TOUTSEL0.U = toutSel.U;
}


void CddGpio_ConfigEgtmAtomUlP00_02(void)
{

    Ifx_P_PADCFG_DRVCFG    padCfg;
    Ifx_EGTM_TOUTSEL       toutSel;

    padCfg.U = P00_PADCFG2_DRVCFG.U;
    toutSel.U = EGTM_TOUTSEL1.U;

    padCfg.B.MODE  = 0x09U;   /* pad driver mode   */
    padCfg.B.DIR   = 0x01U;   /* direction: output */
    toutSel.B.SEL5 = 0x01U;   /* tout egtm          */

    P00_PADCFG2_DRVCFG.U = padCfg.U;
    EGTM_TOUTSEL1.U = toutSel.U;
}

void CddGpio_ConfigEgtmAtomVhP02_06(void)
{

    Ifx_P_PADCFG_DRVCFG    padCfg;
    Ifx_EGTM_TOUTSEL       toutSel;

    toutSel.U = EGTM_TOUTSEL1.U;
    padCfg.U = P02_PADCFG6_DRVCFG.U;

    padCfg.B.MODE  = 0x9U;   /* pad driver mode    */
    padCfg.B.DIR   = 0x1U;   /* direction: output  */
    toutSel.B.SEL0 = 0x12U;  /* tout egtm          */

    P02_PADCFG6_DRVCFG.U = padCfg.U;
    EGTM_TOUTSEL1.U      = toutSel.U;
}


void CddGpio_ConfigEgtmAtomVlP00_04(void)
{

    Ifx_P_PADCFG_DRVCFG    padCfg;
    Ifx_EGTM_TOUTSEL       toutSel;

    padCfg.U = P00_PADCFG4_DRVCFG.U;
    toutSel.U = EGTM_TOUTSEL2.U;

    padCfg.B.MODE  = 0x09U;   /* pad driver mode    */
    padCfg.B.DIR   = 0x1U;    /* direction: output  */
    toutSel.B.SEL1 = 0x1U;    /* tout egtm          */

    P00_PADCFG4_DRVCFG.U = padCfg.U;
    EGTM_TOUTSEL2.U = toutSel.U;
}


void CddGpio_ConfigEgtmAtomWhP02_07(void)
{

    Ifx_P_PADCFG_DRVCFG    padCfg;
    Ifx_EGTM_TOUTSEL       toutSel;

    padCfg.U  = P02_PADCFG7_DRVCFG.U;
    toutSel.U = EGTM_TOUTSEL1.U;

    padCfg.B.MODE  = 0x09U;   /* pad driver mode   */
    padCfg.B.DIR   = 0x1U;    /* direction: output */
    toutSel.B.SEL1 = 0x12U;   /* tout egtm          */

    P02_PADCFG7_DRVCFG.U = padCfg.U;
    EGTM_TOUTSEL1.U = toutSel.U;
}


void CddGpio_ConfigEgtmAtomWlP00_06(void)
{

    Ifx_P_PADCFG_DRVCFG    padCfg;
    Ifx_EGTM_TOUTSEL       toutSel;

    padCfg.U = P00_PADCFG6_DRVCFG.U;
    toutSel.U =   EGTM_TOUTSEL2.U ;

    padCfg.B.MODE  = 0x09U;   /* pad driver mode    */
    padCfg.B.DIR   = 0x01U;   /* direction: output  */
    toutSel.B.SEL3 = 0x1U;     /* tout egtm          */

    P00_PADCFG6_DRVCFG.U = padCfg.U;
    EGTM_TOUTSEL2.U = toutSel.U;
}
