/*
 * \file Display_Functions.h
 * \brief
 * \ingroup
 * \version 
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by 
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the 
 * Software, and to permit third-parties to whom the Software is furnished to 
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */


#ifndef DISPLAY_FUNCTIONS_H_
#define DISPLAY_FUNCTIONS_H_

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "Ifx_Types.h"
#include "conio_tft.h"
#include "touch.h"
#include "stdio.h"

/******************************************************************************/
/*--------------------------------Macros--------------------------------------*/
/******************************************************************************/

//typedef uint8 TDISPLAY_GRAPHICS0[GRAPHICSWIDTH/4];    //4 color
typedef uint8 TDISPLAY_GRAPHICS0[GRAPHICSWIDTH/2];      //16 color
//typedef uint8 TDISPLAY_GRAPHICS0[GRAPHICSWIDTH];        //256 color
//typedef uint8 TDISPLAY_GRAPHICS1[GRAPHICSWIDTH];        //256 color

#ifdef TFT_OVER_DAS
#if (!defined(DAS_BUFFER_LEN))
//#define DAS_BUFFER_LEN (TCOLORTABLEASCII_SIZE * 2 + 2* TERMINAL_MAXX + TCOLORTABLE_SIZE * 2+ (GRAPHICSWIDTH / 1))   //maximum information
#define DAS_BUFFER_LEN (TCOLORTABLEASCII_SIZE * 2 + 2* TERMINAL_MAXX + TCOLORTABLE_SIZE * 2 + (GRAPHICSWIDTH / 2))  //maximum information
//#define DAS_BUFFER_LEN (TCOLORTABLEASCII_SIZE * 2 + 2* TERMINAL_MAXX + TCOLORTABLE_SIZE * 2+ (GRAPHICSWIDTH / 4))   //maximum information
#endif
#endif
/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/
 
/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/
IFX_EXTERN void Dispaly_initDisplay(void);
IFX_EXTERN void tft_appl_init (void);
IFX_EXTERN void keyboard (sint16 x, sint16 y);
IFX_EXTERN void switchoff (sint16 x, sint16 y);
IFX_EXTERN void showalarm (sint16 x, sint16 y);
IFX_EXTERN void set_time (sint16 x, sint16 y);
IFX_EXTERN void set_alarmtime (sint16 x, sint16 y);

IFX_EXTERN void slideshow_periodic (void);
IFX_EXTERN void start_slideshow(void);

/******************************************************************************/
/*-------------------------Inline Function Prototypes-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*---------------------Inline Function Implementations------------------------*/
/******************************************************************************/


#endif /* DISPLAY_FUNCTIONS_H_ */
