/**********************************************************************************************************************
 * \file      embed_sim_mpc_gains_tuned.h
 * \brief     MPC FOC — NN-tuned weight constants for NANOTEC DB42S02
 *
 * \details   AUTO-GENERATED by db42s02_closed_loop_mpc_foc_20k.py.  DO NOT EDIT MANUALLY.
 *
 *            TUNING AUDIT TRAIL
 *            ===================
 *            Generated   : 2026-04-15 20:36
 *            Method      : Latin-Hypercube (40 samples) + MLP 5->16->16->1
 *                          + Adam gradient descent (8 restarts x 400 steps)
 *            Noise model : DISABLED during exploration (clean plant, deterministic surface)
 *            Target      : 2000 RPM  V_DC=17.0V  dt=50µs
 *            Fixed params: Q_omega=500.0  N=10  SMO_K=4.68  SMO_FC=1000
 *
 *            COST FUNCTION
 *            ==============
 *            cost = 80.0  * id_rms_A          (d-axis MTPA, target 0)
 *                 + 2.0  * ss_err_RPM         (speed tracking)
 *                 + 0.5 * load_drop_RPM      (load rejection)
 *                 + 20.0 * [1 if Vref_p90 >= 0.93]  (over-modulation)
 *
 *            VERIFICATION RESULT (clean plant)
 *            ==================================
 *            Total cost     : 108.6851
 *            id RMS (MTPA)  : 0.6821 A    (target 0)
 *            SS speed error : 21.07 RPM
 *            Load drop      : 24.0 RPM  at t=1.2s
 *
 * \note      MISRA C:2012 — Rule 7.2: float literals carry 'f' suffix.
 *
 * \version   1.0.0  (auto-generated)
 * \copyright Copyright (C) EmbedSim 2026
 *********************************************************************************************************************/

#ifndef EMBED_SIM_MPC_GAINS_TUNED_H_
#define EMBED_SIM_MPC_GAINS_TUNED_H_

#include "embed_sim_matrix.h"    /* MatrixFloat = real32_T */

/** \defgroup MPC_Gains_Tuned  NN-tuned MPC weight constants  \{ */

#define MPC_Q_ID     ((MatrixFloat)10.823616f)   /**< d-axis state cost (was 10.0000) */
#define MPC_Q_IQ     ((MatrixFloat)0.010000f)   /**< q-axis regulariser (was 0.1000) */
#define MPC_R_VD     ((MatrixFloat)0.001000f)   /**< vd effort weight  (was 0.0100) */
#define MPC_R_VQ     ((MatrixFloat)0.005000f)   /**< vq effort weight  (was 0.0100) */
#define MPC_KI_V     ((MatrixFloat)0.100000f)   /**< speed integral    (was 0.0300) */
#define MPC_Q_OMEGA  ((MatrixFloat)500.0f)  /**< speed cost (FIXED) */

/** \} */

typedef struct {
    MatrixFloat Q_id;     /**< 10.823616 */
    MatrixFloat Q_iq;     /**< 0.010000 */
    MatrixFloat R_vd;     /**< 0.001000 */
    MatrixFloat R_vq;     /**< 0.005000 */
    MatrixFloat KI_v;     /**< 0.100000 */
    MatrixFloat Q_omega;  /**< 500.0f (fixed) */
} MPC_GainSet_T;

#endif /* EMBED_SIM_MPC_GAINS_TUNED_H_ */
