"""
Auto-generated FMUBlock subclass for: PMSM_Motor
Source model: PMSM with realistic sensor outputs - currents, position, back-EMF

Generated by mo_to_fmu_client.py
DO NOT EDIT — re-run generator to update.

USAGE:
    from PMSM_MotorBlock import PMSM_MotorBlock

    block = PMSM_MotorBlock(
        name="pmsm_motor",
        fmu_path="PMSM_Motor.fmu",
    )
    # Drop into any EmbedSim simulation engine as a VectorBlock.

INPUTS  : duty_a, duty_b, duty_c, v_dc, T_load
OUTPUTS : i_a, i_b, i_c, theta_m, omega_m_out, emf_a, emf_b, emf_c, speed_rpm, T_em_out, P_out, P_in, efficiency, i_d, i_q, omega_m, theta_e, v_neutral, omega_e, T_em
PARAMS  : R, L_d, L_q, lambda_pm, J, B, p
"""

from __future__ import annotations
import sys
from typing import Dict, List, Optional
from embedsim.fmu_blocks import FMUBlock
from _path_utils import get_embedsim_import_path
sys.path.insert(0, get_embedsim_import_path())

class PMSM_MotorBlock(FMUBlock):
    """
    Typed FMUBlock for the PMSM_Motor OpenModelica model.
    PMSM with realistic sensor outputs - currents, position, back-EMF
    
    Subclasses FMUBlock — all VectorBlock lifecycle methods
    (reset, compute_py, terminate) are inherited.
    """

    # FMU variable lists — passed to FMUBlock automatically
    INPUT_VARS:  List[str] = ['duty_a', 'duty_b', 'duty_c', 'v_dc', 'T_load']
    OUTPUT_VARS: List[str] = ['i_a', 'i_b', 'i_c', 'theta_m', 'omega_m_out', 'emf_a', 'emf_b', 'emf_c', 'speed_rpm', 'T_em_out', 'P_out', 'P_in', 'efficiency', 'i_d', 'i_q', 'omega_m', 'theta_e', 'v_neutral', 'omega_e', 'T_em']

    DEFAULT_PARAMS: Dict[str, float] = {
        'R': 0.19,  # [Ohm]
        'L_d': 0.000125,  # [H]
        'L_q': 0.000125,  # [H]
        'lambda_pm': 0.0014,  # [Wb]
        'J': 2.4e-06,  # [kg.m2]
        'B': 1e-06,  # [N.m.s/rad]
        'p': 4.0,  # [-]
    }

    def __init__(
        self,
        name: str,
        fmu_path: str = "PMSM_Motor.fmu",
        R: float = 0.19,  # [Ohm]
        L_d: float = 0.000125,  # [H]
        L_q: float = 0.000125,  # [H]
        lambda_pm: float = 0.0014,  # [Wb]
        J: float = 2.4e-06,  # [kg.m2]
        B: float = 1e-06,  # [N.m.s/rad]
        p: float = 4.0,  # [-]
        use_c_backend: bool = False,
        dtype=None,
    ) -> None:
        """
        Create a PMSM_MotorBlock block.
        
        Parameters
        ----------
        name      : Unique block identifier within the simulation graph.
        fmu_path  : Path to PMSM_Motor.fmu (produced by OpenModelica).
        R           : Stator phase resistance [Ohm]
        L_d         : d-axis inductance [H]
        L_q         : q-axis inductance [H]
        lambda_pm   : PM flux linkage [Wb]
        J           : Rotor inertia [kg.m2]
        B           : Viscous friction [N.m.s/rad]
        p           : Number of pole pairs [-]
        """
        _params = {
            'R': R,
            'L_d': L_d,
            'L_q': L_q,
            'lambda_pm': lambda_pm,
            'J': J,
            'B': B,
            'p': p,
        }
        super().__init__(
            name=name,
            fmu_path=fmu_path,
            input_names=self.INPUT_VARS,
            output_names=self.OUTPUT_VARS,
            parameters=_params,
            instance_name=name,
            use_c_backend=use_c_backend,
            dtype=dtype,
        )

    # ── Parameter setters (callable after instantiation) ──────
    def set_R(self, value: float) -> None:
        """Set R [Ohm] — delegates to FMUBlock.set_parameter."""
        self.set_parameter('R', value)

    def set_L_d(self, value: float) -> None:
        """Set L_d [H] — delegates to FMUBlock.set_parameter."""
        self.set_parameter('L_d', value)

    def set_L_q(self, value: float) -> None:
        """Set L_q [H] — delegates to FMUBlock.set_parameter."""
        self.set_parameter('L_q', value)

    def set_lambda_pm(self, value: float) -> None:
        """Set lambda_pm [Wb] — delegates to FMUBlock.set_parameter."""
        self.set_parameter('lambda_pm', value)

    def set_J(self, value: float) -> None:
        """Set J [kg.m2] — delegates to FMUBlock.set_parameter."""
        self.set_parameter('J', value)

    def set_B(self, value: float) -> None:
        """Set B [N.m.s/rad] — delegates to FMUBlock.set_parameter."""
        self.set_parameter('B', value)

    def set_p(self, value: float) -> None:
        """Set p [-] — delegates to FMUBlock.set_parameter."""
        self.set_parameter('p', value)

    # ── Output readers (typed convenience accessors) ────────────
    def read_i_a(self) -> float:
        """Read Phase A current sensor [A] - ACTUAL [A]"""
        return self.get_output_by_name('i_a')

    def read_i_b(self) -> float:
        """Read Phase B current sensor [A] - ACTUAL [A]"""
        return self.get_output_by_name('i_b')

    def read_i_c(self) -> float:
        """Read Phase C current sensor [A] - ACTUAL [A]"""
        return self.get_output_by_name('i_c')

    def read_theta_m(self) -> float:
        """Read Resolver: mechanical angle [rad] - ACTUAL [rad]"""
        return self.get_output_by_name('theta_m')

    def read_omega_m_out(self) -> float:
        """Read Resolver: mechanical speed [rad/s] - ACTUAL [rad/s]"""
        return self.get_output_by_name('omega_m_out')

    def read_emf_a(self) -> float:
        """Read Phase A back-EMF [V] - ACTUAL [V]"""
        return self.get_output_by_name('emf_a')

    def read_emf_b(self) -> float:
        """Read Phase B back-EMF [V] - ACTUAL [V]"""
        return self.get_output_by_name('emf_b')

    def read_emf_c(self) -> float:
        """Read Phase C back-EMF [V] - ACTUAL [V]"""
        return self.get_output_by_name('emf_c')

    def read_speed_rpm(self) -> float:
        """Read Shaft speed [RPM] - ACTUAL [RPM]"""
        return self.get_output_by_name('speed_rpm')

    def read_T_em_out(self) -> float:
        """Read Electromagnetic torque [N.m] - ACTUAL [N.m]"""
        return self.get_output_by_name('T_em_out')

    def read_P_out(self) -> float:
        """Read Output power [W] - ACTUAL [W]"""
        return self.get_output_by_name('P_out')

    def read_P_in(self) -> float:
        """Read Input power [W] - ACTUAL [W]"""
        return self.get_output_by_name('P_in')

    def read_efficiency(self) -> float:
        """Read Motor efficiency [%] - ACTUAL [%]"""
        return self.get_output_by_name('efficiency')

    def read_i_d(self) -> float:
        """Read d-axis current [A] [A]"""
        return self.get_output_by_name('i_d')

    def read_i_q(self) -> float:
        """Read q-axis current [A] [A]"""
        return self.get_output_by_name('i_q')

    def read_omega_m(self) -> float:
        """Read Actual mechanical speed [rad/s] [rad/s]"""
        return self.get_output_by_name('omega_m')

    def read_theta_e(self) -> float:
        """Read Actual electrical angle [rad] [rad]"""
        return self.get_output_by_name('theta_e')

    def read_v_neutral(self) -> float:
        """Read v_neutral"""
        return self.get_output_by_name('v_neutral')

    def read_omega_e(self) -> float:
        """Read omega_e"""
        return self.get_output_by_name('omega_e')

    def read_T_em(self) -> float:
        """Read T_em"""
        return self.get_output_by_name('T_em')

    def get_all(self) -> Dict[str, float]:
        """Return all output variables as a named dict."""
        return self.get_all_outputs()

    def __repr__(self) -> str:
        return (
            f"PMSM_MotorBlock(name={self.name!r}, "
            f"fmu={self.fmu_path!r}, "
            f"init={self._initialized})"
        )
