"""
Auto-generated FMUBlock subclass for: ThreePhaseMotor
Source model: PMSM 3-Phase Motor in dq0 Reference Frame for FMU Co-Simulation

Generated by mo_to_fmu_client.py
DO NOT EDIT — re-run generator to update.

USAGE:
    from ThreePhaseMotorBlock import ThreePhaseMotorBlock

    block = ThreePhaseMotorBlock(
        name="threephasemotor",
        fmu_path="ThreePhaseMotor.fmu",
    )
    # Drop into any EmbedSim simulation engine as a VectorBlock.

INPUTS  : v_d, v_q, T_load
OUTPUTS : i_d, i_q, omega_m, theta_e, T_em, omega_e, speed_rpm
PARAMS  : R, L_d, L_q, lambda_pm, J, B, p
"""

from __future__ import annotations

from typing import Dict, List, Optional
from embedsim.fmu_blocks import FMUBlock


class ThreePhaseMotorBlock(FMUBlock):
    """
    Typed FMUBlock for the ThreePhaseMotor OpenModelica model.
    PMSM 3-Phase Motor in dq0 Reference Frame for FMU Co-Simulation
    
    Subclasses FMUBlock — all VectorBlock lifecycle methods
    (reset, compute_py, terminate) are inherited.
    """

    # FMU variable lists — passed to FMUBlock automatically
    INPUT_VARS:  List[str] = ['v_d', 'v_q', 'T_load']
    OUTPUT_VARS: List[str] = ['i_d', 'i_q', 'omega_m', 'theta_e', 'T_em', 'omega_e', 'speed_rpm']

    DEFAULT_PARAMS: Dict[str, float] = {
        'R': 0.5,  # [Ohm]
        'L_d': 0.005,  # [H]
        'L_q': 0.006,  # [H]
        'lambda_pm': 0.175,  # [Wb]
        'J': 0.002,  # [kg.m2]
        'B': 0.001,  # [N.m.s/rad]
        'p': 2.0,  # [-]
    }

    def __init__(
        self,
        name: str,
        fmu_path: str = "ThreePhaseMotor.fmu",
        R: float = 0.5,  # [Ohm]
        L_d: float = 0.005,  # [H]
        L_q: float = 0.006,  # [H]
        lambda_pm: float = 0.175,  # [Wb]
        J: float = 0.002,  # [kg.m2]
        B: float = 0.001,  # [N.m.s/rad]
        p: float = 2.0,  # [-]
        use_c_backend: bool = False,
        dtype=None,
    ) -> None:
        """
        Create a ThreePhaseMotorBlock block.
        
        Parameters
        ----------
        name      : Unique block identifier within the simulation graph.
        fmu_path  : Path to ThreePhaseMotor.fmu (produced by OpenModelica).
        R           : Stator resistance [Ohm]
        L_d         : d-axis inductance [H]
        L_q         : q-axis inductance [H]
        lambda_pm   : Permanent magnet flux linkage [Wb]
        J           : Rotor inertia [kg.m2]
        B           : Viscous friction coefficient [N.m.s/rad]
        p           : Number of pole pairs [-]
        """
        _params = {
            'R': R,
            'L_d': L_d,
            'L_q': L_q,
            'lambda_pm': lambda_pm,
            'J': J,
            'B': B,
            'p': p,
        }
        super().__init__(
            name=name,
            fmu_path=fmu_path,
            input_names=self.INPUT_VARS,
            output_names=self.OUTPUT_VARS,
            parameters=_params,
            instance_name=name,
            use_c_backend=use_c_backend,
            dtype=dtype,
        )

    # ── Parameter setters (callable after instantiation) ──────
    def set_R(self, value: float) -> None:
        """Set R [Ohm] — delegates to FMUBlock.set_parameter."""
        self.set_parameter('R', value)

    def set_L_d(self, value: float) -> None:
        """Set L_d [H] — delegates to FMUBlock.set_parameter."""
        self.set_parameter('L_d', value)

    def set_L_q(self, value: float) -> None:
        """Set L_q [H] — delegates to FMUBlock.set_parameter."""
        self.set_parameter('L_q', value)

    def set_lambda_pm(self, value: float) -> None:
        """Set lambda_pm [Wb] — delegates to FMUBlock.set_parameter."""
        self.set_parameter('lambda_pm', value)

    def set_J(self, value: float) -> None:
        """Set J [kg.m2] — delegates to FMUBlock.set_parameter."""
        self.set_parameter('J', value)

    def set_B(self, value: float) -> None:
        """Set B [N.m.s/rad] — delegates to FMUBlock.set_parameter."""
        self.set_parameter('B', value)

    def set_p(self, value: float) -> None:
        """Set p [-] — delegates to FMUBlock.set_parameter."""
        self.set_parameter('p', value)

    # ── Output readers (typed convenience accessors) ────────────
    def read_i_d(self) -> float:
        """Read d-axis current [A] [A]"""
        return self.get_output_by_name('i_d')

    def read_i_q(self) -> float:
        """Read q-axis current [A] [A]"""
        return self.get_output_by_name('i_q')

    def read_omega_m(self) -> float:
        """Read Mechanical angular velocity [rad/s] [rad/s]"""
        return self.get_output_by_name('omega_m')

    def read_theta_e(self) -> float:
        """Read Electrical rotor angle [rad] [rad]"""
        return self.get_output_by_name('theta_e')

    def read_T_em(self) -> float:
        """Read Electromagnetic torque [N.m] [N.m]"""
        return self.get_output_by_name('T_em')

    def read_omega_e(self) -> float:
        """Read Electrical angular velocity [rad/s] [rad/s]"""
        return self.get_output_by_name('omega_e')

    def read_speed_rpm(self) -> float:
        """Read Shaft speed [RPM] [RPM]"""
        return self.get_output_by_name('speed_rpm')

    def get_all(self) -> Dict[str, float]:
        """Return all output variables as a named dict."""
        return self.get_all_outputs()

    def __repr__(self) -> str:
        return (
            f"ThreePhaseMotorBlock(name={self.name!r}, "
            f"fmu={self.fmu_path!r}, "
            f"init={self._initialized})"
        )
