/* Simulation code for BuckConverter generated by the OpenModelica Compiler OpenModelica 1.26.4. */
#if !defined(BuckConverter__MODEL_H)
#define BuckConverter__MODEL_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#include <string.h>

#include "BuckConverter_functions.h"


extern void BuckConverter_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void BuckConverter_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int BuckConverter_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int BuckConverter_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int BuckConverter_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int BuckConverter_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int BuckConverter_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int BuckConverter_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int BuckConverter_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int BuckConverter_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int BuckConverter_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int BuckConverter_checkForAsserts(DATA *data, threadData_t *threadData);
extern int BuckConverter_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int BuckConverter_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int BuckConverter_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* BuckConverter_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* BuckConverter_relationDescription(int i);
extern void BuckConverter_function_initSample(DATA *data, threadData_t *threadData);
extern int BuckConverter_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int BuckConverter_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int BuckConverter_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int BuckConverter_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int BuckConverter_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int BuckConverter_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int BuckConverter_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int BuckConverter_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int BuckConverter_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int BuckConverter_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int BuckConverter_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int BuckConverter_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int BuckConverter_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int BuckConverter_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* BuckConverter_linear_model_frame(void);
extern const char* BuckConverter_linear_model_datarecovery_frame(void);
extern int BuckConverter_mayer(DATA* data, modelica_real** res, short *);
extern int BuckConverter_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int BuckConverter_getInputVarIndicesInOptimization(DATA* data, int* input_var_indices);
extern int BuckConverter_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int BuckConverter_setInputData(DATA *data, const modelica_boolean file);
extern int BuckConverter_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void BuckConverter_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void BuckConverter_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int BuckConverter_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void BuckConverter_read_simulation_info(SIMULATION_INFO* simulationData);
extern void BuckConverter_read_input_fmu(MODEL_DATA* modelData);
extern void BuckConverter_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int BuckConverter_inputNames(DATA* data, char ** names);
extern int BuckConverter_dataReconciliationInputNames(DATA* data, char ** names);
extern int BuckConverter_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int BuckConverter_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int BuckConverter_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int BuckConverter_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "BuckConverter_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(BuckConverter__MODEL_H) */


