/*
 * \file Gpt12_Init.h
 * \brief Header file for GPT12 initialization for PMSM FOC motor control.
 * \ingroup pmsm_foc_configuration
 * \version 1.0
 * \date 2019
 *
 * \details
 * This file contains the function declarations for initializing and configuring
 * the GPT12 module for PMSM FOC motor control applications.
 *
 * \copyright
 * Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef GPT12_INIT_H_
#define GPT12_INIT_H_

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

/**
 * \brief Include necessary headers for GPT12 module initialization.
 */
#include "IfxGpt12_IncrEnc.h"

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/

/**
 * \brief Initialize the GPT12 module for incremental encoder functionality.
 *
 * \param[in] encoder Pointer to the GPT12 incremental encoder configuration structure.
 *
 * \details
 * This function initializes the GPT12 module for use as an incremental encoder.
 * It configures the clock prescalers, pins, interrupt priorities, and other
 * parameters required for position and speed acquisition in PMSM FOC motor control.
 *
 * \ingroup pmsm_foc_configuration
 */
IFX_EXTERN void PmsmFoc_Gpt12_initGpt12(IfxGpt12_IncrEnc* encoder);

#endif /* GPT12_INIT_H_ */
