/**
 * @file Gtm_Init.h
 * @brief Header file for GTM initialization for PMSM FOC motor control.
 * @ingroup pmsm_foc_configuration
 * @version 1.0
 * @date 2019
 *
 * @details
 * This file contains the function declarations for initializing and configuring
 * the Generic Timer Module (GTM) for PMSM FOC motor control applications. The functions
 * include GTM initialization, TOM/ATOM configurations, and EVADC triggering setups.
 *
 * @copyright
 * Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef GTM_INIT_H_
#define GTM_INIT_H_

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

/**
 * @brief Include necessary headers for GTM initialization and PMSM FOC configuration.
 */
#include "Ifx_Types.h"
#include "PmsmFoc_Inverter.h"
#include "PmsmFoc_UserConfig.h"

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/

/**
 * @brief Initialize the GTM module for PMSM FOC motor control applications.
 *
 * @param[in] inverter Pointer to the inverter structure containing instance-specific data.
 *
 * @details
 * This function initializes the Generic Timer Module (GTM) for use in PMSM FOC motor control.
 * It sets up the clock frequencies, enables the GTM module, and configures PWM channels
 * and triggers for current and voltage sensing, depending on the GTM configuration.
 *
 * @note The GTM module must be enabled and properly configured before use.
 *
 * @ingroup pmsm_foc_configuration
 */
IFX_EXTERN void PmsmFoc_Gtm_initGtm(Inverter* const inverter);

/**
 * @brief Initialize the GTM TOM module for PWM generation.
 *
 * @param[in] inverter Pointer to the inverter structure containing instance-specific data.
 *
 * @details
 * This function sets up and initializes the TOM (Timer Output Module) of the GTM
 * for PWM signal generation used in motor control applications. It configures the
 * timer channels, trigger points, and phase outputs required to control the high-side
 * and low-side switches of the inverter.
 *
 * @note This function is used specifically for TOM-based configurations.
 *
 * @ingroup pmsm_foc_configuration
 */
IFX_EXTERN void PmsmFoc_Gtm_initTom(Inverter* const inverter);

/**
 * @brief Initialize the GTM ATOM module for PWM generation.
 *
 * @param[in] inverter Pointer to the inverter structure containing instance-specific data.
 *
 * @details
 * This function initializes the ATOM (Advanced Timer Output Module) of the GTM
 * for PWM signal generation used in motor control applications. It is provided for
 * compatibility with ATOM-based PWM configurations.
 *
 * @note This function is currently not used in TOM-based configurations.
 *
 * @ingroup pmsm_foc_configuration
 */
IFX_EXTERN void PmsmFoc_Gtm_initAtom(Inverter* const inverter);

/******************************************************************************/
/*-------------------------Inline Function Prototypes-------------------------*/
/******************************************************************************/

/* No inline functions declared in this file */

/******************************************************************************/
/*---------------------Inline Function Implementations------------------------*/
/******************************************************************************/

/* No inline function implementations in this file */

#endif /* GTM_INIT_H_ */
