/*
 * \file Mcu_Init.c
 * \brief Implementation of MCU initialization for PMSM FOC motor control.
 * \details
 * This file contains the implementation of MCU initialization functions, including
 * configurations for SPI interfaces, GTM, EVADC, position sensors, and other key modules.
 *
 * \copyright
 * Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#include "Mcu_Init.h"

/******************************************************************************/
/*-------------------------------Global Variables-----------------------------*/
/******************************************************************************/

/* None for this file */

/******************************************************************************/
/*-----------------------------Private Functions------------------------------*/
/******************************************************************************/

/**
 * \brief Configure GPIO pins for LED control.
 *
 * \details
 * This function initializes the GPIO pins connected to LEDs and sets their
 * initial state to high.
 */
static void PmsmFoc_initLeds(void)
{
    /* Configure test pins */
    IfxPort_setPinModeOutput(&MODULE_P13, 0, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);   /* Set Pin13_0 as GP-Out */
    IfxPort_setPinModeOutput(&MODULE_P13, 1, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);   /* Set Pin13_1 as GP-Out */
    IfxPort_setPinModeOutput(&MODULE_P13, 2, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);   /* Set Pin13_2 as GP-Out */
    IfxPort_setPinModeOutput(&MODULE_P13, 3, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);   /* Set Pin13_3 as GP-Out */


    IfxPort_setPinMode(&MODULE_P13, 0, IfxPort_Mode_outputPushPullGeneral); /* LED107 */
    IfxPort_setPinHigh(&MODULE_P13, 0);

    IfxPort_setPinMode(&MODULE_P13, 1, IfxPort_Mode_outputPushPullGeneral); /* LED108 */
    IfxPort_setPinHigh(&MODULE_P13, 1);

    IfxPort_setPinMode(&MODULE_P13, 2, IfxPort_Mode_outputPushPullGeneral); /* LED109 */
    IfxPort_setPinHigh(&MODULE_P13, 2);

    IfxPort_setPinMode(&MODULE_P13, 3, IfxPort_Mode_outputPushPullGeneral); /* LED110 */
    IfxPort_setPinHigh(&MODULE_P13, 3);
}

/******************************************************************************/
/*-----------------------------Public Functions-------------------------------*/
/******************************************************************************/

void PmsmFoc_initHardware(MotorControl* const motorCtrl)
{
    IfxCpu_disableInterrupts();

    /* Initialize GPIO pins for LEDs */
    PmsmFoc_initLeds();

    /* Initialize SPI interfaces */
    PmsmFoc_Qspi_initQspi();

    /* Load power management and WDT configurations */
    {
        IfxCpu_enableInterrupts();

        /* Initialize the TLF35584 power management IC */
        PmsmFoc_Tlf35584_Init();
        IfxTLF35584_unprotectRegister();
        IfxTLF35584_disableWindowWatchdog();
        IfxTLF35584_disableErrPinMonitor();
        IfxTLF35584_protectRegister();
        IfxTLF35584_gotoNormalState();

        IfxCpu_disableInterrupts();
    }

    /* Initialize time constants for time functions (bsp.c) */
    initTime();

    /* Initialize the TLE9180 motor driver IC */
    PmsmFoc_Tle9180_Init();

    /* Initialize GTM driver */
    PmsmFoc_Gtm_initGtm(&motorCtrl->inverter);

    /* Initialize the EVADC driver */
    PmsmFoc_Evadc_initEvadc(&motorCtrl->inverter);

    /* Initialize the position sensor driver */
    PmsmFoc_PositionAcquisition_init(&motorCtrl->positionSensor, PositionAcquisition_SensorType_Encoder);

    /* Send startup configuration to the TLE9180 */
    IfxCpu_enableInterrupts();
    PmsmFoc_Tle9180_loadConfiguration();
    IfxCpu_disableInterrupts();
}
