/**
 * \file PmsmFoc_InitTLE9180.c
 * \brief Implementation of TLE9180 ASIC initialization for PMSM motor control systems.
 * \ingroup Tle9180
 * \date 2019
 * \details
 * This file implements the initialization functions for the TLE9180 ASIC, including SPI
 * communication setup and hardware driver configuration.
 *
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between(i) you or the
 * company in which ordinary course of business you are acting and(ii) Infineon
 * Technologies AG or its licensees. If and as long as no such terms of use are
 * agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to do
 * so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#include "PmsmFoc_InitTLE9180.h"
#include "Qspi_Init.h"
#include "IfxPort_PinMap.h"

#include "PmsmFoc_UserConfig.h"
#include MCUCARD_TYPE_PATH
#include INVERTERCARD_TYPE_PATH
#include MOTOR_TYPE_PATH

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

/**
 * \brief Global instance of the TLE9180 configuration structure.
 */
TLE9180 tle9180;

/******************************************************************************/
/*--------------------------Private Function Implementations------------------*/
/******************************************************************************/

/**
 * \brief Initialize the SPI channel for TLE9180 communication.
 * \details
 * Configures the SPI channel used for communication with the TLE9180 ASIC.
 * This includes setting the baud rate, data width, and chip select pin configuration.
 */
IFX_INLINE void PmsmFoc_Tle9180_InitSpiChannel(void)
{
    IfxQspi_SpiMaster_ChannelConfig spiChConfig;

    /* Initialize SPI channel configuration */
    IfxQspi_SpiMaster_initChannelConfig(&spiChConfig, &TLE9180_SPI);

    /* Configure SPI channel parameters */
    spiChConfig.base.baudrate = IFX_TLE9180_BAUDRATE;
    spiChConfig.base.mode.dataWidth = IFX_TLE9180_DATAWIDTH;
    spiChConfig.base.mode.csTrailDelay = SpiIf_SlsoTiming_1;
    spiChConfig.base.mode.csInactiveDelay = SpiIf_SlsoTiming_7;
    spiChConfig.base.mode.shiftClock = SpiIf_ShiftClock_shiftTransmitDataOnTrailingEdge;

    /* Configure chip select pin */
    spiChConfig.sls.output.pin = &TLE9180_SPI_CS_PIN;
    spiChConfig.sls.output.mode = IfxPort_OutputMode_pushPull;
    spiChConfig.sls.output.driver = IfxPort_PadDriver_cmosAutomotiveSpeed1;
    spiChConfig.channelBasedCs = IfxQspi_SpiMaster_ChannelBasedCs_enabled;

    /* Initialize the SPI channel */
    IfxQspi_SpiMaster_initChannel(&tle9180.spiChannel, &spiChConfig);
}

/******************************************************************************/
/*--------------------------Public Function Implementations-------------------*/
/******************************************************************************/

void PmsmFoc_Tle9180_Init(void)
{
	IfxTLE9180_Config tleConfig;

    /* Initialize the SPI channel for TLE9180 */
	PmsmFoc_Tle9180_InitSpiChannel();

    /* Configure and initialize the TLE9180 driver */
	tleConfig.size= 8192;
	tleConfig.pins.enable= TLE9180_ENABLE_PIN;
	tleConfig.pins.error= TLE9180_ERROR_PIN;
	tleConfig.pins.inhibit= TLE9180_INHIBIT_PIN;
	tleConfig.pins.safeOff= TLE9180_SAFEOFF_PIN;
	tleConfig.spiChannel= &tle9180.spiChannel;

    /* Configure the SPI interface */
	tleConfig.spiIf.spiExchange= (IfxTLE9180_SpiExchangeIfPtrType)&IfxQspi_SpiMaster_exchange;

    /* Initialize the TLE9180 driver */
	IfxTLE9180_init(&tle9180.driver, &tleConfig);
}
