/*
 * \file Evadc_Init.h
 * \brief Initialization of EVADC for current sensing in PMSM motor control applications.
 * \ingroup EVADC
 * \version 1.0.0
 * \date 2019
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 * \details
 * This header file provides the declarations and the global structure required
 * for configuring and initializing the Enhanced Versatile Analog-to-Digital
 * Converter (EVADC) in the context of Permanent Magnet Synchronous Motor (PMSM)
 * control applications. It includes:
 * - Initialization of EVADC module and ADC groups.
 * - Configuration of ADC channels for PMSM current sensing and voltage measurement.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef EVADC_INIT_H_
#define EVADC_INIT_H_

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "IfxEVadc_Adc.h"
#include "PmsmFoc_Inverter.h"

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/**
 * \brief EVADC configuration and group handles.
 * \details
 * The `Adc_Evadc` structure contains the EVADC handle and handles for up to 12 ADC groups.
 * Each group provides its own configuration and can be used for different ADC tasks such as
 * current sensing or voltage measurement.
 */
typedef struct
{
    IfxEvadc_Adc evadc; /**< EVADC module handle */
    IfxEvadc_Adc_Group adcGroup0; /**< Handle for ADC Group 0 */
    IfxEvadc_Adc_Group adcGroup1; /**< Handle for ADC Group 1 */
    IfxEvadc_Adc_Group adcGroup2; /**< Handle for ADC Group 2 */
    IfxEvadc_Adc_Group adcGroup3; /**< Handle for ADC Group 3 */
    IfxEvadc_Adc_Group adcGroup4; /**< Handle for ADC Group 4 */
    IfxEvadc_Adc_Group adcGroup5; /**< Handle for ADC Group 5 */
    IfxEvadc_Adc_Group adcGroup6; /**< Handle for ADC Group 6 */
    IfxEvadc_Adc_Group adcGroup7; /**< Handle for ADC Group 7 */
    IfxEvadc_Adc_Group adcGroup8; /**< Handle for ADC Group 8 */
    IfxEvadc_Adc_Group adcGroup9; /**< Handle for ADC Group 9 */
    IfxEvadc_Adc_Group adcGroup10; /**< Handle for ADC Group 10 */
    IfxEvadc_Adc_Group adcGroup11; /**< Handle for ADC Group 11 */
} Adc_Evadc;

/******************************************************************************/
/*------------------------------Global Variables------------------------------*/
/******************************************************************************/
/**
 * \brief Global instance of the `Adc_Evadc` structure.
 * \details
 * This global structure provides access to the EVADC module and its associated
 * ADC groups for configuration and operation.
 */
extern Adc_Evadc adcEvadc;

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/

/**
 * \brief Initialize the EVADC module and its groups.
 * \details
 * This function configures the EVADC module and assigns ADC groups for PMSM motor
 * current sensing and voltage measurement. It initializes the ADC channels and ensures
 * proper operation of the EVADC hardware.
 *
 * \param[in] inverter Pointer to the inverter structure containing the instance data members.
 * \return None
 * \ingroup EVADC
 */
IFX_EXTERN void PmsmFoc_Evadc_initEvadc(Inverter * const inverter);

#endif /* EVADC_INIT_H_ */
