/*
 * \file PmsmFoc_PwmSvm.h
 * \brief Configuration and API for PWM and Space Vector Modulation (SVM) in PMSM motor control.
 * \ingroup PwmSvm
 * \version 1.0.0
 * \date 2019
 * \details
 * This header file defines the data structures, macros, and API for PWM updates and Space
 * Vector Modulation (SVM) implementation in a PMSM motor control system. It provides
 * functions for updating PWM signals and handling SVM for efficient motor control.
 * \copyright
 * Copyright (c) 2020 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef PMSM_FOC_PWMSVM_H_
#define PMSM_FOC_PWMSVM_H_

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "PmsmFoc_Inverter.h"
#include "embedsim_step.h"

#if (EMOTOR_LIB == MC_EMOTOR)
#include "Arith.StdReal.h"
#include "SpaceVectorModulation.h"
#endif

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/

/**
 * \brief Update PWM signals for three-phase motor control.
 * \details
 * This function updates the PWM signals for a three-phase motor based on the
 * calculated duty cycles and modulation index.
 *
 * \param[in] inverter Pointer to the inverter structure containing PWM configuration.
 */
IFX_EXTERN void PmsmFoc_doPwmSvmUpdate(Inverter *const inverter);

#if (EMOTOR_LIB == MC_EMOTOR)
/**
 * \brief Perform Space Vector Modulation (SVM) for motor control.
 * \details
 * This function calculates the duty cycles for the PWM signals using Space Vector
 * Modulation (SVM) based on the modulation index and updates the SVM sector.
 *
 * \param[in] inverter Pointer to the inverter structure containing PWM configuration.
 * \param[in] modulationIndex Specifies the modulation index as a complex vector.
 */
IFX_EXTERN void PmsmFoc_doSvPwmModulation(Inverter *const inverter, CplxStdReal modulationIndex);




IFX_EXTERN void PmsmFoc_applyEmbedSimPwm(Inverter* const inverter, const EmbedSim_Output_T* sim_out);


#endif /* EMOTOR_LIB == MC_EMOTOR */

#endif /* PMSM_FOC_PWMSVM_H_ */
