/*
 * \file PmsmFoc_PositionAndSpeedAcquisition.h
 * \brief Position and speed acquisition for PMSM motor control.
 * \ingroup PositionAndSpeedAcquisition
 * \version 1.0.0
 * \date 2019
 * \details
 * This header file provides the structures, enumerations, and function prototypes required
 * for acquiring position and speed information in PMSM motor control systems. It supports
 * different sensor types, such as Hall, Encoder, Resolver, and Sensorless methods.
 * \copyright
 * Copyright (c) 2020 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef PMSM_FOC_POSITION_SPEED_ACQUISITION_H_
#define PMSM_FOC_POSITION_SPEED_ACQUISITION_H_

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "Ifx_Types.h"
#include "Gpt12_Init.h"
#include "Ifx_LowPassPt1F32.h"

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/**
 * \brief Enumeration for position acquisition sensor types.
 * \details
 * Specifies the type of sensor used for position acquisition in the PMSM motor control system.
 */
typedef enum
{
    PositionAcquisition_SensorType_Hall = 0,                /**< Hall sensor is used. */
    PositionAcquisition_SensorType_Encoder = 1,             /**< Encoder and Hall sensors are used. */
    PositionAcquisition_SensorType_Resolver = 2,            /**< Resolver sensor is used. */
    PositionAcquisition_SensorType_Sensorless = 3,          /**< Sensorless method is used. */
    PositionAcquisition_SensorType_Encoder_and_Resolver = 4 /**< Encoder and Resolver sensors are used. */
} PositionAcquisition_SensorType;

/**
 * \brief Enumeration for encoder calibration status.
 * \details
 * Indicates whether the encoder calibration process is complete.
 */
typedef enum
{
    Encoder_CalibrationStatus_notDone = 0, /**< Calibration is not completed. */
    Encoder_CalibrationStatus_done         /**< Calibration is completed. */
} Encoder_CalibrationStatus;

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/**
 * \brief Encoder configuration for position acquisition.
 * \details
 * Defines the configuration and state of an incremental encoder used for position and speed acquisition.
 */
typedef struct
{
    IfxGpt12_IncrEnc incrEncoder;           /**< Incremental encoder configuration. */
    Encoder_CalibrationStatus calibrationStatus; /**< Encoder calibration status. */
    boolean encSyncTopZero;                 /**< Encoder top zero synchronization:
                                                 - `1`: Enabled.
                                                 - `0`: Disabled. */
    boolean encOffsetCal;                   /**< Encoder offset calibration:
                                                 - `1`: Enabled.
                                                 - `0`: Disabled. */
} PositionAcquisition_Encoder;

/**
 * \brief Main structure for position and speed acquisition.
 * \details
 * Contains all configurations, filters, and status information required for acquiring position
 * and speed using various sensor types.
 */
typedef struct
{
    PositionAcquisition_Encoder encoder;    /**< Encoder configuration for position and speed acquisition. */
    Ifx_LowPassPt1F32 speedLpf;            /**< Lowpass filter for speed calculation. */
    PositionAcquisition_SensorType sensorType; /**< Sensor type used for position acquisition. */
    boolean statusOk;                      /**< Status flag indicating whether the sensor is operational. */
    uint32 electricalAngle;                /**< Electrical angle in degrees. */
    float32 rotorSpeed;                    /**< Rotor speed in RPM. */
} PositionAcquisition;

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/

/**
 * \brief Initialize position acquisition system.
 * \details
 * Configures the position acquisition system based on the specified sensor type.
 *
 * \param[in,out] positionAcquisition Pointer to the position acquisition structure.
 * \param[in] sensorType The type of sensor used for position acquisition.
 */
IFX_EXTERN void PmsmFoc_PositionAcquisition_init(PositionAcquisition *positionAcquisition, PositionAcquisition_SensorType sensorType);

/**
 * \brief Update the motor's position.
 * \details
 * Updates the motor's position based on the selected position acquisition sensor type.
 *
 * \param[in,out] positionAcquisition Pointer to the position acquisition structure.
 * \return The updated position value.
 */
IFX_EXTERN sint32 PmsmFoc_PositionAcquisition_updatePosition(PositionAcquisition *positionAcquisition);

/**
 * \brief Update the motor's speed.
 * \details
 * Updates the rotor speed using the configured sensor type and stores the calculated value.
 *
 * \param[in,out] positionAcquisition Pointer to the position acquisition structure.
 */
IFX_EXTERN void PmsmFoc_PositionAcquisition_updateSpeed(PositionAcquisition *positionAcquisition);

/**
 * \brief Retrieve the motor's speed.
 * \details
 * Returns the current rotor speed calculated using the sensor data and lowpass filter.
 *
 * \param[in] positionAcquisition Pointer to the position acquisition structure.
 * \return The rotor speed in RPM.
 */
IFX_EXTERN float32 PmsmFoc_PositionAcquisition_getSpeed(PositionAcquisition *positionAcquisition);

#endif /* PMSM_FOC_POSITION_SPEED_ACQUISITION_H_ */
