/*
 * \file PmsmFoc_CurrentDcLinkSense.h
 * \brief High-side and low-side DC link current sensing configuration and API.
 * \ingroup CurrentSensing
 * \version 1.0.0
 * \date 2019
 * \details
 * This header file defines the structures, enumerations, and APIs required for configuring
 * and handling DC link current sensing in PMSM motor control systems. It supports both
 * low-side and high-side current sensing mechanisms, including initialization, calibration,
 * gain selection, and value retrieval.
 * \copyright
 * Copyright (c) 2020 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by 
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the 
 * Software, and to permit third-parties to whom the Software is furnished to 
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */


#ifndef PMSMFOC_CURRENTDCLINKSENSE_H_
#define PMSMFOC_CURRENTDCLINKSENSE_H_

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "PmsmFoc_SensorAdc.h"
#include "Ifx_Types.h"
#include "PmsmFoc_UserConfig.h"
#include "Compilers.h"
#include "Port/Std/IfxPort.h"

#include MCUCARD_TYPE_PATH
#include INVERTERCARD_TYPE_PATH
#include MOTOR_TYPE_PATH

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/**
 * \brief Enumeration for high-side current sense gain selection.
 * \details
 * Specifies the gain values in volts-per-volt for configuring high-side current sensing hardware.
 */
typedef enum
{
    HighSideCurrentSense_Gain_25VperV = 0,  /**< 25 V/V gain  */
    HighSideCurrentSense_Gain_50VperV = 1,  /**< 50 V/V gain  */
    HighSideCurrentSense_Gain_100VperV = 2, /**< 100 V/V gain */
    HighSideCurrentSense_Gain_200VperV = 3  /**< 200 V/V gain */
} HighSideCurrentSense_Gain;


/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/
/**
 * \brief Pin configuration for high-side current sense gain selection.
 */
typedef struct
{
    IfxPort_Pin *gainSelelct0; /**< Output pin for gain select signal 0 */
    IfxPort_Pin *gainSelelct1; /**< Output pin for gain select signal 1 */
} HighSideCurrentSense_Pins;

/**
 * \brief Configuration structure for high-side current sensing initialization.
 */
typedef struct
{
    HighSideCurrentSense_Pins pins; /**< Pin configuration for gain selection */
} HighSideCurrentSense_Config;

/**
 * \brief Calibration data for low-side current sensing.
 */
typedef struct
{
    sint32 inputSum;                      /**< \brief Current phase A raw sum */
    sint32 count;                         /**< \brief Calibration index */
    PmsmFoc_SensorAdc_CalibrationStatus status;
} LowSideCurrentSense_Calibration;

/**
 * \brief Calibration data for high-side current sensing.
 */
typedef struct
{
    sint32 inputSum; /**< Accumulated raw input values during calibration. */
    sint32 count;    /**< Number of calibration samples. */
    PmsmFoc_SensorAdc_CalibrationStatus status; /**< Calibration status. */
} HighSideCurrentSense_Calibration;


/**
 * \brief Low-side current sensing structure.
 */
typedef struct
{
	PmsmFoc_SensorAdc       input;
	PmsmFoc_SensorAdc       refInput;
	LowSideCurrentSense_Calibration    calibration;
} LowSideCurrentSense;

/**
 * \brief High-side current sensing structure.
 */
typedef struct
{
    PmsmFoc_SensorAdc input; /**< ADC channel configuration for high-side current sensing. */
    HighSideCurrentSense_Calibration calibration; /**< Calibration data. */
    HighSideCurrentSense_Pins pins; /**< Gain selection pin configuration. */
    sint16 selectedGain; /**< Currently selected gain value. */
} HighSideCurrentSense;

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/

/**
 * \brief Initialize high-side current sensing.
 * \details
 * Configures the high-side current sensing system, including gain selection pins and ADC parameters.
 *
 * \param[in] highSideCurrentSense Pointer to the `HighSideCurrentSense` structure.
 * \param[in] config Pointer to the configuration structure.
 * \return `TRUE` if initialization was successful, `FALSE` otherwise.
 */
IFX_EXTERN boolean PmsmFoc_CurrentDCLinkSenseHs_init(HighSideCurrentSense *highSideCurrentSense, const HighSideCurrentSense_Config *config);

/**
 * \brief Perform calibration for high-side current sensing.
 * \details
 * Calibrates the high-side current sensing system by averaging raw input values over a predefined number of samples.
 *
 * \param[in] highSideCurrentSense Pointer to the `HighSideCurrentSense` structure.
 */
IFX_EXTERN void PmsmFoc_CurrentDCLinkSenseHs_doCalibration(HighSideCurrentSense *const highSideCurrentSense);

/**
 * \brief Set the gain for high-side current sensing.
 */
IFX_EXTERN void PmsmFoc_CurrentDCLinkSenseHs_setGain(HighSideCurrentSense *const highSideCurrentSense, HighSideCurrentSense_Gain gain);

/**
 * \brief Reset the calibration status for high-side current sensing.
 */
IFX_EXTERN void PmsmFoc_CurrentDCLinkSenseHs_resetCalibrationStatus(HighSideCurrentSense *const highSideCurrentSense);

/**
 * \brief Retrieve the calibration status.
 */
PmsmFoc_SensorAdc_CalibrationStatus PmsmFoc_CurrentDCLinkSenseHs_getCalibrationStatus(HighSideCurrentSense *const highSideCurrentSense);

/**
 * \brief Retrieve the raw current value.
 */
IFX_EXTERN void PmsmFoc_CurrentDCLinkSenseHs_getRawCurrentValue(HighSideCurrentSense *const highSideCurrentSense);

/**
 * \brief Update the ADC input.
 */
IFX_EXTERN float32 PmsmFoc_CurrentDCLinkSenseHs_updateAnalogInput(PmsmFoc_SensorAdc *const highSideCurrentSenseCh);

#endif /* PMSMFOC_CURRENTDCLINKSENSE_H_ */

