/*
 * \file Display_Cfg_AppKitTft_TC387A.h
 * \brief
 * \ingroup display_configuration
 * \version
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef DISPLAY_APPKIT_TFT_TC387A_PARAMETERS_H_
#define DISPLAY_APPKIT_TFT_TC387A_PARAMETERS_H_
/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "IfxQspi_SpiMaster.h"
#include "IfxDma.h"
#include "SysSe/Bsp/Bsp.h"
#include "Port/Std/IfxPort.h"
#include "IfxPort_PinMap.h"

/******************************************************************************/
/*--------------------------------Macros--------------------------------------*/
/******************************************************************************/

/**< \brief Interrupt priority assignment for the application 											*/
/**< \brief Instruction: Arrange the interrupt defines in ascending order of their priority! 			*/
/**< \brief Check if there are two interrupts assigned with same priority (unless they are grouped)  	*/


#define INTERRUPT_PRIORITY_QSPI0_TX     (40)  															/**< \brief Define the QSPI0 transmit interrupt priority.  */
#define INTERRUPT_PRIORITY_QSPI0_RX     (41)  															/**< \brief Define the QSPI0 receive interrupt priority.  */
#define INTERRUPT_PRIORITY_QSPI0_ERR    (42)  															/**< \brief Define the QSPI0 error interrupt priority.  */


/* TFT GPIO and QSPI define */
#define TFT_SPI_MODULE                	MODULE_QSPI0													/**< \brief Define the QSPI object */
#define TFT_SPI_CLOCK_PIN             	IfxQspi0_SCLK_P20_13_OUT										/**< \brief Define the QSPI SLCK out pin  */
#define TFT_SPI_MOSI_PIN              	IfxQspi0_MTSR_P20_14_OUT										/**< \brief Define the QSPI MTSR out pin */
#define TFT_SPI_MISO_PIN              	IfxQspi0_MRSTA_P20_12_IN										/**< \brief Define the QSPI MRSTA input pin */
#define TFT_SPI_HOST_CPU              	IfxSrc_Tos_cpu0													/**< \brief Define the handler of the interrupts*/
#define TFT_SPI_USE_DMA               	TRUE															/**< \brief Define the use of DMA for data transfer/s */
#define TFT_SPI_TX_DMA_CH             	IfxDma_ChannelId_0												/**< \brief Define the DMA channel no for the QSPI transmit */
#define TFT_SPI_RX_DMA_CH             	IfxDma_ChannelId_1

#define TFT_USE_SCLK                    TFT_SPI_CLOCK_PIN
#define TFT_USE_CHIPSELECT              IfxQspi0_SLSO8_P20_6_OUT


/**< \brief Define the DMA channel no for the QSPI receive */

/* TOUCH GPIO and QSPI define */
#define TOUCH_SPI_CS_PIN             	IfxQspi0_SLSO9_P20_3_OUT
#define TOUCH_USE_INT                   IfxPort_P20_9

//#define TFT_OVER_DAS 					1


/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Global Function Prototypes-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Inline Function Prototypes-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*---------------------Inline Function Implementations------------------------*/
/******************************************************************************/

#endif /* DISPLAY_APPKIT_TFT_TC387A_PARAMETERS_H_ */
