/**********************************************************************************************************************
 * \file DAVE_common.h
 * \brief This file contains all app related public data structures, enums and function prototypes
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 * 

********************************************************************************
**                                                                            **
**                                                                            **
** PLATFORM : Infineon                                                        **
**                                                                            **
** COMPILER : Compiler Independent                                            **
**                                                                            **
** MODIFICATION DATE : Jun 23, 2025                                           **
**                                                                            **
*******************************************************************************/

/**
 * @file  DAVE_common.h
 *
 * @brief This file contains all app related public data structures,enums and function
 *        prototypes
 *
 * Revision History
 * 23 Jun 2025 v0.1.1 Updated information for AURIX Configuration Studio, updated copyright
 * 27 Dec 2014 v0.1.0 Initial Version
 *
 */



#ifndef _DAVE_COMMON_H_
#define _DAVE_COMMON_H_

#include "Platform_Types.h"

/*******************************************************************************
**                      @Project Includes                                     **
*******************************************************************************/

/*******************************************************************************
**                      Global data structures                                **
*******************************************************************************/
typedef struct ADS_APP_VERSION_t
{
  uint8 major;
  uint8 minor;
  uint8 patch;
} ADS_APP_VERSION_t;

#define ACS_APP_VERSION_t ADS_APP_VERSION_t

/*******************************************************************************
**                      @Prototypes Of Global Functions                       **
*******************************************************************************/

#endif  /** ifndef _DAVE_COMMON_H_ */

