/* Simulation code for PMSM_Plant_FMU generated by the OpenModelica Compiler OpenModelica 1.27.0~5-ga0783c0. */
#if !defined(PMSM_Plant_FMU__MODEL_H)
#define PMSM_Plant_FMU__MODEL_H

#if defined(__cplusplus)
extern "C" {
#endif

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_json.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "util/parallel_helper.h"
#include "simulation/jacobian_util.h"
#include "simulation/simulation_omc_assert.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"
#include "simulation/solver/spatialDistribution.h"
#include "simulation/solver/synchronous.h"

#include <string.h>

#include "PMSM_Plant_FMU_functions.h"


extern void PMSM_Plant_FMU_callExternalObjectDestructors(DATA *_data, threadData_t *threadData);
#if !defined(OMC_NUM_NONLINEAR_SYSTEMS) || OMC_NUM_NONLINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_LINEAR_SYSTEMS) || OMC_NUM_LINEAR_SYSTEMS>0
#endif
#if !defined(OMC_NUM_MIXED_SYSTEMS) || OMC_NUM_MIXED_SYSTEMS>0
#endif
#if !defined(OMC_NO_STATESELECTION)
extern void PMSM_Plant_FMU_initializeStateSets(int nStateSets, STATE_SET_DATA* statesetData, DATA *data);
#endif
extern int PMSM_Plant_FMU_functionAlgebraics(DATA *data, threadData_t *threadData);
extern int PMSM_Plant_FMU_function_storeDelayed(DATA *data, threadData_t *threadData);
extern int PMSM_Plant_FMU_function_storeSpatialDistribution(DATA *data, threadData_t *threadData);
extern int PMSM_Plant_FMU_function_initSpatialDistribution(DATA *data, threadData_t *threadData);
extern int PMSM_Plant_FMU_updateBoundVariableAttributes(DATA *data, threadData_t *threadData);
extern int PMSM_Plant_FMU_functionInitialEquations(DATA *data, threadData_t *threadData);
extern int PMSM_Plant_FMU_functionInitialEquations_lambda0(DATA *data, threadData_t *threadData);
extern int PMSM_Plant_FMU_functionRemovedInitialEquations(DATA *data, threadData_t *threadData);
extern int PMSM_Plant_FMU_updateBoundParameters(DATA *data, threadData_t *threadData);
extern int PMSM_Plant_FMU_checkForAsserts(DATA *data, threadData_t *threadData);
extern int PMSM_Plant_FMU_function_ZeroCrossingsEquations(DATA *data, threadData_t *threadData);
extern int PMSM_Plant_FMU_function_ZeroCrossings(DATA *data, threadData_t *threadData, double* gout);
extern int PMSM_Plant_FMU_function_updateRelations(DATA *data, threadData_t *threadData, int evalZeroCross);
extern const char* PMSM_Plant_FMU_zeroCrossingDescription(int i, int **out_EquationIndexes);
extern const char* PMSM_Plant_FMU_relationDescription(int i);
extern void PMSM_Plant_FMU_function_initSample(DATA *data, threadData_t *threadData);
extern int PMSM_Plant_FMU_initialAnalyticJacobianG(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int PMSM_Plant_FMU_initialAnalyticJacobianA(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int PMSM_Plant_FMU_initialAnalyticJacobianADJ(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int PMSM_Plant_FMU_initialAnalyticJacobianB(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int PMSM_Plant_FMU_initialAnalyticJacobianC(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int PMSM_Plant_FMU_initialAnalyticJacobianD(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int PMSM_Plant_FMU_initialAnalyticJacobianF(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int PMSM_Plant_FMU_initialAnalyticJacobianH(DATA* data, threadData_t *threadData, JACOBIAN *jacobian);
extern int PMSM_Plant_FMU_functionJacG_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int PMSM_Plant_FMU_functionJacA_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int PMSM_Plant_FMU_functionJacADJ_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int PMSM_Plant_FMU_functionJacB_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int PMSM_Plant_FMU_functionJacC_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int PMSM_Plant_FMU_functionJacD_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int PMSM_Plant_FMU_functionJacF_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern int PMSM_Plant_FMU_functionJacH_column(DATA* data, threadData_t *threadData, JACOBIAN *thisJacobian, JACOBIAN *parentJacobian);
extern const char* PMSM_Plant_FMU_linear_model_frame(void);
extern const char* PMSM_Plant_FMU_linear_model_datarecovery_frame(void);
extern int PMSM_Plant_FMU_mayer(DATA* data, modelica_real** res, short *);
extern int PMSM_Plant_FMU_lagrange(DATA* data, modelica_real** res, short *, short *);
extern int PMSM_Plant_FMU_getInputVarIndicesInOptimization(DATA* data, int* input_var_indices);
extern int PMSM_Plant_FMU_pickUpBoundsForInputsInOptimization(DATA* data, modelica_real* min, modelica_real* max, modelica_real*nominal, modelica_boolean *useNominal, char ** name, modelica_real * start, modelica_real * startTimeOpt);
extern int PMSM_Plant_FMU_setInputData(DATA *data, const modelica_boolean file);
extern int PMSM_Plant_FMU_getTimeGrid(DATA *data, modelica_integer * nsi, modelica_real**t);
extern void PMSM_Plant_FMU_function_initSynchronous(DATA * data, threadData_t *threadData);
extern void PMSM_Plant_FMU_function_updateSynchronous(DATA * data, threadData_t *threadData, long base_idx);
extern int PMSM_Plant_FMU_function_equationsSynchronous(DATA * data, threadData_t *threadData, long base_idx, long sub_idx);
extern void PMSM_Plant_FMU_read_simulation_info(SIMULATION_INFO* simulationData);
extern void PMSM_Plant_FMU_read_input_fmu(MODEL_DATA* modelData);
extern void PMSM_Plant_FMU_function_savePreSynchronous(DATA *data, threadData_t *threadData);
extern int PMSM_Plant_FMU_inputNames(DATA* data, char ** names);
extern int PMSM_Plant_FMU_dataReconciliationInputNames(DATA* data, char ** names);
extern int PMSM_Plant_FMU_dataReconciliationUnmeasuredVariables(DATA* data, char ** names);
extern int PMSM_Plant_FMU_initializeDAEmodeData(DATA *data, DAEMODE_DATA*);
extern int PMSM_Plant_FMU_functionLocalKnownVars(DATA* data, threadData_t* threadData);
extern int PMSM_Plant_FMU_symbolicInlineSystem(DATA* data, threadData_t* threadData);

#include "PMSM_Plant_FMU_literals.h"




#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#if defined(__cplusplus)
}
#endif

#endif /* !defined(PMSM_Plant_FMU__MODEL_H) */


