/*
 * \file Display_Functions.c
 * \copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or 
 * the company in which ordinary course of business you are acting and (ii) 
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by 
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the 
 * Software, and to permit third-parties to whom the Software is furnished to 
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE 
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */



/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include "Ifx_Types.h"
#include "Display_Functions.h"
#include "Display_Cfg_AppKitTft_TC387A.h"
#include "Display_Qspi_Init.h"
#include "conio_tft.h"
#include "touch.h"
#include "stdio.h"
/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/






TCONTROLMENU controlmenu;

extern TTOUCH_DRIVER touch_driver;
extern TCONIO_DRIVER conio_driver;

extern const TDISPLAYENTRY menulist[];
extern const TDISPLAYENTRY stdlist[];

TDISPLAY_GRAPHICS0 display_graphics0;

TDISPLAY display_stdout0;
TDISPLAYCOLOR displaycolor_stdout0;
TDISPLAY display_stdout1;
TDISPLAYCOLOR displaycolor_stdout1;
TDISPLAYBAR display_bar;
TDISPLAYBARCOLOR displaycolor_bar;
TDISPLAY display_menu;
TDISPLAYCOLOR displaycolor_menu;


volatile boolean tft_ready;
/******************************************************************************/
/*-------------------------Private Variables/Constants------------------------*/
/******************************************************************************/
const TCONIODLGENTRY conio_dialog_list[] =
{
    { KEYBOARDON, &keyboard },
};

const TCONIODMENTRY conio_displaymode_list[CONIO_MAXDISPLAYS] =
{
    { DISPLAYBAR, {(uint8 *) & display_bar, (uint8 *) & displaycolor_bar, TEXTMODE, WHITE, TERMINAL_MAXX, 1, 0, 0} },
    { DISPLAYMENU, {(uint8 *) & display_menu, (uint8 *) & displaycolor_menu, TEXTMODE, WHITE, TERMINAL_MAXX, TERMINAL_MAXY-1, 0, 0} },
    { DISPLAYSTDOUT0, {(uint8 *) & display_stdout0, (uint8 *) & displaycolor_stdout0, TEXTMODE, WHITE, TERMINAL_MAXX, TERMINAL_MAXY-1, 0, 0} },
    { DISPLAYSTDOUT1, {(uint8 *) & display_stdout1, (uint8 *) & displaycolor_stdout1, TEXTMODE, WHITE, TERMINAL_MAXX, TERMINAL_MAXY-1, 0, 0} },
    { DISPLAYGRAPHICS0, {(uint8 *) & display_graphics0, 0, GRAPHICMODE_16COLOR, WHITE, TERMINAL_MAXX, TERMINAL_MAXY, 0, 0} }
};
/******************************************************************************/
/*--------------------------Function Implementations--------------------------*/
/******************************************************************************/
/** \brief TFT application init
 *
 * This function initialises the TFT display via QSPI0 in master mode.
 */
void tft_appl_init (void)
{
    conio_driver.dialogmode = DIALOGOFF;
//    /* First we check that there is an alarm activ */
//    if (IfxPort_getPinState(RTC_ALARM_PIN_INPUT.pin.port,RTC_ALARM_PIN_INPUT.pin.pinIndex) == FALSE) conio_driver.dialogmode = SHOWALARMON;
//    else conio_driver.dialogmode = DIALOGOFF;
//    /* overwrite the dialog if time need to set, ignore any alarm */
//    if (RtcRunning == 0)
//    {
//    	conio_driver.dialogmode = SETTIMEON;
//    	/* call start of RTC calibration */
//        rtc_calibration();
//    }
    conio_driver.pmenulist = (TDISPLAYENTRY *)&menulist[0];
    conio_driver.pstdlist = (TDISPLAYENTRY *)&stdlist[0];

    tft_init ();                //initializes tft driver
    touch_init ();
    conio_init ((const pTCONIODMENTRY)conio_displaymode_list);

    controlmenu.cpusecondsdelta = 0.1f;
    tft_ready = TRUE;

}


void Dispaly_initDisplay(void)
{
	/* Initialize SPI interfaces */
	Display_initSpiModules();

	IfxCpu_enableInterrupts();
	/* Initialize TFT Display */
	tft_appl_init();
	/* Initialize the background light */
	IfxPort_setPinModeOutput(&MODULE_P15, 0, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
	IfxPort_setPinHigh(&MODULE_P15, 0);
	IfxCpu_disableInterrupts();
}
