"""
motor_block1.py
==============

PMSMMotorBlock — Permanent Magnet Synchronous Motor model.

State vector:  x = [id, iq, ω, θ]    (4 states)

Electrical equations (dq frame, rotor-oriented):
    did/dt = (vd - Rs·id + Lq·ω·iq) / Ld
    diq/dt = (vq - Rs·iq - Ld·ω·id - ψ_pm·ω) / Lq

Mechanical equation:
    dω/dt  = (Te - B·ω - T_load) / J       Te = 1.5 · ψ_pm · iq
    dθ/dt  = ω

Inputs (two VectorSignal ports):
    port 0 — [v_alpha, v_beta]   (stator voltage, αβ frame)
    port 1 — [T_load]            (load torque)

Output VectorSignal (5 elements):
    [ia, ib, ic, ω, θ]

    ia, ib, ic are reconstructed three-phase currents via inverse Park:
        ia = id·cos(θ) − iq·sin(θ)
        ib = id·cos(θ − 2π/3) − iq·sin(θ − 2π/3)
        ic = id·cos(θ + 2π/3) − iq·sin(θ + 2π/3)

C backend interface:
    Input struct  — double v_alpha, v_beta, T_load
    Output struct — double ia, ib, ic, omega, theta
    Function      — pmsm_motor_compute(InputSignals*, OutputSignals*)

Parameters
----------
    Rs    : float  — Stator resistance [Ω]        default 0.5
    Ld    : float  — d-axis inductance [H]         default 0.002
    Lq    : float  — q-axis inductance [H]         default 0.002
    psi_pm: float  — Permanent magnet flux [Wb]    default 0.3
    J     : float  — Rotor inertia [kg·m²]         default 0.001
    B     : float  — Viscous friction [N·m·s/rad]  default 0.001

Example
-------
    from pmsm_blocks import PMSMMotorBlock

    motor = PMSMMotorBlock("motor", Rs=0.5, Ld=0.002, Lq=0.002,
                           psi_pm=0.3, J=0.001, B=0.001)
    inv_park >> motor   # port 0: [v_alpha, v_beta]
    load     >> motor   # port 1: [T_load]
    motor    >> sink
"""

import sys
import numpy as np
from pathlib import Path
from typing import List, Optional

# ------------------------------------------------------------------
# Locate embedsim regardless of working directory
# ------------------------------------------------------------------
from ._path_utils import setup_embedsim_path
setup_embedsim_path()

from embedsim.code_generator import SimBlockBase
from embedsim.core_blocks import VectorSignal

_TWO_PI      = 2.0 * np.pi
_SQRT3       = np.sqrt(3.0)
_TWO_THIRDS  = 2.0 / 3.0
_ONE_THIRD   = 1.0 / 3.0
_PI2_3       = _TWO_PI / 3.0   # 2π/3


# ==============================================================================
# PMSMMotorBlock
# ==============================================================================

class PMSMMotorBlock(SimBlockBase):
    """
    PMSM motor model — dual Python / C backend.

    State (internal, NOT a VectorSignal):
        [id, iq, ω, θ]

    Output VectorSignal:
        [ia, ib, ic, ω, θ]   (5 elements, float32 by default)

    Supported ODE solvers (via EmbedSim integration):
        Euler   — integrate_state(dt, 'euler')
        RK4     — get_derivative() + external RK4 in EmbedSim engine

    C backend stub (generated by CodeGenEnd.generate_pyx_stub):
        pmsm_motor.h / pmsm_motor_wrapper.pyx / pmsm_motor_simblock.py
    """

    # -- construction ----------------------------------------------------------

    def __init__(
        self,
        name: str,
        Rs:     float = 0.5,
        Ld:     float = 0.002,
        Lq:     float = 0.002,
        psi_pm: float = 0.3,
        J:      float = 0.001,
        B:      float = 0.001,
        initial_state: Optional[List[float]] = None,
        use_c_backend: bool = False,
        dtype = None,
    ) -> None:
        """
        Construct the PMSM motor block.

        Args:
            name:          Block identifier (used in plots and C code)
            Rs:            Stator resistance [Ω]
            Ld:            d-axis inductance [H]
            Lq:            q-axis inductance [H]
            psi_pm:        Permanent-magnet flux linkage [Wb]
            J:             Rotor moment of inertia [kg·m²]
            B:             Viscous friction coefficient [N·m·s/rad]
            initial_state: [id0, iq0, ω0, θ0].  If None → all zeros.
            use_c_backend: False = Python, True = compiled C via Cython
            dtype:         Array dtype (default: float32 from embedsim)
        """
        super().__init__(name, use_c_backend=use_c_backend, dtype=dtype)

        # Motor parameters
        self.Rs:     float = float(Rs)
        self.Ld:     float = float(Ld)
        self.Lq:     float = float(Lq)
        self.psi_pm: float = float(psi_pm)
        self.J:      float = float(J)
        self.B:      float = float(B)

        # ODE state [id, iq, ω, θ]
        if initial_state is not None:
            self.state: np.ndarray = np.array(initial_state, dtype=np.float64)
        else:
            self.state = np.zeros(4, dtype=np.float64)

        # EmbedSim integration hooks
        self.is_dynamic:  bool        = True
        self.vector_size: int         = 5   # output size: [ia, ib, ic, ω, θ]
        self.derivative:  np.ndarray  = np.zeros(4, dtype=np.float64)

        # RK4 staging arrays (allocated once)
        self.k1 = np.zeros(4, dtype=np.float64)
        self.k2 = np.zeros(4, dtype=np.float64)
        self.k3 = np.zeros(4, dtype=np.float64)
        self.k4 = np.zeros(4, dtype=np.float64)

        # Cached voltages / load for derivative call (set in compute)
        self._dt:   float = 0.0001   # updated on first compute; passed to C wrapper
        self._vd:   float = 0.0
        self._vq:   float = 0.0
        self._load: float = 0.0

        if use_c_backend:
            self._load_wrapper()

    # -- Python backend --------------------------------------------------------

    def compute_py(
        self,
        t: float,
        dt: float,
        input_values: Optional[List[VectorSignal]] = None,
    ) -> VectorSignal:
        """
        Compute one simulation step — pure Python path.

        Reads αβ voltages from port 0 and load torque from port 1.
        Updates self._vd, self._vq, self._load for get_derivative().
        Returns VectorSignal([ia, ib, ic, ω, θ]).
        """
        # -- Unpack inputs -------------------------------------------------------
        if input_values and len(input_values) >= 1 and len(input_values[0].value) >= 2:
            v_alpha = float(input_values[0].value[0])
            v_beta  = float(input_values[0].value[1])
        else:
            v_alpha = v_beta = 0.0

        if input_values and len(input_values) >= 2 and len(input_values[1].value) >= 1:
            self._load = float(input_values[1].value[0])
        else:
            self._load = 0.0

        # -- Current state -------------------------------------------------------
        id_     = self.state[0]
        iq      = self.state[1]
        omega   = self.state[2]
        theta   = self.state[3]

        # -- αβ → dq (Park transform) -------------------------------------------
        cos_t = np.cos(theta)
        sin_t = np.sin(theta)
        self._vd = float( v_alpha * cos_t + v_beta * sin_t)
        self._vq = float(-v_alpha * sin_t + v_beta * cos_t)

        # -- Three-phase currents (inverse Park) ---------------------------------
        cos_m120 = np.cos(theta - _PI2_3)
        sin_m120 = np.sin(theta - _PI2_3)
        cos_p120 = np.cos(theta + _PI2_3)
        sin_p120 = np.sin(theta + _PI2_3)

        ia = id_ * cos_t    - iq * sin_t
        ib = id_ * cos_m120 - iq * sin_m120
        ic = id_ * cos_p120 - iq * sin_p120

        # -- Update derivative for ODE integrator --------------------------------
        self.derivative = self._f(self.state)

        # -- Output --------------------------------------------------------------
        out = np.array([ia, ib, ic, omega, theta], dtype=np.float64)
        self.output = VectorSignal(out, self.name, dtype=self.dtype)
        return self.output

    # -- ODE hooks (used by EmbedSim engine) -----------------------------------

    def get_derivative(
        self,
        t: float,
        input_values: Optional[List[VectorSignal]] = None,
    ) -> np.ndarray:
        """
        Return dx/dt at *current* state.
        Called by RK4 integrator with intermediate states.
        """
        return self._f(self.state)

    def integrate_state(self, dt: float, solver: str = "euler") -> None:
        """Advance internal ODE state by dt (Euler only; RK4 handled by engine)."""
        if solver == "euler":
            self.state = self.state + self.derivative * dt
            self.state[3] = self.state[3] % _TWO_PI   # wrap θ ∈ [0, 2π)

    # -- C backend -------------------------------------------------------------

    def compute_c(
        self,
        t: float,
        dt: float,
        input_values: Optional[List[VectorSignal]] = None,
    ) -> VectorSignal:
        """
        C-backend compute — outputs from current Python state.

        The C wrapper's internal integration is NOT used here.
        EmbedSim's external RK4 controls state integration by calling
        get_derivative() and integrate_state().  compute_c only:
          1. Unpacks inputs (v_alpha, v_beta, T_load)
          2. Transforms to dq frame and stores _vd/_vq/_load for get_derivative
          3. Computes three-phase output currents from self.state
          4. Returns the 5-element output vector

        This is identical to compute_py — the C extension is used in
        get_derivative() for fast ODE evaluation at RK4 substeps.
        """
        # Unpack inputs
        if input_values and len(input_values) >= 1 and len(input_values[0].value) >= 2:
            v_alpha = float(input_values[0].value[0])
            v_beta  = float(input_values[0].value[1])
        else:
            v_alpha = v_beta = 0.0

        if input_values and len(input_values) >= 2 and len(input_values[1].value) >= 1:
            self._load = float(input_values[1].value[0])
        else:
            self._load = 0.0

        # Current state
        id_   = self.state[0]
        iq    = self.state[1]
        omega = self.state[2]
        theta = self.state[3]

        # αβ → dq (Park transform) — store for get_derivative()
        cos_t    = np.cos(theta)
        sin_t    = np.sin(theta)
        self._vd = float( v_alpha * cos_t + v_beta * sin_t)
        self._vq = float(-v_alpha * sin_t + v_beta * cos_t)
        self._dt = dt

        # Three-phase currents (inverse Park)
        cos_m120 = np.cos(theta - _PI2_3)
        sin_m120 = np.sin(theta - _PI2_3)
        cos_p120 = np.cos(theta + _PI2_3)
        sin_p120 = np.sin(theta + _PI2_3)

        ia = id_ * cos_t    - iq * sin_t
        ib = id_ * cos_m120 - iq * sin_m120
        ic = id_ * cos_p120 - iq * sin_p120

        # Cache derivative for Euler fallback
        self.derivative = self._f(self.state)

        out = np.array([ia, ib, ic, omega, theta], dtype=np.float64)
        self.output = VectorSignal(out, self.name, dtype=self.dtype)
        return self.output

    def _load_wrapper(self) -> None:
        """Import compiled pmsm_motor_wrapper Cython module."""
        try:
            from pmsm_motor_wrapper import PmsmMotorWrapper   # noqa: F401
            self._wrapper = PmsmMotorWrapper()
            # Push current motor parameters to the C side
            self._wrapper.set_parameters(
                self.Rs, self.Ld, self.Lq, self.psi_pm, self.J, self.B,
                dt=self._dt
            )

        except ImportError:
            raise ImportError(
                "Cython wrapper 'pmsm_motor_wrapper' not found.\n"
                "Generate and compile it:\n"
                "  1. Run generate_pmsm_motor_c_code() in codegen_pmsm.py\n"
                "  2. python setup_pmsm_motor.py build_ext --inplace"
            )

    # -- Private helpers -------------------------------------------------------

    def _f(self, x: np.ndarray) -> np.ndarray:
        """
        PMSM ODE right-hand side  dx/dt = f(x).

        Uses self._vd, self._vq, self._load which are set by compute_py()
        before the integrator calls get_derivative().
        """
        id_   = x[0]
        iq    = x[1]
        omega = x[2]

        # Electrical dynamics
        did_dt = (self._vd - self.Rs * id_   + self.Lq * omega * iq) / self.Ld
        diq_dt = (self._vq - self.Rs * iq    - self.Ld * omega * id_
                  - self.psi_pm * omega) / self.Lq

        # Electromagnetic torque & mechanical dynamics
        Te     = 1.5 * self.psi_pm * iq
        dw_dt  = (Te - self.B * omega - self._load) / self.J
        dth_dt = omega

        return np.array([did_dt, diq_dt, dw_dt, dth_dt], dtype=np.float64)

    # -- Repr ------------------------------------------------------------------

    def __repr__(self) -> str:
        be = "C" if self.use_c_backend else "Python"
        return (
            f"PMSMMotorBlock('{self.name}', backend={be}, "
            f"Rs={self.Rs}, Ld={self.Ld}, Lq={self.Lq}, "
            f"ψ_pm={self.psi_pm}, J={self.J}, B={self.B})"
        )
