/**
 * @file PmsmFoc_EMotorDrive_v_3_1.h
 * @brief Header file for PMSM FOC EMotorDrive version 3.1.
 * @ingroup pmsm_foc_configuration
 * @version 1.0
 * @date 2019
 * @copyright Copyright (c) 2019 Infineon Technologies AG. All rights reserved.
 *
 * @details
 * This file contains macro definitions, configuration parameters, and constants
 * for the PMSM FOC eMotorDrive version 3.1. It includes definitions for inverter
 * settings, phase current sensing, DC-link voltage sensing, and BEMF voltage sensing.
 *
 *                            IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */

#ifndef PPMSM_FOC_EMOTORDRIVE_V_3_1_H_
#define PMSM_FOC_EMOTORDRIVE_V_3_1_H_
/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

/**
 * @brief Include user configuration for PMSM FOC applications.
 */
#include "PmsmFoc_UserConfig.h"

/******************************************************************************/
/*--------------------------------Macros--------------------------------------*/
/******************************************************************************/

#if (INVERTERCARD_TYPE == EMOTOR_DRIVE_V_3_1)

/**
 * @defgroup Inverter_Parameters Inverter Configuration Parameters
 * @brief Parameters specific to the eMotorDrive version 3.1 inverter.
 * @{
 */

/** @brief Define the hardware inverter VDC link voltage value in volts. */
#define USER_INVERTER_VDC_LINK_V                          (12.0f)

/** @brief Define the GTM PWM Switching Frequency value in Hz. */
#define USER_INVERTER_PWM_FREQ_HZ                         (20000U)

/** @brief Define the dead time for rising (left) in seconds. */
#define USER_INVERTER_PWM_RISING_DEADTIME_SEC             (0.0000010f)

/** @brief Define the dead time for falling (right) in seconds. */
#define USER_INVERTER_PWM_FAILING_DEADTIME_SEC            (0.0000010f)

/** @brief Define the initial bootstrap pre-charging time in milliseconds. */
#define USER_INVERTER_BOOTSTRAP_PRECHARGE_TIME_MS         (20U)

/** @} */

/**
 * @defgroup Phase_Current_Sensing Phase Current and DC-Link Current Sensing
 * @brief Macros for phase current sensing and DC-link current sensing.
 * @{
 */

/** @brief Define the phase shunt resistor value in ohms. */
#define USER_INVERTER_THREE_PHASE_SHUNT_OHM               (0.01f)

/** @brief Define the low-side DC link shunt current resistor value in ohms. */
#define USER_INVERTER_DC_LOW_SIDE_SHUNT_OHM               (0.01f)

/** @brief Define the high-side DC link shunt current resistor value in ohms. */
#define USER_INVERTER_DC_HIGH_SIDE_SHUNT_OHM              (0.01f)

/** @brief Define the maximum ADC voltage for EVADC in volts. */
#define USER_INVERTER_MAX_ADC_VDD_V                       (5.0f)

/** @brief Define the amplifier gain value for phase current sensing. */
#define USER_INVERTER_PHASECURSENSE_AMPLIFIER_GAIN        (30.81)

/** @brief Define the maximum phase current value. */
#define USER_INVERTER_I_MAX_A                             ((USER_INVERTER_MAX_ADC_VDD_V / \
                                                           (USER_INVERTER_THREE_PHASE_SHUNT_OHM * \
                                                           USER_INVERTER_PHASECURSENSE_AMPLIFIER_GAIN)) / 2)

/** @brief Define the minimum phase current value. */
#define USER_INVERTER_PHASECURSENSE_I_MIN                 (-USER_INVERTER_I_MAX_A)

/** @brief Define the maximum phase current value. */
#define USER_INVERTER_PHASECURSENSE_I_MAX                 (USER_INVERTER_I_MAX_A)

/** @brief Define the phase current sense gain value. */
#define USER_INVERTER_PHASECURSENSE_I_GAIN                (-(USER_INVERTER_MAX_ADC_VDD_V / \
                                                           (4096 * USER_INVERTER_PHASECURSENSE_AMPLIFIER_GAIN * \
                                                           USER_INVERTER_THREE_PHASE_SHUNT_OHM)))

/** @brief Define the phase current sense offset value. */
#define USER_INVERTER_PHASECURSENSE_I_OFFSET              (2.5 / (USER_INVERTER_PHASECURSENSE_AMPLIFIER_GAIN * \
                                                           USER_INVERTER_THREE_PHASE_SHUNT_OHM))

/** @brief Define the phase current sense amplifier reference voltage gain value. */
#define USER_INVERTER_PHASECURSENSE_V_GAIN                (USER_INVERTER_MAX_ADC_VDD_V / 4096)

/** @brief Define the phase current sense amplifier reference voltage offset value. */
#define USER_INVERTER_PHASECURSENSE_V_OFFSET              (0.0)

/** @brief Define the nominal offset value for the phase current sense amplifier. */
#define USER_INVERTER_PHASECURSENSE_V_OFFSET_NOM          (2048)

/** @brief Define the refill trigger value for phase current sensing. */
#define USER_INVERTER_PHASECURSENSE_REFILL_TRIG           ((1 << IFX_EVADC_G_Q_QINR_RF_OFF) | \
                                                           (1 << IFX_EVADC_G_Q_Q0R_EXTR_OFF))

/** @brief Define the number of loops for current sensing calibration. */
#define USER_INVERTER_PHASECURSENSE_CALIBRATION_COUNT     (2048)

/** @} */

/**
 * @defgroup DC_Link_Voltage_Sensing DC-Link Voltage and Phase Voltage Sensing
 * @brief Macros for DC-link voltage and phase voltage sensing.
 * @{
 */

/** @brief Define the R1/(R2+R1) ratio for DC link MCU ADC. */
#define USER_INVERTER_DC_LINK_DIVIDER_RATIO               (5.6f / (5.6f + 56.0f))

/** @brief Define the DC-link voltage sensing scaled gain value. */
#define USER_INVERTER_DCLINVOLTAGESENSE_GAIN              (USER_INVERTER_MAX_ADC_VDD_V / \
                                                           (4096 * USER_INVERTER_DC_LINK_DIVIDER_RATIO))

/** @brief Define the initial offset for DC-link voltage sensing. */
#define USER_INVERTER_DCLINVOLTAGESENSE_OFFSET            (0.0)

/** @brief Define the nominal offset for DC-link voltage sensing. */
#define USER_INVERTER_DCLINVOLTAGESENSE_OFFSET_NOM        (0)

/** @brief Define the R1/(R2+R1) ratio for BEMF voltage sensing circuit. */
#define USER_INVERTER_BEMF_DIVIDER_RATIO                  (5.6f / (5.6f + 56.0f))

/** @brief Define the phase voltage sensing scaled gain value. */
#define USER_INVERTER_BEMFSENSE_GAIN                      (USER_INVERTER_MAX_ADC_VDD_V / \
                                                           (4096 * USER_INVERTER_BEMF_DIVIDER_RATIO))

/** @brief Define the initial offset for phase voltage sensing. */
#define USER_INVERTER_BEMFSENSE_OFFSET                    (0.0)

/** @brief Define the nominal offset for phase voltage sensing. */
#define USER_INVERTER_BEMFSENSE_OFFSET_NOM                (0)

/** @} */

/**
 * @defgroup High_Side_Current_Sensing High-Side Current Sensing
 * @brief Macros for high-side DC-link current sensing.
 * @{
 */

/** @brief Define the default gain value for high-side DC-link current sensing. */
#define USER_INVERTER_HS_DCLINK_CUR_SENSE_DEFAULT_GAIN    (200.0f)

/** @brief Define the scaled gain value for high-side DC-link current sensing. */
#define USER_INVERTER_HS_DCLINK_CUR_SENSE_GAIN            ((USER_INVERTER_MAX_ADC_VDD_V / \
                                                           (4096 * USER_INVERTER_HS_DCLINK_CUR_SENSE_DEFAULT_GAIN * \
                                                           USER_INVERTER_DC_HIGH_SIDE_SHUNT_OHM)))

/** @brief Define the maximum DC-link current value. */
#define USER_INVERTER_HS_I_MAX_A                          ((USER_INVERTER_MAX_ADC_VDD_V / \
                                                           (USER_INVERTER_DC_HIGH_SIDE_SHUNT_OHM * \
                                                           USER_INVERTER_HS_DCLINK_CUR_SENSE_DEFAULT_GAIN)) / 2)

/** @brief Define the initial offset for high-side DC-link current sensing. */
#define USER_INVERTER_HS_DCLINK_CUR_SENSE_OFFSET          (0.0)

/** @brief Define the nominal offset for high-side DC-link current sensing. */
#define USER_INVERTER_HS_DCLINK_CUR_SENSE_OFFSET_NOM      (0.0)

/** @brief Define the minimum value for high-side DC-link current sensing. */
#define USER_INVERTER_HS_DCLINK_CUR_SENSE_I_MIN           (-USER_INVERTER_HS_I_MAX_A)

/** @brief Define the maximum value for high-side DC-link current sensing. */
#define USER_INVERTER_HS_DCLINK_CUR_SENSE_I_MAX           (USER_INVERTER_HS_I_MAX_A)

/** @} */

#endif /* INVERTERCARD_TYPE == EMOTOR_DRIVE_V_3_1 */

#endif /* PMSM_FOC_EMOTORDRIVE_V_3_1_H_ */
