################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C++M_SRCS := 
C++_SRCS := 
CCM_SRCS := 
CC_SRCS := 
CPP_SRCS := 
CXXM_SRCS := 
CXX_SRCS := 
C_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
O_SRCS := 
SRC_SRCS := 
C++M_DEPS := 
C++_DEPS := 
CCM_DEPS := 
CC_DEPS := 
COMPILED_SRCS := 
CPP_DEPS := 
CXXM_DEPS := 
CXX_DEPS := 
C_DEPS := 
C_UPPER_DEPS := 
EXECUTABLES := 
OBJS := 
SECONDARY_SIZE := 

# Every subdirectory with source files must be described here
SUBDIRS := \
AppSw/Display/App \
AppSw/Display/Interrupts \
AppSw/Display/MCUInit \
AppSw/OSTasks \
AppSw/OneEye \
AppSw/PmsmFoc/ControlModules \
AppSw/PmsmFoc/EmbedSim \
AppSw/PmsmFoc/ExtDevInit \
AppSw/PmsmFoc/Interrupts \
AppSw/PmsmFoc/Libraries/Math \
AppSw/PmsmFoc/Libraries/MotorDrive \
AppSw/PmsmFoc/MCUInit \
AppSw/PmsmFoc/MidSys \
Configurations/Debug \
Configurations \
. \
Libraries/ExtDevDrivers/TLE9180/Tricore \
Libraries/ExtDevDrivers/TLF35584/Tricore \
Libraries/Infra/Platform/Tricore/Compilers \
Libraries/Infra/Ssw/TC38A/Tricore \
Libraries/Service/CpuGeneric/If \
Libraries/Service/CpuGeneric/StdIf \
Libraries/Service/CpuGeneric/SysSe/Bsp \
Libraries/Service/CpuGeneric/SysSe/Comm \
Libraries/Service/CpuGeneric/SysSe/Math \
Libraries/iLLD/TC38A/Tricore/Asclin/Asc \
Libraries/iLLD/TC38A/Tricore/Asclin/Std \
Libraries/iLLD/TC38A/Tricore/Cpu/Irq \
Libraries/iLLD/TC38A/Tricore/Cpu/Std \
Libraries/iLLD/TC38A/Tricore/Cpu/Trap \
Libraries/iLLD/TC38A/Tricore/Dma/Dma \
Libraries/iLLD/TC38A/Tricore/Dma/Std \
Libraries/iLLD/TC38A/Tricore/Edsadc/Edsadc \
Libraries/iLLD/TC38A/Tricore/Edsadc/Std \
Libraries/iLLD/TC38A/Tricore/Evadc/Adc \
Libraries/iLLD/TC38A/Tricore/Evadc/Std \
Libraries/iLLD/TC38A/Tricore/Gpt12/IncrEnc \
Libraries/iLLD/TC38A/Tricore/Gpt12/Std \
Libraries/iLLD/TC38A/Tricore/Gtm/Std \
Libraries/iLLD/TC38A/Tricore/Gtm/Tom/PwmHl \
Libraries/iLLD/TC38A/Tricore/Gtm/Tom/Timer \
Libraries/iLLD/TC38A/Tricore/Gtm/Trig \
Libraries/iLLD/TC38A/Tricore/Mtu/Std \
Libraries/iLLD/TC38A/Tricore/Pms/Std \
Libraries/iLLD/TC38A/Tricore/Port/Std \
Libraries/iLLD/TC38A/Tricore/Qspi/SpiMaster \
Libraries/iLLD/TC38A/Tricore/Qspi/Std \
Libraries/iLLD/TC38A/Tricore/Scu/Std \
Libraries/iLLD/TC38A/Tricore/Src/Std \
Libraries/iLLD/TC38A/Tricore/Stm/Std \
Libraries/iLLD/TC38A/Tricore/_Impl \
Libraries/iLLD/TC38A/Tricore/_Lib/DataHandling \
Libraries/iLLD/TC38A/Tricore/_PinMap \
Libraries/oneeye_lib/arduino \
Libraries/oneeye_lib/aurix/illd \
Libraries/oneeye_lib/cy/pdl \
Libraries/oneeye_lib \
Libraries/oneeye_lib/xmc/xmcdaveapp \
Libraries/oneeye_lib/xmc/xmclib \
OS/FreeRTOS \
OS/FreeRTOS/portable/MemMang \
OS/FreeRTOS/portable/TriCore \

