/* Additional record code for ThreePhaseMotor generated by the OpenModelica Compiler OpenModelica v1.25.7 (64-bit). */

#include "omc_simulation_settings.h"
#include "meta/meta_modelica.h"
#include "ThreePhaseMotor_functions.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifdef __cplusplus
}
#endif

