/**********************************************************************************************************************
 * \file svpwm.h
 *
 * \copyright Copyright (C) EmbedSim 2024
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) EmbedSim. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef EMBEDSIM_MIDSYS_SVPWM_H_
#define EMBEDSIM_MIDSYS_SVPWM_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Sys_Types.h"
#include "Matrix.h"
#include <math.h>

/* MISRA C 2012 Rule 21.1: math.h is permitted for floating-point utilities */

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/** \addtogroup svpwm_constants
 * \{ */

#ifndef SVM_PI_OVER_2_F
#define SVM_PI_OVER_2_F          (1.57079632679f)  /**< π/2 = 90 degrees */
#endif

#ifndef SVM_SQRT3_F
#define SVM_SQRT3_F              (1.73205080757f)  /**< √3 = 1.73205080757 */
#endif

#ifndef SVM_PI_OVER_6_F
#define SVM_PI_OVER_6_F          (0.5235987756f)   /**< π/6 = 30 degrees */
#endif

#ifndef SVM_PI_OVER_3_F
#define SVM_PI_OVER_3_F          (1.0471975512f)   /**< π/3 = 60 degrees */
#endif

#ifndef SVM_2PI_OVER_3_F
#define SVM_2PI_OVER_3_F         (2.0943951024f)   /**< 2π/3 = 120 degrees */
#endif

#ifndef SVM_PI_F
#define SVM_PI_F                 (3.14159265359f)  /**< π = 180 degrees */
#endif

#ifndef SVM_4PI_OVER_3_F
#define SVM_4PI_OVER_3_F         (4.18879020479f)  /**< 4π/3 = 240 degrees */
#endif

#ifndef SVM_5PI_OVER_3_F
#define SVM_5PI_OVER_3_F         (5.23598775598f)  /**< 5π/3 = 300 degrees */
#endif

#ifndef SVM_2PI_F
#define SVM_2PI_F                (6.28318530718f)  /**< 2π = 360 degrees */
#endif

/** \} */

/** \def SVM_SQRT3_OVER_2_F
 * \brief sqrt(3)/2 = 0.86602540378 as float
 */
#define SVM_SQRT3_OVER_2_F       (0.86602540378f)

/** \def Q31_SCALE_F
 * \brief Scaling factor for Q31 to float conversion (from Matrix.c)
 */
#define Q31_SCALE_F              (2147483648.0f)

/** \def Q31_ONE
 * \brief Q31 fixed-point representation of 1.0 (from Matrix.c)
 */
#define Q31_ONE                  ((int32_T)0x7FFFFFFF)

/** \def Q31_ZERO
 * \brief Q31 fixed-point representation of 0.0
 */
#define Q31_ZERO                 ((int32_T)0x00000000)


/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
/** \addtogroup svpwm_enums
 * \{ */

/**
 * \enum SVM_Sector_Type
 * \brief SVM sectors (I through VI)
 */
typedef enum
{
    SVM_SECTOR_I = 0U,     /**< Sector I: 0° to 60° */
    SVM_SECTOR_II = 1U,    /**< Sector II: 60° to 120° */
    SVM_SECTOR_III = 2U,   /**< Sector III: 120° to 180° */
    SVM_SECTOR_IV = 3U,    /**< Sector IV: 180° to 240° */
    SVM_SECTOR_V = 4U,     /**< Sector V: 240° to 300° */
    SVM_SECTOR_VI = 5U     /**< Sector VI: 300° to 360° */
} SVM_Sector_Type;

/** \} */

/**
 * \struct SVM_DutyCycle_Type
 * \brief Duty cycles for three phases (as Q31 values in [0, Q31_ONE])
 *
 * Q31_ONE (0x7FFFFFFF) represents 100% duty cycle
 * Q31_ZERO (0x00000000) represents 0% duty cycle
 *
 * The duty cycles represent the "on" time for the high-side switches
 * in each phase, normalized to the switching period.
 */
typedef struct
{
    MatrixElement ta;       /**< Duty cycle for phase A (Q31 format, 0 to Q31_ONE) */
    MatrixElement tb;       /**< Duty cycle for phase B (Q31 format, 0 to Q31_ONE) */
    MatrixElement tc;       /**< Duty cycle for phase C (Q31 format, 0 to Q31_ONE) */
    SVM_Sector_Type sector; /**< Sector number for information */
} SVM_DutyCycle_Type;


/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
/* None */


/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
/** \addtogroup svpwm_api
 * \{ */

/**
 * \brief Calculate SVM duty cycles from modulation index and angle
 *
 * This function implements Space Vector Modulation according to Table 9.3
 * and generates duty cycles for symmetric switching (T0 = T7).
 *
 * \param[in]  modulation_index  Modulation index m' (0.0 to 1.0, float)
 * \param[in]  angle_rad         Angle ω·t in radians (0 to 2π, float)
 * \param[out] duty              Pointer to structure to store duty cycles
 * \return MatrixStatus_Type (MATRIX_SUCCESS on success, error code otherwise)
 */
extern MatrixStatus_Type SVM_CalculateDutyCycle(
    const MatrixFloat modulation_index,
    const MatrixFloat angle_rad,
    SVM_DutyCycle_Type * const duty);

/**
 * \brief Calculate SVM sector from dq voltage components
 *
 * Determines the sector based on the dq voltage vector components
 * according to the conditions in the text.
 *
 * \param[in]  vd     d-axis voltage (Q31 format, range [-Q31_ONE, Q31_ONE])
 * \param[in]  vq     q-axis voltage (Q31 format, range [-Q31_ONE, Q31_ONE])
 * \param[out] sector Pointer to store the sector
 * \return MatrixStatus_Type (MATRIX_SUCCESS on success, error code otherwise)
 */
extern MatrixStatus_Type SVM_GetSectorFromDQ(
    const MatrixElement vd,
    const MatrixElement vq,
    SVM_Sector_Type * const sector);

/**
 * \brief Convert duty cycles to PWM compare values
 *
 * Converts the normalized duty cycles to timer compare values
 * for center-aligned PWM generation.
 *
 * \param[in]  duty         Duty cycle structure (Q31 format)
 * \param[in]  timer_period Timer period in ticks (must be > 0)
 * \param[out] compare_a    Compare value for phase A (0 to timer_period)
 * \param[out] compare_b    Compare value for phase B (0 to timer_period)
 * \param[out] compare_c    Compare value for phase C (0 to timer_period)
 * \return MatrixStatus_Type (MATRIX_SUCCESS on success, error code otherwise)
 */
extern MatrixStatus_Type SVM_GetCompareValues(
    const SVM_DutyCycle_Type * const duty,
    const uint32_T timer_period,
    uint32_T * const compare_a,
    uint32_T * const compare_b,
    uint32_T * const compare_c);

/**
 * \brief Get phase duty cycles as floating-point values
 *
 * Utility function to convert the Q31 duty cycles back to float
 * for monitoring or debugging purposes.
 *
 * \param[in]  duty Duty cycle structure (Q31 format)
 * \param[out] ta   Phase A duty cycle as float [0.0, 1.0]
 * \param[out] tb   Phase B duty cycle as float [0.0, 1.0]
 * \param[out] tc   Phase C duty cycle as float [0.0, 1.0]
 */
extern void SVM_GetDutyCyclesFloat(
    const SVM_DutyCycle_Type * const duty,
    MatrixFloat * const ta,
    MatrixFloat * const tb,
    MatrixFloat * const tc);


#endif /* EMBEDSIM_MIDSYS_SVPWM_H_ */
