/**********************************************************************************************************************
 * \file svpwm.c
 *
 * \copyright Copyright (C) EmbedSim 2024
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) EmbedSim. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "svpwm.h"
#include <math.h>
#include <stddef.h>


/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
/* Mathematical constants */
#define SVM_HALF_F               (0.5f)            /**< 1/2 */
#define SVM_ONE_F                (1.0f)            /**< 1.0 */
#define SVM_ZERO_F               (0.0f)            /**< 0.0 */


/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* None */


/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
/* None */


/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
/**
 * \brief Determine sector from angle
 *
 * \param[in] angle_rad Angle in radians
 * \return Sector number (0-5)
 */
static SVM_Sector_Type SVM_GetSectorFromAngle(const MatrixFloat angle_rad);

/**
 * \brief Calculate normalized times T1 and T2
 *
 * \param[in]  sector     Sector number
 * \param[in]  angle_rad  Angle in radians
 * \param[in]  m          Modulation index
 * \param[out] t1         Pointer to store T1 value
 * \param[out] t2         Pointer to store T2 value
 */
static void SVM_CalculateTimes(
    const SVM_Sector_Type sector,
    const MatrixFloat angle_rad,
    const MatrixFloat m,
    MatrixFloat * const t1,
    MatrixFloat * const t2);

/**
 * \brief Clamp float value to [0.0, 1.0] range
 *
 * \param[in] value Input value
 * \return Clamped value
 */
static MatrixFloat SVM_ClampFloat(const MatrixFloat value);


/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
static MatrixFloat SVM_ClampFloat(const MatrixFloat value)
{
    MatrixFloat result;

    result = value;

    if (result < SVM_ZERO_F)
    {
        result = SVM_ZERO_F;
    }
    else if (result > SVM_ONE_F)
    {
        result = SVM_ONE_F;
    }
    else
    {
        /* No action - value already in range */
    }

    return result;
}

static SVM_Sector_Type SVM_GetSectorFromAngle(const MatrixFloat angle_rad)
{
    MatrixFloat angle_normalized;
    SVM_Sector_Type sector;

    /* Normalize angle to [0, 2π) */
    angle_normalized = angle_rad;

    while (angle_normalized < SVM_ZERO_F)
    {
        angle_normalized += SVM_2PI_F;
    }

    while (angle_normalized >= SVM_2PI_F)
    {
        angle_normalized -= SVM_2PI_F;
    }

    /* Determine sector based on angle */
    if (angle_normalized < SVM_PI_OVER_3_F)
    {
        sector = SVM_SECTOR_I;
    }
    else if (angle_normalized < SVM_2PI_OVER_3_F)
    {
        sector = SVM_SECTOR_II;
    }
    else if (angle_normalized < SVM_PI_F)
    {
        sector = SVM_SECTOR_III;
    }
    else if (angle_normalized < SVM_4PI_OVER_3_F)
    {
        sector = SVM_SECTOR_IV;
    }
    else if (angle_normalized < SVM_5PI_OVER_3_F)
    {
        sector = SVM_SECTOR_V;
    }
    else
    {
        sector = SVM_SECTOR_VI;
    }

    return sector;
}

static void SVM_CalculateTimes(
    const SVM_Sector_Type sector,
    const MatrixFloat angle_rad,
    const MatrixFloat m,
    MatrixFloat * const t1,
    MatrixFloat * const t2)
{
    MatrixFloat cos_t1;
    MatrixFloat cos_t2;
    MatrixFloat scale;

    scale = SVM_SQRT3_OVER_2_F * m;

    /* Initialize outputs */
    *t1 = SVM_ZERO_F;
    *t2 = SVM_ZERO_F;

    switch (sector)
    {
        case SVM_SECTOR_I:
        {
            /* T1 = (√3/2)·m·cos(ωt + π/6) */
            /* T2 = (√3/2)·m·cos(ωt - π/2) */
            cos_t1 = cosf(angle_rad + SVM_PI_OVER_6_F);
            cos_t2 = cosf(angle_rad - SVM_PI_OVER_2_F);
            break;
        }

        case SVM_SECTOR_II:
        {
            /* T1 = (√3/2)·m·cos(ωt - π/6) */
            /* T2 = (√3/2)·m·cos(ωt - 5π/6) */
            cos_t1 = cosf(angle_rad - SVM_PI_OVER_6_F);
            cos_t2 = cosf(angle_rad - (5.0f * SVM_PI_OVER_6_F));
            break;
        }

        case SVM_SECTOR_III:
        {
            /* T1 = (√3/2)·m·cos(ωt - π/2) */
            /* T2 = (√3/2)·m·cos(ωt - 7π/6) */
            cos_t1 = cosf(angle_rad - SVM_PI_OVER_2_F);
            cos_t2 = cosf(angle_rad - (7.0f * SVM_PI_OVER_6_F));
            break;
        }

        case SVM_SECTOR_IV:
        {
            /* T1 = (√3/2)·m·cos(ωt - 5π/6) */
            /* T2 = (√3/2)·m·cos(ωt - 3π/2) */
            cos_t1 = cosf(angle_rad - (5.0f * SVM_PI_OVER_6_F));
            cos_t2 = cosf(angle_rad - (3.0f * SVM_PI_OVER_2_F));
            break;
        }

        case SVM_SECTOR_V:
        {
            /* T1 = (√3/2)·m·cos(ωt - 7π/6) */
            /* T2 = (√3/2)·m·cos(ωt - 11π/6) */
            cos_t1 = cosf(angle_rad - (7.0f * SVM_PI_OVER_6_F));
            cos_t2 = cosf(angle_rad - (11.0f * SVM_PI_OVER_6_F));
            break;
        }

        case SVM_SECTOR_VI:
        {
            /* T1 = (√3/2)·m·cos(ωt - 3π/2) */
            /* T2 = (√3/2)·m·cos(ωt - π/6) */
            cos_t1 = cosf(angle_rad - (3.0f * SVM_PI_OVER_2_F));
            cos_t2 = cosf(angle_rad - SVM_PI_OVER_6_F);
            break;
        }

        default:
        {
            /* MISRA C 2012 Rule 16.4: Default clause required */
            cos_t1 = SVM_ZERO_F;
            cos_t2 = SVM_ZERO_F;
            break;
        }
    }

    *t1 = scale * cos_t1;
    *t2 = scale * cos_t2;

    /* Clamp to non-negative */
    if (*t1 < SVM_ZERO_F)
    {
        *t1 = SVM_ZERO_F;
    }
    else
    {
        /* No action - value already non-negative */
    }

    if (*t2 < SVM_ZERO_F)
    {
        *t2 = SVM_ZERO_F;
    }
    else
    {
        /* No action - value already non-negative */
    }

    /* Prevent overflow (overmodulation protection) */
    if ((*t1 + *t2) > SVM_ONE_F)
    {
        MatrixFloat scale_factor;

        scale_factor = SVM_ONE_F / (*t1 + *t2);
        *t1 *= scale_factor;
        *t2 *= scale_factor;
    }
    else
    {
        /* No action - no overflow */
    }
}

MatrixStatus_Type SVM_CalculateDutyCycle(
    const MatrixFloat modulation_index,
    const MatrixFloat angle_rad,
    SVM_DutyCycle_Type * const duty)
{
    MatrixFloat t1;
    MatrixFloat t2;
    MatrixFloat t0;
    MatrixFloat ta;
    MatrixFloat tb;
    MatrixFloat tc;
    SVM_Sector_Type sector;
    MatrixStatus_Type status;

    status = MATRIX_SUCCESS;

    /* Check for NULL pointer */
    if (duty == NULL)
    {
        status = MATRIX_ERROR_NULL_PTR;
    }
    else
    {
        /* Validate input range */
        if ((modulation_index < SVM_ZERO_F) || (modulation_index > SVM_ONE_F))
        {
            status = MATRIX_ERROR_OUT_OF_BOUNDS;
        }
        else
        {
            /* Get sector from angle */
            sector = SVM_GetSectorFromAngle(angle_rad);
            duty->sector = sector;

            /* Calculate times T1 and T2 */
            SVM_CalculateTimes(sector, angle_rad, modulation_index, &t1, &t2);

            /* Calculate zero vector time (symmetric: T0 = T7) */
            t0 = (SVM_ONE_F - t1 - t2) * SVM_HALF_F;

            if (t0 < SVM_ZERO_F)
            {
                t0 = SVM_ZERO_F;
            }
            else
            {
                /* No action - t0 already valid */
            }

            /* Assign duty cycles based on sector */
            switch (sector)
            {
                case SVM_SECTOR_I:
                {
                    /* Sector I: A-on, B-on, C-off sequence */
                    ta = t1 + t2 + t0;
                    tb = t2 + t0;
                    tc = t0;
                    break;
                }

                case SVM_SECTOR_II:
                {
                    /* Sector II pattern */
                    ta = t1 + t0;
                    tb = t1 + t2 + t0;
                    tc = t0;
                    break;
                }

                case SVM_SECTOR_III:
                {
                    /* Sector III pattern */
                    ta = t0;
                    tb = t1 + t2 + t0;
                    tc = t2 + t0;
                    break;
                }

                case SVM_SECTOR_IV:
                {
                    /* Sector IV pattern */
                    ta = t0;
                    tb = t1 + t0;
                    tc = t1 + t2 + t0;
                    break;
                }

                case SVM_SECTOR_V:
                {
                    /* Sector V pattern */
                    ta = t2 + t0;
                    tb = t0;
                    tc = t1 + t2 + t0;
                    break;
                }

                case SVM_SECTOR_VI:
                {
                    /* Sector VI pattern */
                    ta = t1 + t2 + t0;
                    tb = t0;
                    tc = t1 + t0;
                    break;
                }

                default:
                {
                    /* MISRA C 2012 Rule 16.4: Default clause required */
                    status = MATRIX_ERROR_OUT_OF_BOUNDS;
                    ta = SVM_ZERO_F;
                    tb = SVM_ZERO_F;
                    tc = SVM_ZERO_F;
                    break;
                }
            }

            if (status == MATRIX_SUCCESS)
            {
                /* Clamp duty cycles to valid range [0, 1] */
                ta = SVM_ClampFloat(ta);
                tb = SVM_ClampFloat(tb);
                tc = SVM_ClampFloat(tc);

                /* Convert to Q31 format using Matrix library function */
                duty->ta = Matrix_FloatToQ31(ta);
                duty->tb = Matrix_FloatToQ31(tb);
                duty->tc = Matrix_FloatToQ31(tc);
            }
            else
            {
                /* No action - error already set */
            }
        }
    }

    return status;
}

MatrixStatus_Type SVM_GetSectorFromDQ(
    const MatrixElement vd,
    const MatrixElement vq,
    SVM_Sector_Type * const sector)
{
    MatrixFloat vd_f;
    MatrixFloat vq_f;
    MatrixFloat sqrt3_vd;
    MatrixStatus_Type status;

    status = MATRIX_SUCCESS;

    /* Check for NULL pointer */
    if (sector == NULL)
    {
        status = MATRIX_ERROR_NULL_PTR;
    }
    else
    {
        /* Convert Q31 to float using Matrix library function */
        vd_f = Matrix_Q31ToFloat(vd);
        vq_f = Matrix_Q31ToFloat(vq);
        sqrt3_vd = SVM_SQRT3_F * vd_f;

        /* Determine sector based on dq components */
        if (vq_f >= SVM_ZERO_F)
        {
            /* Upper half-plane */
            if (vq_f > sqrt3_vd)
            {
                *sector = SVM_SECTOR_II;
            }
            else if (vq_f > -sqrt3_vd)
            {
                *sector = SVM_SECTOR_I;
            }
            else
            {
                *sector = SVM_SECTOR_VI;
            }
        }
        else
        {
            /* Lower half-plane */
            if (vq_f < -sqrt3_vd)
            {
                *sector = SVM_SECTOR_V;
            }
            else if (vq_f < sqrt3_vd)
            {
                *sector = SVM_SECTOR_IV;
            }
            else
            {
                *sector = SVM_SECTOR_III;
            }
        }
    }

    return status;
}

MatrixStatus_Type SVM_GetCompareValues(
    const SVM_DutyCycle_Type * const duty,
    const uint32_T timer_period,
    uint32_T * const compare_a,
    uint32_T * const compare_b,
    uint32_T * const compare_c)
{
    uint32_T ta_ticks;
    uint32_T tb_ticks;
    uint32_T tc_ticks;
    MatrixStatus_Type status;

    status = MATRIX_SUCCESS;

    /* Check for NULL pointers */
    if ((duty == NULL) || (compare_a == NULL) ||
        (compare_b == NULL) || (compare_c == NULL))
    {
        status = MATRIX_ERROR_NULL_PTR;
    }
    else
    {
        /* Check for valid timer period */
        if (timer_period == 0U)
        {
            status = MATRIX_ERROR_DIV_BY_ZERO;
        }
        else
        {
            /* Convert Q31 duty cycles (0 to Q31_ONE) to timer ticks */
            ta_ticks = (uint32_T)(((uint64_T)duty->ta * (uint64_T)timer_period) / (uint64_T)Q31_ONE);
            tb_ticks = (uint32_T)(((uint64_T)duty->tb * (uint64_T)timer_period) / (uint64_T)Q31_ONE);
            tc_ticks = (uint32_T)(((uint64_T)duty->tc * (uint64_T)timer_period) / (uint64_T)Q31_ONE);

            /* For center-aligned PWM with up-down counter:
             * Compare value = (period - on_time) / 2
             * This ensures the output is high for 'on_time' ticks centered in the period
             */
            *compare_a = (timer_period - ta_ticks) / 2U;
            *compare_b = (timer_period - tb_ticks) / 2U;
            *compare_c = (timer_period - tc_ticks) / 2U;
        }
    }

    return status;
}

void SVM_GetDutyCyclesFloat(
    const SVM_DutyCycle_Type * const duty,
    MatrixFloat * const ta,
    MatrixFloat * const tb,
    MatrixFloat * const tc)
{
    /* Check for NULL pointers */
    if ((duty != NULL) && (ta != NULL) && (tb != NULL) && (tc != NULL))
    {
        *ta = Matrix_Q31ToFloat(duty->ta);
        *tb = Matrix_Q31ToFloat(duty->tb);
        *tc = Matrix_Q31ToFloat(duty->tc);
    }
    else
    {
        /* MISRA C 2012 Rule 15.7: Empty else clause required */
        /* No action for NULL pointers - function does nothing */
    }
}

