"""
embedsim_control_block.py  —  C Backend Only

This module provides a VectorBlock that interfaces with the C‑implemented
motor control algorithm. It packs the simulation inputs into the expected
format, calls the control step, and returns duty cycles.

Debugging of signals should be done externally using SignalPrinter blocks.
"""

import os
import sys
from pathlib import Path

import numpy as np

from embedsim.core_blocks import VectorBlock, VectorSignal, DEFAULT_DTYPE

# ---------------------------------------------------------------------------
# Path setup for C extension imports
# ---------------------------------------------------------------------------
_HERE = Path(__file__).resolve().parent
_C_SRC = _HERE / "c_src"

for _p in (str(_HERE), str(_C_SRC)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

# ===========================================================================
# Import from the C wrapper (generated by Cython)
# ===========================================================================
from embedsim_control_wrapper import (
    control_init,                    # one‑time initialisation of the C controller
    control_step as c_control_step,  # main control update function
    clarke,                          # Clarke transform (3‑phase → stationary αβ)
    park,                            # Park transform (stationary → rotating dq)
    inv_park,                        # Inverse Park (rotating → stationary)
    inv_clarke,                      # Inverse Clarke (stationary → 3‑phase)
)

# ===========================================================================
# Constants – control algorithm selector
# ===========================================================================
SIM_CTRL_OPEN_LOOP = 0   # Open‑loop V/f control (no feedback)
SIM_CTRL_DFC       = 1   # Direct Flux Control (sensorless FOC variant)


# ===========================================================================
# EmbedSimControlBlock – main block class
# ===========================================================================

class EmbedSimControlBlock(VectorBlock):
    """
    A VectorBlock that executes the C‑based motor control algorithm.

    Inputs (expected as a 10‑element vector from CtrlPacker):
        [speed_ref_rpm, ia, ib, ic, speed_sensor_rpm, dt, theta_m, valid, 0, Vdc]

    Outputs:
        [duty_u, duty_v, duty_w, valid_out]   # duty cycles in [0,1], valid flag

    All I/O debugging is intentionally left out; use SignalPrinter blocks in
    the simulation graph to inspect inputs and outputs.
    """
    NUM_INPUTS   = 1          # single vector input
    OUTPUT_SIZE  = 4          # four output elements

    def __init__(self, name="ctrl", dt_s=50e-6, ctrl_alg=SIM_CTRL_DFC,
                 vdc_nom=12.0, use_c_backend=True, dtype=None):
        """
        Initialise the control block.

        Args:
            name:       Block name (used in logging and signal labels).
            dt_s:       Control loop sample time (seconds).
            ctrl_alg:   Algorithm selector (SIM_CTRL_OPEN_LOOP or SIM_CTRL_DFC).
            vdc_nom:    Nominal DC bus voltage (V) – used for scaling.
            use_c_backend: Must be True (this block only supports C backend).
            dtype:      Data type (defaults to float64).
        """
        super().__init__(name, use_c_backend=True, dtype=dtype)

        self.dt_s      = float(dt_s)
        self.ctrl_alg  = int(ctrl_alg)
        self.vdc_nom   = float(vdc_nom)
        self.vector_size = 4
        self.output_label = "[duty_u,duty_v,duty_w,valid]"
        self.is_dynamic = False   # not a dynamic block (no internal state)

        # Initialise the C controller (allocates internal structures)
        control_init()

        # Informational startup messages (these are not debug prints)
        mode_name = "DFC" if ctrl_alg == SIM_CTRL_DFC else "OPEN_LOOP"
        print(f"[Control] C backend '{name}'")
        print(f"[Control]   DT: {dt_s*1e6:.0f} us")
        print(f"[Control]   Mode: {mode_name}")
        print(f"[Control]   Vdc: {vdc_nom:.1f} V")

    # ------------------------------------------------------------------------
    # Main computation method (called every simulation step)
    # ------------------------------------------------------------------------
    def compute(self, t, dt, input_values=None):
        """
        Execute one control step.

        The input vector is unpacked, passed to the C function, and the
        resulting duty cycles are packed into the output VectorSignal.
        """
        # Unpack the 10‑element input vector (see CtrlPacker for format)
        u = input_values[0].value

        speed_ref_rpm       = float(u[0])
        ia                  = float(u[1])
        ib                  = float(u[2])
        ic                  = float(u[3])
        speed_sensor_rpm    = float(u[4])
        sample_time         = float(u[5])    # dt (passed for completeness)
        position_sensor_rad = float(u[6])
        valid_in            = int(u[7])
        # u[8] is reserved (0.0)
        vdc                 = float(u[9])

        # Call the C control step – it returns a dict with PWM duties and validity
        result = c_control_step(
            ia=ia,
            ib=ib,
            ic=ic,
            rotor_position_rad=position_sensor_rad,
            rotor_velocity_rpm=speed_sensor_rpm,
            speed_ref_rpm=speed_ref_rpm,
            vdc=vdc,
            sample_time=sample_time,
            ctrl_alg=self.ctrl_alg,
            valid_in=valid_in,
        )

        # Build the output vector: duty cycles and a valid flag
        output_array = np.array([
            float(result['pwm_u']),
            float(result['pwm_v']),
            float(result['pwm_w']),
            float(result['valid_out']),
        ], dtype=DEFAULT_DTYPE)

        self.output = VectorSignal(output_array, self.name)
        return self.output

    def reset(self):
        """Reset the block state (nothing to reset here)."""
        super().reset()

    # ========================================================================
    # Static transform methods – convenient wrappers around C functions
    # These can be used directly by the user without instantiating the block.
    # ========================================================================

    @staticmethod
    def clarke(u, v, w):
        """Clarke transform: (u,v,w) → (alpha, beta)."""
        return clarke(u, v, w)

    @staticmethod
    def park(alpha, beta, theta):
        """Park transform: (alpha, beta, theta) → (d, q)."""
        return park(alpha, beta, theta)

    @staticmethod
    def inv_park(d, q, theta):
        """Inverse Park transform: (d, q, theta) → (alpha, beta)."""
        return inv_park(d, q, theta)

    @staticmethod
    def inv_clarke(alpha, beta):
        """Inverse Clarke transform: (alpha, beta) → (u, v, w)."""
        return inv_clarke(alpha, beta)

    @staticmethod
    def svm(alpha, beta, vdc):
        """
        Space Vector PWM from alpha/beta voltage references.

        This method computes the three duty cycles directly from the stationary‑
        frame voltage references using inverse Clarke and centre‑aligned PWM.

        Args:
            alpha, beta : float   – voltage references in stationary frame (V)
            vdc : float           – DC bus voltage (V)

        Returns:
            (duty_u, duty_v, duty_w) – duty cycles clamped to [0, 1]
        """
        # 1) Convert αβ → three phase voltages
        u, v, w = inv_clarke(alpha, beta)

        # 2) Duty cycle = (V_phase / Vdc) + 0.5  (centre‑aligned PWM)
        duty_u = (u / vdc) + 0.5
        duty_v = (v / vdc) + 0.5
        duty_w = (w / vdc) + 0.5

        # 3) Numerical safety: clamp to [0, 1]
        duty_u = max(0.0, min(1.0, duty_u))
        duty_v = max(0.0, min(1.0, duty_v))
        duty_w = max(0.0, min(1.0, duty_w))

        return duty_u, duty_v, duty_w

    def __repr__(self):
        """Human‑readable representation of the block."""
        mode_name = "DFC" if self.ctrl_alg == SIM_CTRL_DFC else "OPEN_LOOP"
        return f"EmbedSimControlBlock('{self.name}', dt={self.dt_s*1e6:.0f}us, mode={mode_name})"


# ===========================================================================
# Public API
# ===========================================================================
__all__ = ["EmbedSimControlBlock", "SIM_CTRL_OPEN_LOOP", "SIM_CTRL_DFC"]