# setup_processor.py
# Auto-generated by ControlForge
#
# Usage:
#   python setup_processor.py build_ext --inplace
#
# Prerequisite: processor.c must exist in the same directory.

import sys
from setuptools import setup, Extension
from Cython.Build import cythonize
import numpy as np

# Detect compiler: MSVC uses /O2, GCC/Clang use -O3
if sys.platform == 'win32':
    compile_args = ['/O2']
else:
    compile_args = ['-O3', '-ffast-math']

ext = Extension(
    name='processor_wrapper',
    # Include both the Cython wrapper AND your C implementation.
    # This compiles everything together so the linker finds
    # processor_compute() without a separate .dll/.lib step.
    sources=[
        'processor_wrapper.pyx',
        'processor.c',
    ],
    include_dirs=[np.get_include()],
    extra_compile_args=compile_args,
)

setup(
    name='processor_wrapper',
    ext_modules=cythonize(
        [ext],
        compiler_directives={
            'language_level': '3',
            'boundscheck':    False,
            'wraparound':     False,
            'cdivision':      True,
        },
        annotate=True,
    ),
)